/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'README-form-resources',
        'resources-directory',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'Password_System',
        'struts-actions-detailed',
        'struts-actions-summary',
        'integrator-system-architecture',
      ],
    },
    {
      type: 'category',
      label: 'API Documentation',
      link: {
        type: 'generated-index',
        title: 'API Reference',
        description: 'Generated API documentation from Javadoc',
        slug: '/api',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api', // Automatically generate sidebar from docs/api folder
        },
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'dsGuideline',
        'Testing_Exclusion_of_MCEDT_and_HinValidator_tests',
      ],
    },
    {
      type: 'category',
      label: 'Legacy',
      items: [
        'MyDrugref',
        'legacy-hapi-dynamic-loading',
      ],
    },
  ],
};

module.exports = sidebars;