package ca.openosp.openo.caisi_integrator.util;

public enum Role
{
    PSYCHIATRIST, 
    DOCTOR, 
    RN, 
    CLINICAL_SOCIAL_WORKER, 
    RECREATION_THERAPIST, 
    RPN, 
    NURSE_MANAGER, 
    CLINICAL_CASE_MANAGER, 
    CLINICAL_ASSISTANT, 
    MEDICAL_SECRETARY, 
    HOUSING_WORKER, 
    COUNSELLOR, 
    CASE_MANAGER, 
    SECRETARY, 
    RECEPTIONIST, 
    SUPPORT_WORKER, 
    CLIENT_SERVICE_WORKER, 
    PROPERTY_STAFF, 
    CSW, 
    SUPPORT_COUNSELLOR;
}
