package ca.openosp.openo.caisi_integrator.dao;

import java.io.ObjectInputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import org.apache.openjpa.util.ObjectId;
import org.apache.openjpa.enhance.FieldConsumer;
import org.apache.openjpa.util.InternalException;
import org.apache.openjpa.enhance.FieldSupplier;
import org.apache.openjpa.enhance.RedefinitionHelper;
import org.apache.openjpa.enhance.PersistenceCapable;
import org.apache.openjpa.enhance.PCRegistry;
import org.apache.commons.lang3.StringUtils;
import org.apache.openjpa.enhance.StateManager;
import javax.persistence.TemporalType;
import javax.persistence.Temporal;
import java.util.Date;
import org.apache.openjpa.persistence.jdbc.Index;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;

/**
 * JPA entity representing a cached Ontario billing item within the CAISI Integrator system.
 *
 * This entity is part of OpenO EMR's multi-facility integration framework, specifically designed
 * to cache Ontario-specific billing data (ON billing items) across integrated healthcare facilities.
 * The CAISI Integrator allows multiple OpenO EMR installations to share patient data, appointments,
 * and billing information in a federated healthcare network.
 *
 * <p>The cached billing items include essential billing information such as service codes, diagnostic
 * codes (dx, dx1, dx2), provider identifiers, appointment references, and billing status. This caching
 * mechanism improves performance when accessing billing data across multiple facilities and provides
 * a local copy for integrator queries.</p>
 *
 * <p><b>Healthcare Context:</b> Ontario billing uses province-specific service codes (OHIP Schedule of
 * Benefits) and diagnostic codes (ICD-9/ICD-10). This entity captures billing submissions including
 * the primary service provider (caisiProviderId), appointment provider (apptProviderId), and assistant
 * provider (asstProviderId) for procedures requiring multiple healthcare professionals.</p>
 *
 * <p><b>OpenJPA Enhancement:</b> This class implements {@link PersistenceCapable} and contains
 * bytecode-enhanced methods (prefixed with "pc") auto-generated by OpenJPA for persistence operations.
 * These methods handle field access tracking, state management, and object identity for JPA operations.</p>
 *
 * @see AbstractModel
 * @see FacilityIdIntegerCompositePk
 * @since 2026-01-24
 */
@Entity
public class CachedBillingOnItem extends AbstractModel<FacilityIdIntegerCompositePk> implements Comparable<CachedBillingOnItem>, PersistenceCapable
{
    @EmbeddedId
    private FacilityIdIntegerCompositePk facilityBillingOnItemPk;
    @Column(nullable = false)
    @Index
    private Integer caisiDemographicId;
    @Column(nullable = false, length = 16)
    @Index
    private String caisiProviderId;
    @Column(length = 16)
    private String apptProviderId;
    @Column(length = 16)
    private String asstProviderId;
    @Column
    private Integer appointmentId;
    @Temporal(TemporalType.DATE)
    private Date serviceDate;
    @Column(length = 20)
    private String serviceCode;
    @Column(length = 4)
    private String dx;
    @Column(length = 4)
    private String dx1;
    @Column(length = 4)
    private String dx2;
    @Column(length = 1)
    private String status;
    private static int pcInheritedFieldCount;
    private static String[] pcFieldNames;
    private static Class[] pcFieldTypes;
    private static byte[] pcFieldFlags;
    private static Class pcPCSuperclass;
    protected transient StateManager pcStateManager;
    static /* synthetic */ Class class$Ljava$lang$Integer;
    static /* synthetic */ Class class$Ljava$lang$String;
    static /* synthetic */ Class class$Lca$openosp$openo$caisi_integrator$dao$FacilityIdIntegerCompositePk;
    static /* synthetic */ Class class$Ljava$util$Date;
    static /* synthetic */ Class class$Lca$openosp$openo$caisi_integrator$dao$CachedBillingOnItem;
    private transient Object pcDetachedState;
    private static final long serialVersionUID;

    /**
     * Default constructor creating a new CachedBillingOnItem with all fields initialized to null.
     *
     * This constructor is used by JPA/OpenJPA for entity instantiation during database operations
     * and by the persistence framework when creating new instances via pcNewInstance methods.
     */
    public CachedBillingOnItem() {
        this.caisiDemographicId = null;
        this.caisiProviderId = null;
        this.apptProviderId = null;
        this.asstProviderId = null;
        this.appointmentId = null;
        this.serviceDate = null;
        this.serviceCode = null;
        this.dx = null;
        this.dx1 = null;
        this.dx2 = null;
        this.status = null;
    }

    /**
     * Gets the composite primary key identifying this billing item across facilities.
     *
     * @return FacilityIdIntegerCompositePk the composite key containing facility ID and item ID
     */
    public FacilityIdIntegerCompositePk getFacilityIdIntegerCompositePk() {
        return pcGetfacilityBillingOnItemPk(this);
    }

    /**
     * Sets the composite primary key for this billing item.
     *
     * @param facilityBillingOnItemPk FacilityIdIntegerCompositePk the composite key to set
     */
    public void setFacilityIdIntegerCompositePk(final FacilityIdIntegerCompositePk facilityBillingOnItemPk) {
        pcSetfacilityBillingOnItemPk(this, facilityBillingOnItemPk);
    }

    /**
     * Gets the CAISI demographic (patient) identifier for this billing item.
     *
     * @return Integer the patient demographic ID
     */
    public Integer getCaisiDemographicId() {
        return pcGetcaisiDemographicId(this);
    }

    /**
     * Sets the CAISI demographic (patient) identifier for this billing item.
     *
     * @param caisiDemographicId Integer the patient demographic ID to set
     */
    public void setCaisiDemographicId(final Integer caisiDemographicId) {
        pcSetcaisiDemographicId(this, caisiDemographicId);
    }

    /**
     * Gets the CAISI provider identifier responsible for this billing item.
     *
     * This is the primary healthcare provider associated with the billable service.
     *
     * @return String the provider ID (max 16 characters)
     */
    public String getCaisiProviderId() {
        return pcGetcaisiProviderId(this);
    }

    /**
     * Sets the CAISI provider identifier for this billing item.
     *
     * The provider ID is automatically trimmed to empty string if null or whitespace.
     *
     * @param caisiProviderId String the provider ID to set (max 16 characters, will be trimmed)
     */
    public void setCaisiProviderId(final String caisiProviderId) {
        pcSetcaisiProviderId(this, StringUtils.trimToEmpty(caisiProviderId));
    }

    /**
     * Gets the appointment provider identifier.
     *
     * This may differ from the CAISI provider if the service was performed by a different
     * provider than the one who scheduled the appointment.
     *
     * @return String the appointment provider ID (max 16 characters), or null if not set
     */
    public String getApptProviderId() {
        return pcGetapptProviderId(this);
    }

    /**
     * Sets the appointment provider identifier.
     *
     * The provider ID is automatically trimmed, with empty strings converted to null.
     *
     * @param apptProviderId String the appointment provider ID to set (max 16 characters)
     */
    public void setApptProviderId(final String apptProviderId) {
        pcSetapptProviderId(this, StringUtils.trimToNull(apptProviderId));
    }

    /**
     * Gets the assistant provider identifier.
     *
     * Used when a billable service requires an assisting healthcare professional
     * (e.g., surgical assistant, anesthesiologist).
     *
     * @return String the assistant provider ID (max 16 characters), or null if not applicable
     */
    public String getAsstProviderId() {
        return pcGetasstProviderId(this);
    }

    /**
     * Sets the assistant provider identifier.
     *
     * The provider ID is automatically trimmed, with empty strings converted to null.
     *
     * @param asstProviderId String the assistant provider ID to set (max 16 characters)
     */
    public void setAsstProviderId(final String asstProviderId) {
        pcSetasstProviderId(this, StringUtils.trimToNull(asstProviderId));
    }

    /**
     * Gets the appointment identifier associated with this billing item.
     *
     * Links the billing record to the specific appointment during which the service was provided.
     *
     * @return Integer the appointment ID, or null if not associated with an appointment
     */
    public Integer getAppointmentId() {
        return pcGetappointmentId(this);
    }

    /**
     * Sets the appointment identifier for this billing item.
     *
     * @param appointmentId Integer the appointment ID to set
     */
    public void setAppointmentId(final Integer appointmentId) {
        pcSetappointmentId(this, appointmentId);
    }

    /**
     * Gets the service date when the billable service was provided.
     *
     * This is the date used for billing submission to OHIP or other Ontario billing systems.
     *
     * @return Date the service date
     */
    public Date getServiceDate() {
        return pcGetserviceDate(this);
    }

    /**
     * Sets the service date for this billing item.
     *
     * @param serviceDate Date the service date to set
     */
    public void setServiceDate(final Date serviceDate) {
        pcSetserviceDate(this, serviceDate);
    }

    /**
     * Gets the Ontario service code for the billable service.
     *
     * Service codes reference the OHIP Schedule of Benefits and identify the specific
     * medical service provided (e.g., "A007A" for office visit).
     *
     * @return String the service code (max 20 characters), or null if not set
     */
    public String getServiceCode() {
        return pcGetserviceCode(this);
    }

    /**
     * Sets the Ontario service code for this billing item.
     *
     * The service code is automatically trimmed, with empty strings converted to null.
     *
     * @param serviceCode String the service code to set (max 20 characters)
     */
    public void setServiceCode(final String serviceCode) {
        pcSetserviceCode(this, StringUtils.trimToNull(serviceCode));
    }

    /**
     * Gets the primary diagnostic code for this billing item.
     *
     * Ontario billing typically uses ICD-9 or ICD-10 diagnostic codes to justify
     * the medical necessity of the billed service.
     *
     * @return String the primary diagnosis code (max 4 characters), or null if not set
     */
    public String getDx() {
        return pcGetdx(this);
    }

    /**
     * Sets the primary diagnostic code for this billing item.
     *
     * The diagnostic code is automatically trimmed, with empty strings converted to null.
     *
     * @param dx String the primary diagnosis code to set (max 4 characters)
     */
    public void setDx(final String dx) {
        pcSetdx(this, StringUtils.trimToNull(dx));
    }

    /**
     * Gets the first secondary diagnostic code.
     *
     * Ontario billing allows up to three diagnostic codes per billing item.
     * This is the first additional diagnosis beyond the primary dx code.
     *
     * @return String the first secondary diagnosis code (max 4 characters), or null if not set
     */
    public String getDx1() {
        return pcGetdx1(this);
    }

    /**
     * Sets the first secondary diagnostic code.
     *
     * The diagnostic code is automatically trimmed, with empty strings converted to null.
     *
     * @param dx String the first secondary diagnosis code to set (max 4 characters)
     */
    public void setDx1(final String dx) {
        pcSetdx1(this, StringUtils.trimToNull(dx));
    }

    /**
     * Gets the second secondary diagnostic code.
     *
     * Ontario billing allows up to three diagnostic codes per billing item.
     * This is the second additional diagnosis beyond the primary dx code.
     *
     * @return String the second secondary diagnosis code (max 4 characters), or null if not set
     */
    public String getDx2() {
        return pcGetdx2(this);
    }

    /**
     * Sets the second secondary diagnostic code.
     *
     * The diagnostic code is automatically trimmed, with empty strings converted to null.
     *
     * @param dx String the second secondary diagnosis code to set (max 4 characters)
     */
    public void setDx2(final String dx) {
        pcSetdx2(this, StringUtils.trimToNull(dx));
    }

    /**
     * Gets the billing status for this item.
     *
     * Status indicates the current state of the billing claim (e.g., pending, submitted, paid, rejected).
     *
     * @return String the billing status (max 1 character), or null if not set
     */
    public String getStatus() {
        return pcGetstatus(this);
    }

    /**
     * Sets the billing status for this item.
     *
     * @param status String the billing status to set (max 1 character)
     */
    public void setStatus(final String status) {
        pcSetstatus(this, status);
    }

    /**
     * Compares this billing item with another based on the CAISI item ID.
     *
     * @param o CachedBillingOnItem the other billing item to compare with
     * @return int negative if this item ID is less, zero if equal, positive if greater
     */
    @Override
    public int compareTo(final CachedBillingOnItem o) {
        return pcGetfacilityBillingOnItemPk(this).getCaisiItemId() - pcGetfacilityBillingOnItemPk(o).getCaisiItemId();
    }

    /**
     * Gets the entity identifier, which is the composite primary key.
     *
     * @return FacilityIdIntegerCompositePk the composite key identifying this billing item
     */
    @Override
    public FacilityIdIntegerCompositePk getId() {
        return pcGetfacilityBillingOnItemPk(this);
    }

    /**
     * Gets the OpenJPA bytecode enhancement contract version.
     *
     * This method is auto-generated by OpenJPA enhancement and indicates the version
     * of the persistence capability contract implemented by this entity.
     *
     * @return int the enhancement contract version (currently 2)
     */
    public int pcGetEnhancementContractVersion() {
        return 2;
    }

    /**
     * Static initializer registering this entity with OpenJPA's persistence capability registry.
     *
     * This block is auto-generated by OpenJPA enhancement and configures field metadata,
     * persistence flags, and registers the entity type with the JPA provider.
     */
    static {
        serialVersionUID = -7391385481748879875L;
        CachedBillingOnItem.pcFieldNames = new String[] { "appointmentId", "apptProviderId", "asstProviderId", "caisiDemographicId", "caisiProviderId", "dx", "dx1", "dx2", "facilityBillingOnItemPk", "serviceCode", "serviceDate", "status" };
        CachedBillingOnItem.pcFieldTypes = new Class[] { (CachedBillingOnItem.class$Ljava$lang$Integer != null) ? CachedBillingOnItem.class$Ljava$lang$Integer : (CachedBillingOnItem.class$Ljava$lang$Integer = class$("java.lang.Integer")), (CachedBillingOnItem.class$Ljava$lang$String != null) ? CachedBillingOnItem.class$Ljava$lang$String : (CachedBillingOnItem.class$Ljava$lang$String = class$("java.lang.String")), (CachedBillingOnItem.class$Ljava$lang$String != null) ? CachedBillingOnItem.class$Ljava$lang$String : (CachedBillingOnItem.class$Ljava$lang$String = class$("java.lang.String")), (CachedBillingOnItem.class$Ljava$lang$Integer != null) ? CachedBillingOnItem.class$Ljava$lang$Integer : (CachedBillingOnItem.class$Ljava$lang$Integer = class$("java.lang.Integer")), (CachedBillingOnItem.class$Ljava$lang$String != null) ? CachedBillingOnItem.class$Ljava$lang$String : (CachedBillingOnItem.class$Ljava$lang$String = class$("java.lang.String")), (CachedBillingOnItem.class$Ljava$lang$String != null) ? CachedBillingOnItem.class$Ljava$lang$String : (CachedBillingOnItem.class$Ljava$lang$String = class$("java.lang.String")), (CachedBillingOnItem.class$Ljava$lang$String != null) ? CachedBillingOnItem.class$Ljava$lang$String : (CachedBillingOnItem.class$Ljava$lang$String = class$("java.lang.String")), (CachedBillingOnItem.class$Ljava$lang$String != null) ? CachedBillingOnItem.class$Ljava$lang$String : (CachedBillingOnItem.class$Ljava$lang$String = class$("java.lang.String")), (CachedBillingOnItem.class$Lca$openosp$openo$caisi_integrator$dao$FacilityIdIntegerCompositePk != null) ? CachedBillingOnItem.class$Lca$openosp$openo$caisi_integrator$dao$FacilityIdIntegerCompositePk : (CachedBillingOnItem.class$Lca$openosp$openo$caisi_integrator$dao$FacilityIdIntegerCompositePk = class$("ca.openosp.openo.caisi_integrator.dao.FacilityIdIntegerCompositePk")), (CachedBillingOnItem.class$Ljava$lang$String != null) ? CachedBillingOnItem.class$Ljava$lang$String : (CachedBillingOnItem.class$Ljava$lang$String = class$("java.lang.String")), (CachedBillingOnItem.class$Ljava$util$Date != null) ? CachedBillingOnItem.class$Ljava$util$Date : (CachedBillingOnItem.class$Ljava$util$Date = class$("java.util.Date")), (CachedBillingOnItem.class$Ljava$lang$String != null) ? CachedBillingOnItem.class$Ljava$lang$String : (CachedBillingOnItem.class$Ljava$lang$String = class$("java.lang.String")) };
        CachedBillingOnItem.pcFieldFlags = new byte[] { 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26 };
        PCRegistry.register((CachedBillingOnItem.class$Lca$openosp$openo$caisi_integrator$dao$CachedBillingOnItem != null) ? CachedBillingOnItem.class$Lca$openosp$openo$caisi_integrator$dao$CachedBillingOnItem : (CachedBillingOnItem.class$Lca$openosp$openo$caisi_integrator$dao$CachedBillingOnItem = class$("ca.openosp.openo.caisi_integrator.dao.CachedBillingOnItem")), CachedBillingOnItem.pcFieldNames, CachedBillingOnItem.pcFieldTypes, CachedBillingOnItem.pcFieldFlags, CachedBillingOnItem.pcPCSuperclass, "CachedBillingOnItem", (PersistenceCapable)new CachedBillingOnItem());
    }

    /**
     * Utility method for loading classes by name during static initialization.
     *
     * This is a synthetic method auto-generated by the Java compiler to support
     * class literal references in the static initializer.
     *
     * @param className String the fully qualified class name to load
     * @return Class the loaded class object
     * @throws NoClassDefFoundError if the class cannot be found
     */
    static /* synthetic */ Class class$(final String className) {
        try {
            return Class.forName(className);
        }
        catch (final ClassNotFoundException ex) {
            throw new NoClassDefFoundError(ex.getMessage());
        }
    }

    /**
     * Clears all managed field values to null.
     *
     * This method is used by OpenJPA during entity lifecycle management,
     * particularly when creating new instances or managing detached state.
     */
    protected void pcClearFields() {
        this.appointmentId = null;
        this.apptProviderId = null;
        this.asstProviderId = null;
        this.caisiDemographicId = null;
        this.caisiProviderId = null;
        this.dx = null;
        this.dx1 = null;
        this.dx2 = null;
        this.facilityBillingOnItemPk = null;
        this.serviceCode = null;
        this.serviceDate = null;
        this.status = null;
    }

    /**
     * Creates a new instance with a state manager and object ID.
     *
     * This OpenJPA-managed method creates a new entity instance, optionally clears its fields,
     * assigns a state manager, and copies key fields from the provided object ID.
     *
     * @param pcStateManager StateManager the OpenJPA state manager for this instance
     * @param o Object the object ID from which to copy key field values
     * @param b boolean true to clear all fields before initialization
     * @return PersistenceCapable the newly created and initialized instance
     */
    public PersistenceCapable pcNewInstance(final StateManager pcStateManager, final Object o, final boolean b) {
        final CachedBillingOnItem cachedBillingOnItem = new CachedBillingOnItem();
        if (b) {
            cachedBillingOnItem.pcClearFields();
        }
        cachedBillingOnItem.pcStateManager = pcStateManager;
        cachedBillingOnItem.pcCopyKeyFieldsFromObjectId(o);
        return (PersistenceCapable)cachedBillingOnItem;
    }

    /**
     * Creates a new instance with a state manager.
     *
     * This OpenJPA-managed method creates a new entity instance, optionally clears its fields,
     * and assigns a state manager without copying key field values.
     *
     * @param pcStateManager StateManager the OpenJPA state manager for this instance
     * @param b boolean true to clear all fields before initialization
     * @return PersistenceCapable the newly created instance
     */
    public PersistenceCapable pcNewInstance(final StateManager pcStateManager, final boolean b) {
        final CachedBillingOnItem cachedBillingOnItem = new CachedBillingOnItem();
        if (b) {
            cachedBillingOnItem.pcClearFields();
        }
        cachedBillingOnItem.pcStateManager = pcStateManager;
        return (PersistenceCapable)cachedBillingOnItem;
    }

    /**
     * Gets the count of JPA-managed fields in this entity.
     *
     * @return int the number of managed fields (12)
     */
    protected static int pcGetManagedFieldCount() {
        return 12;
    }

    /**
     * Replaces a single managed field with a value from the state manager.
     *
     * This OpenJPA callback is invoked during entity state restoration to update
     * individual field values during database load or merge operations.
     *
     * @param n int the field index to replace
     * @throws IllegalArgumentException if the field index is invalid
     */
    public void pcReplaceField(final int n) {
        final int n2 = n - CachedBillingOnItem.pcInheritedFieldCount;
        if (n2 < 0) {
            throw new IllegalArgumentException();
        }
        switch (n2) {
            case 0: {
                this.appointmentId = (Integer)this.pcStateManager.replaceObjectField((PersistenceCapable)this, n);
                return;
            }
            case 1: {
                this.apptProviderId = this.pcStateManager.replaceStringField((PersistenceCapable)this, n);
                return;
            }
            case 2: {
                this.asstProviderId = this.pcStateManager.replaceStringField((PersistenceCapable)this, n);
                return;
            }
            case 3: {
                this.caisiDemographicId = (Integer)this.pcStateManager.replaceObjectField((PersistenceCapable)this, n);
                return;
            }
            case 4: {
                this.caisiProviderId = this.pcStateManager.replaceStringField((PersistenceCapable)this, n);
                return;
            }
            case 5: {
                this.dx = this.pcStateManager.replaceStringField((PersistenceCapable)this, n);
                return;
            }
            case 6: {
                this.dx1 = this.pcStateManager.replaceStringField((PersistenceCapable)this, n);
                return;
            }
            case 7: {
                this.dx2 = this.pcStateManager.replaceStringField((PersistenceCapable)this, n);
                return;
            }
            case 8: {
                this.facilityBillingOnItemPk = (FacilityIdIntegerCompositePk)this.pcStateManager.replaceObjectField((PersistenceCapable)this, n);
                return;
            }
            case 9: {
                this.serviceCode = this.pcStateManager.replaceStringField((PersistenceCapable)this, n);
                return;
            }
            case 10: {
                this.serviceDate = (Date)this.pcStateManager.replaceObjectField((PersistenceCapable)this, n);
                return;
            }
            case 11: {
                this.status = this.pcStateManager.replaceStringField((PersistenceCapable)this, n);
                return;
            }
            default: {
                throw new IllegalArgumentException();
            }
        }
    }

    /**
     * Replaces multiple managed fields with values from the state manager.
     *
     * This method iterates through an array of field indices and replaces each one.
     *
     * @param array int[] array of field indices to replace
     */
    public void pcReplaceFields(final int[] array) {
        for (int i = 0; i < array.length; ++i) {
            this.pcReplaceField(array[i]);
        }
    }

    /**
     * Provides a single managed field value to the state manager.
     *
     * This OpenJPA callback is invoked to supply current field values during persistence
     * operations such as flush or detachment.
     *
     * @param n int the field index to provide
     * @throws IllegalArgumentException if the field index is invalid
     */
    public void pcProvideField(final int n) {
        final int n2 = n - CachedBillingOnItem.pcInheritedFieldCount;
        if (n2 < 0) {
            throw new IllegalArgumentException();
        }
        switch (n2) {
            case 0: {
                this.pcStateManager.providedObjectField((PersistenceCapable)this, n, (Object)this.appointmentId);
                return;
            }
            case 1: {
                this.pcStateManager.providedStringField((PersistenceCapable)this, n, this.apptProviderId);
                return;
            }
            case 2: {
                this.pcStateManager.providedStringField((PersistenceCapable)this, n, this.asstProviderId);
                return;
            }
            case 3: {
                this.pcStateManager.providedObjectField((PersistenceCapable)this, n, (Object)this.caisiDemographicId);
                return;
            }
            case 4: {
                this.pcStateManager.providedStringField((PersistenceCapable)this, n, this.caisiProviderId);
                return;
            }
            case 5: {
                this.pcStateManager.providedStringField((PersistenceCapable)this, n, this.dx);
                return;
            }
            case 6: {
                this.pcStateManager.providedStringField((PersistenceCapable)this, n, this.dx1);
                return;
            }
            case 7: {
                this.pcStateManager.providedStringField((PersistenceCapable)this, n, this.dx2);
                return;
            }
            case 8: {
                this.pcStateManager.providedObjectField((PersistenceCapable)this, n, (Object)this.facilityBillingOnItemPk);
                return;
            }
            case 9: {
                this.pcStateManager.providedStringField((PersistenceCapable)this, n, this.serviceCode);
                return;
            }
            case 10: {
                this.pcStateManager.providedObjectField((PersistenceCapable)this, n, (Object)this.serviceDate);
                return;
            }
            case 11: {
                this.pcStateManager.providedStringField((PersistenceCapable)this, n, this.status);
                return;
            }
            default: {
                throw new IllegalArgumentException();
            }
        }
    }

    /**
     * Provides multiple managed field values to the state manager.
     *
     * This method iterates through an array of field indices and provides each one.
     *
     * @param array int[] array of field indices to provide
     */
    public void pcProvideFields(final int[] array) {
        for (int i = 0; i < array.length; ++i) {
            this.pcProvideField(array[i]);
        }
    }

    /**
     * Copies a single field value from another instance of this entity.
     *
     * This method is used by OpenJPA during merge and copy operations.
     *
     * @param cachedBillingOnItem CachedBillingOnItem the source instance to copy from
     * @param n int the field index to copy
     * @throws IllegalArgumentException if the field index is invalid
     */
    protected void pcCopyField(final CachedBillingOnItem cachedBillingOnItem, final int n) {
        final int n2 = n - CachedBillingOnItem.pcInheritedFieldCount;
        if (n2 < 0) {
            throw new IllegalArgumentException();
        }
        switch (n2) {
            case 0: {
                this.appointmentId = cachedBillingOnItem.appointmentId;
                return;
            }
            case 1: {
                this.apptProviderId = cachedBillingOnItem.apptProviderId;
                return;
            }
            case 2: {
                this.asstProviderId = cachedBillingOnItem.asstProviderId;
                return;
            }
            case 3: {
                this.caisiDemographicId = cachedBillingOnItem.caisiDemographicId;
                return;
            }
            case 4: {
                this.caisiProviderId = cachedBillingOnItem.caisiProviderId;
                return;
            }
            case 5: {
                this.dx = cachedBillingOnItem.dx;
                return;
            }
            case 6: {
                this.dx1 = cachedBillingOnItem.dx1;
                return;
            }
            case 7: {
                this.dx2 = cachedBillingOnItem.dx2;
                return;
            }
            case 8: {
                this.facilityBillingOnItemPk = cachedBillingOnItem.facilityBillingOnItemPk;
                return;
            }
            case 9: {
                this.serviceCode = cachedBillingOnItem.serviceCode;
                return;
            }
            case 10: {
                this.serviceDate = cachedBillingOnItem.serviceDate;
                return;
            }
            case 11: {
                this.status = cachedBillingOnItem.status;
                return;
            }
            default: {
                throw new IllegalArgumentException();
            }
        }
    }

    /**
     * Copies multiple field values from another instance.
     *
     * This method validates that both instances share the same state manager
     * before copying the specified field values.
     *
     * @param o Object the source instance to copy from (must be CachedBillingOnItem)
     * @param array int[] array of field indices to copy
     * @throws IllegalArgumentException if instances have different state managers
     * @throws IllegalStateException if the state manager is null
     */
    public void pcCopyFields(final Object o, final int[] array) {
        final CachedBillingOnItem cachedBillingOnItem = (CachedBillingOnItem)o;
        if (cachedBillingOnItem.pcStateManager != this.pcStateManager) {
            throw new IllegalArgumentException();
        }
        if (this.pcStateManager == null) {
            throw new IllegalStateException();
        }
        for (int i = 0; i < array.length; ++i) {
            this.pcCopyField(cachedBillingOnItem, array[i]);
        }
    }

    /**
     * Gets the generic context object from the state manager.
     *
     * This context provides additional metadata for the persistence framework.
     *
     * @return Object the generic context, or null if no state manager is present
     */
    public Object pcGetGenericContext() {
        if (this.pcStateManager == null) {
            return null;
        }
        return this.pcStateManager.getGenericContext();
    }

    /**
     * Fetches the object ID for this entity from the state manager.
     *
     * @return Object the object ID, or null if no state manager is present
     */
    public Object pcFetchObjectId() {
        if (this.pcStateManager == null) {
            return null;
        }
        return this.pcStateManager.fetchObjectId();
    }

    /**
     * Checks whether this entity has been deleted.
     *
     * @return boolean true if the entity is marked for deletion, false otherwise
     */
    public boolean pcIsDeleted() {
        return this.pcStateManager != null && this.pcStateManager.isDeleted();
    }

    /**
     * Checks whether this entity has uncommitted changes.
     *
     * Performs a dirty check via the state manager to determine if any fields
     * have been modified since the last database synchronization.
     *
     * @return boolean true if the entity has uncommitted changes, false otherwise
     */
    public boolean pcIsDirty() {
        if (this.pcStateManager == null) {
            return false;
        }
        final StateManager pcStateManager = this.pcStateManager;
        RedefinitionHelper.dirtyCheck(pcStateManager);
        return pcStateManager.isDirty();
    }

    /**
     * Checks whether this entity is newly created and not yet persisted.
     *
     * @return boolean true if the entity is new (not yet in database), false otherwise
     */
    public boolean pcIsNew() {
        return this.pcStateManager != null && this.pcStateManager.isNew();
    }

    /**
     * Checks whether this entity is persistent (managed by JPA).
     *
     * @return boolean true if the entity is persistent, false otherwise
     */
    public boolean pcIsPersistent() {
        return this.pcStateManager != null && this.pcStateManager.isPersistent();
    }

    /**
     * Checks whether this entity is currently part of a transaction.
     *
     * @return boolean true if the entity is transactional, false otherwise
     */
    public boolean pcIsTransactional() {
        return this.pcStateManager != null && this.pcStateManager.isTransactional();
    }

    /**
     * Checks whether this entity is currently being serialized.
     *
     * @return boolean true if the entity is being serialized, false otherwise
     */
    public boolean pcSerializing() {
        return this.pcStateManager != null && this.pcStateManager.serializing();
    }

    /**
     * Marks a specific field as dirty (modified).
     *
     * This notifies the state manager that a field has been changed and needs
     * to be included in the next database update.
     *
     * @param s String the field name to mark as dirty
     */
    public void pcDirty(final String s) {
        if (this.pcStateManager == null) {
            return;
        }
        this.pcStateManager.dirty(s);
    }

    /**
     * Gets the OpenJPA state manager for this entity.
     *
     * @return StateManager the state manager, or null if not managed
     */
    public StateManager pcGetStateManager() {
        return this.pcStateManager;
    }

    /**
     * Gets the version object for optimistic locking.
     *
     * @return Object the version, or null if no state manager is present
     */
    public Object pcGetVersion() {
        if (this.pcStateManager == null) {
            return null;
        }
        return this.pcStateManager.getVersion();
    }

    /**
     * Replaces the current state manager with a new one.
     *
     * If a state manager already exists, it handles the transition via its
     * replaceStateManager method; otherwise, directly assigns the new manager.
     *
     * @param pcStateManager StateManager the new state manager to use
     * @throws SecurityException if the state manager replacement is not permitted
     */
    public void pcReplaceStateManager(final StateManager pcStateManager) throws SecurityException {
        if (this.pcStateManager != null) {
            this.pcStateManager = this.pcStateManager.replaceStateManager(pcStateManager);
            return;
        }
        this.pcStateManager = pcStateManager;
    }

    /**
     * Copies key fields from the entity to an object ID via a field supplier.
     *
     * This operation is not supported for this entity type.
     *
     * @param fieldSupplier FieldSupplier the field supplier for copying values
     * @param o Object the target object ID
     * @throws InternalException always thrown as this operation is not supported
     */
    public void pcCopyKeyFieldsToObjectId(final FieldSupplier fieldSupplier, final Object o) {
        throw new InternalException();
    }

    /**
     * Copies key fields from the entity to an object ID.
     *
     * This operation is not supported for this entity type.
     *
     * @param o Object the target object ID
     * @throws InternalException always thrown as this operation is not supported
     */
    public void pcCopyKeyFieldsToObjectId(final Object o) {
        throw new InternalException();
    }

    /**
     * Copies key fields from an object ID to the entity via a field consumer.
     *
     * Extracts the composite primary key from the provided ObjectId and stores it
     * in the facilityBillingOnItemPk field via the field consumer.
     *
     * @param fieldConsumer FieldConsumer the field consumer for storing values
     * @param o Object the source object ID (must be ObjectId type)
     */
    public void pcCopyKeyFieldsFromObjectId(final FieldConsumer fieldConsumer, final Object o) {
        fieldConsumer.storeObjectField(8 + CachedBillingOnItem.pcInheritedFieldCount, ((ObjectId)o).getId());
    }

    /**
     * Copies key fields from an object ID directly to the entity.
     *
     * Extracts the composite primary key from the provided ObjectId and assigns it
     * directly to the facilityBillingOnItemPk field.
     *
     * @param o Object the source object ID (must be ObjectId type)
     */
    public void pcCopyKeyFieldsFromObjectId(final Object o) {
        this.facilityBillingOnItemPk = (FacilityIdIntegerCompositePk)((ObjectId)o).getId();
    }

    /**
     * Creates a new object ID instance from a string representation.
     *
     * This operation is not supported for ObjectId-based identifiers.
     *
     * @param o Object the string representation of the object ID
     * @return Object the new object ID instance
     * @throws IllegalArgumentException always thrown as string-based ID construction is not supported
     */
    public Object pcNewObjectIdInstance(final Object o) {
        throw new IllegalArgumentException("The id type \"class org.apache.openjpa.util.ObjectId\" specified by persistent type \"class ca.openosp.openo.caisi_integrator.dao.CachedBillingOnItem\" does not have a public class org.apache.openjpa.util.ObjectId(String) or class org.apache.openjpa.util.ObjectId(Class, String) constructor.");
    }

    /**
     * Creates a new object ID instance from the current entity's key fields.
     *
     * Creates an OpenJPA ObjectId wrapping this entity's composite primary key.
     *
     * @return Object the newly created ObjectId containing the facilityBillingOnItemPk
     */
    public Object pcNewObjectIdInstance() {
        return new ObjectId((CachedBillingOnItem.class$Lca$openosp$openo$caisi_integrator$dao$CachedBillingOnItem != null) ? CachedBillingOnItem.class$Lca$openosp$openo$caisi_integrator$dao$CachedBillingOnItem : (CachedBillingOnItem.class$Lca$openosp$openo$caisi_integrator$dao$CachedBillingOnItem = class$("ca.openosp.openo.caisi_integrator.dao.CachedBillingOnItem")), (Object)this.facilityBillingOnItemPk);
    }

    /**
     * OpenJPA-enhanced field accessor for appointmentId.
     *
     * Notifies the state manager of field access for change tracking before returning the value.
     *
     * @param cachedBillingOnItem CachedBillingOnItem the instance to access
     * @return Integer the appointment ID value
     */
    private static final Integer pcGetappointmentId(final CachedBillingOnItem cachedBillingOnItem) {
        if (cachedBillingOnItem.pcStateManager == null) {
            return cachedBillingOnItem.appointmentId;
        }
        cachedBillingOnItem.pcStateManager.accessingField(CachedBillingOnItem.pcInheritedFieldCount + 0);
        return cachedBillingOnItem.appointmentId;
    }

    /**
     * OpenJPA-enhanced field mutator for appointmentId.
     *
     * Notifies the state manager of field modification for change tracking and dirty detection.
     *
     * @param cachedBillingOnItem CachedBillingOnItem the instance to modify
     * @param appointmentId Integer the new appointment ID value
     */
    private static final void pcSetappointmentId(final CachedBillingOnItem cachedBillingOnItem, final Integer appointmentId) {
        if (cachedBillingOnItem.pcStateManager == null) {
            cachedBillingOnItem.appointmentId = appointmentId;
            return;
        }
        cachedBillingOnItem.pcStateManager.settingObjectField((PersistenceCapable)cachedBillingOnItem, CachedBillingOnItem.pcInheritedFieldCount + 0, (Object)cachedBillingOnItem.appointmentId, (Object)appointmentId, 0);
    }

    /*
     * The following pcGet* and pcSet* methods are OpenJPA-enhanced field accessors and mutators.
     * Each getter notifies the state manager of field access for change tracking.
     * Each setter notifies the state manager of field modification for dirty detection.
     * These methods are auto-generated by OpenJPA bytecode enhancement and follow the same pattern
     * for each managed field in this entity.
     */

    private static final String pcGetapptProviderId(final CachedBillingOnItem cachedBillingOnItem) {
        if (cachedBillingOnItem.pcStateManager == null) {
            return cachedBillingOnItem.apptProviderId;
        }
        cachedBillingOnItem.pcStateManager.accessingField(CachedBillingOnItem.pcInheritedFieldCount + 1);
        return cachedBillingOnItem.apptProviderId;
    }
    
    private static final void pcSetapptProviderId(final CachedBillingOnItem cachedBillingOnItem, final String apptProviderId) {
        if (cachedBillingOnItem.pcStateManager == null) {
            cachedBillingOnItem.apptProviderId = apptProviderId;
            return;
        }
        cachedBillingOnItem.pcStateManager.settingStringField((PersistenceCapable)cachedBillingOnItem, CachedBillingOnItem.pcInheritedFieldCount + 1, cachedBillingOnItem.apptProviderId, apptProviderId, 0);
    }
    
    private static final String pcGetasstProviderId(final CachedBillingOnItem cachedBillingOnItem) {
        if (cachedBillingOnItem.pcStateManager == null) {
            return cachedBillingOnItem.asstProviderId;
        }
        cachedBillingOnItem.pcStateManager.accessingField(CachedBillingOnItem.pcInheritedFieldCount + 2);
        return cachedBillingOnItem.asstProviderId;
    }
    
    private static final void pcSetasstProviderId(final CachedBillingOnItem cachedBillingOnItem, final String asstProviderId) {
        if (cachedBillingOnItem.pcStateManager == null) {
            cachedBillingOnItem.asstProviderId = asstProviderId;
            return;
        }
        cachedBillingOnItem.pcStateManager.settingStringField((PersistenceCapable)cachedBillingOnItem, CachedBillingOnItem.pcInheritedFieldCount + 2, cachedBillingOnItem.asstProviderId, asstProviderId, 0);
    }
    
    private static final Integer pcGetcaisiDemographicId(final CachedBillingOnItem cachedBillingOnItem) {
        if (cachedBillingOnItem.pcStateManager == null) {
            return cachedBillingOnItem.caisiDemographicId;
        }
        cachedBillingOnItem.pcStateManager.accessingField(CachedBillingOnItem.pcInheritedFieldCount + 3);
        return cachedBillingOnItem.caisiDemographicId;
    }
    
    private static final void pcSetcaisiDemographicId(final CachedBillingOnItem cachedBillingOnItem, final Integer caisiDemographicId) {
        if (cachedBillingOnItem.pcStateManager == null) {
            cachedBillingOnItem.caisiDemographicId = caisiDemographicId;
            return;
        }
        cachedBillingOnItem.pcStateManager.settingObjectField((PersistenceCapable)cachedBillingOnItem, CachedBillingOnItem.pcInheritedFieldCount + 3, (Object)cachedBillingOnItem.caisiDemographicId, (Object)caisiDemographicId, 0);
    }
    
    private static final String pcGetcaisiProviderId(final CachedBillingOnItem cachedBillingOnItem) {
        if (cachedBillingOnItem.pcStateManager == null) {
            return cachedBillingOnItem.caisiProviderId;
        }
        cachedBillingOnItem.pcStateManager.accessingField(CachedBillingOnItem.pcInheritedFieldCount + 4);
        return cachedBillingOnItem.caisiProviderId;
    }
    
    private static final void pcSetcaisiProviderId(final CachedBillingOnItem cachedBillingOnItem, final String caisiProviderId) {
        if (cachedBillingOnItem.pcStateManager == null) {
            cachedBillingOnItem.caisiProviderId = caisiProviderId;
            return;
        }
        cachedBillingOnItem.pcStateManager.settingStringField((PersistenceCapable)cachedBillingOnItem, CachedBillingOnItem.pcInheritedFieldCount + 4, cachedBillingOnItem.caisiProviderId, caisiProviderId, 0);
    }
    
    private static final String pcGetdx(final CachedBillingOnItem cachedBillingOnItem) {
        if (cachedBillingOnItem.pcStateManager == null) {
            return cachedBillingOnItem.dx;
        }
        cachedBillingOnItem.pcStateManager.accessingField(CachedBillingOnItem.pcInheritedFieldCount + 5);
        return cachedBillingOnItem.dx;
    }
    
    private static final void pcSetdx(final CachedBillingOnItem cachedBillingOnItem, final String dx) {
        if (cachedBillingOnItem.pcStateManager == null) {
            cachedBillingOnItem.dx = dx;
            return;
        }
        cachedBillingOnItem.pcStateManager.settingStringField((PersistenceCapable)cachedBillingOnItem, CachedBillingOnItem.pcInheritedFieldCount + 5, cachedBillingOnItem.dx, dx, 0);
    }
    
    private static final String pcGetdx1(final CachedBillingOnItem cachedBillingOnItem) {
        if (cachedBillingOnItem.pcStateManager == null) {
            return cachedBillingOnItem.dx1;
        }
        cachedBillingOnItem.pcStateManager.accessingField(CachedBillingOnItem.pcInheritedFieldCount + 6);
        return cachedBillingOnItem.dx1;
    }
    
    private static final void pcSetdx1(final CachedBillingOnItem cachedBillingOnItem, final String dx1) {
        if (cachedBillingOnItem.pcStateManager == null) {
            cachedBillingOnItem.dx1 = dx1;
            return;
        }
        cachedBillingOnItem.pcStateManager.settingStringField((PersistenceCapable)cachedBillingOnItem, CachedBillingOnItem.pcInheritedFieldCount + 6, cachedBillingOnItem.dx1, dx1, 0);
    }
    
    private static final String pcGetdx2(final CachedBillingOnItem cachedBillingOnItem) {
        if (cachedBillingOnItem.pcStateManager == null) {
            return cachedBillingOnItem.dx2;
        }
        cachedBillingOnItem.pcStateManager.accessingField(CachedBillingOnItem.pcInheritedFieldCount + 7);
        return cachedBillingOnItem.dx2;
    }
    
    private static final void pcSetdx2(final CachedBillingOnItem cachedBillingOnItem, final String dx2) {
        if (cachedBillingOnItem.pcStateManager == null) {
            cachedBillingOnItem.dx2 = dx2;
            return;
        }
        cachedBillingOnItem.pcStateManager.settingStringField((PersistenceCapable)cachedBillingOnItem, CachedBillingOnItem.pcInheritedFieldCount + 7, cachedBillingOnItem.dx2, dx2, 0);
    }
    
    private static final FacilityIdIntegerCompositePk pcGetfacilityBillingOnItemPk(final CachedBillingOnItem cachedBillingOnItem) {
        if (cachedBillingOnItem.pcStateManager == null) {
            return cachedBillingOnItem.facilityBillingOnItemPk;
        }
        cachedBillingOnItem.pcStateManager.accessingField(CachedBillingOnItem.pcInheritedFieldCount + 8);
        return cachedBillingOnItem.facilityBillingOnItemPk;
    }
    
    private static final void pcSetfacilityBillingOnItemPk(final CachedBillingOnItem cachedBillingOnItem, final FacilityIdIntegerCompositePk facilityBillingOnItemPk) {
        if (cachedBillingOnItem.pcStateManager == null) {
            cachedBillingOnItem.facilityBillingOnItemPk = facilityBillingOnItemPk;
            return;
        }
        cachedBillingOnItem.pcStateManager.settingObjectField((PersistenceCapable)cachedBillingOnItem, CachedBillingOnItem.pcInheritedFieldCount + 8, (Object)cachedBillingOnItem.facilityBillingOnItemPk, (Object)facilityBillingOnItemPk, 0);
    }
    
    private static final String pcGetserviceCode(final CachedBillingOnItem cachedBillingOnItem) {
        if (cachedBillingOnItem.pcStateManager == null) {
            return cachedBillingOnItem.serviceCode;
        }
        cachedBillingOnItem.pcStateManager.accessingField(CachedBillingOnItem.pcInheritedFieldCount + 9);
        return cachedBillingOnItem.serviceCode;
    }
    
    private static final void pcSetserviceCode(final CachedBillingOnItem cachedBillingOnItem, final String serviceCode) {
        if (cachedBillingOnItem.pcStateManager == null) {
            cachedBillingOnItem.serviceCode = serviceCode;
            return;
        }
        cachedBillingOnItem.pcStateManager.settingStringField((PersistenceCapable)cachedBillingOnItem, CachedBillingOnItem.pcInheritedFieldCount + 9, cachedBillingOnItem.serviceCode, serviceCode, 0);
    }
    
    private static final Date pcGetserviceDate(final CachedBillingOnItem cachedBillingOnItem) {
        if (cachedBillingOnItem.pcStateManager == null) {
            return cachedBillingOnItem.serviceDate;
        }
        cachedBillingOnItem.pcStateManager.accessingField(CachedBillingOnItem.pcInheritedFieldCount + 10);
        return cachedBillingOnItem.serviceDate;
    }
    
    private static final void pcSetserviceDate(final CachedBillingOnItem cachedBillingOnItem, final Date serviceDate) {
        if (cachedBillingOnItem.pcStateManager == null) {
            cachedBillingOnItem.serviceDate = serviceDate;
            return;
        }
        cachedBillingOnItem.pcStateManager.settingObjectField((PersistenceCapable)cachedBillingOnItem, CachedBillingOnItem.pcInheritedFieldCount + 10, (Object)cachedBillingOnItem.serviceDate, (Object)serviceDate, 0);
    }
    
    private static final String pcGetstatus(final CachedBillingOnItem cachedBillingOnItem) {
        if (cachedBillingOnItem.pcStateManager == null) {
            return cachedBillingOnItem.status;
        }
        cachedBillingOnItem.pcStateManager.accessingField(CachedBillingOnItem.pcInheritedFieldCount + 11);
        return cachedBillingOnItem.status;
    }
    
    private static final void pcSetstatus(final CachedBillingOnItem cachedBillingOnItem, final String status) {
        if (cachedBillingOnItem.pcStateManager == null) {
            cachedBillingOnItem.status = status;
            return;
        }
        cachedBillingOnItem.pcStateManager.settingStringField((PersistenceCapable)cachedBillingOnItem, CachedBillingOnItem.pcInheritedFieldCount + 11, cachedBillingOnItem.status, status, 0);
    }

    /**
     * Checks whether this entity is in a detached state.
     *
     * An entity is detached when it was previously managed by a persistence context
     * but is no longer associated with an active EntityManager.
     *
     * @return Boolean TRUE if detached, FALSE if attached, null if state is indeterminate
     */
    public Boolean pcIsDetached() {
        if (this.pcStateManager != null) {
            if (this.pcStateManager.isDetached()) {
                return Boolean.TRUE;
            }
            return Boolean.FALSE;
        }
        else {
            if (this.pcGetDetachedState() != null && this.pcGetDetachedState() != PersistenceCapable.DESERIALIZED) {
                return Boolean.TRUE;
            }
            if (!this.pcisDetachedStateDefinitive()) {
                return null;
            }
            if (this.pcGetDetachedState() == null) {
                return Boolean.FALSE;
            }
            return null;
        }
    }

    /**
     * Checks whether the detached state is definitive.
     *
     * @return boolean false, indicating detached state cannot be definitively determined from field inspection alone
     */
    private boolean pcisDetachedStateDefinitive() {
        return false;
    }

    /**
     * Gets the detached state object for this entity.
     *
     * The detached state contains metadata about the entity's persistence state
     * when it was detached from its EntityManager.
     *
     * @return Object the detached state, or null if not detached
     */
    public Object pcGetDetachedState() {
        return this.pcDetachedState;
    }

    /**
     * Sets the detached state object for this entity.
     *
     * @param pcDetachedState Object the detached state to set
     */
    public void pcSetDetachedState(final Object pcDetachedState) {
        this.pcDetachedState = pcDetachedState;
    }

    /**
     * Custom serialization method for this entity.
     *
     * Handles JPA detached state during serialization by clearing it after
     * the default serialization process completes.
     *
     * @param objectOutputStream ObjectOutputStream the stream to write to
     * @throws IOException if an I/O error occurs during serialization
     */
    private void writeObject(final ObjectOutputStream objectOutputStream) throws IOException {
        final boolean pcSerializing = this.pcSerializing();
        objectOutputStream.defaultWriteObject();
        if (pcSerializing) {
            this.pcSetDetachedState(null);
        }
    }

    /**
     * Custom deserialization method for this entity.
     *
     * Marks the entity as deserialized by setting the detached state marker
     * before performing default deserialization.
     *
     * @param objectInputStream ObjectInputStream the stream to read from
     * @throws IOException if an I/O error occurs during deserialization
     * @throws ClassNotFoundException if a required class cannot be found
     */
    private void readObject(final ObjectInputStream objectInputStream) throws IOException, ClassNotFoundException {
        this.pcSetDetachedState(PersistenceCapable.DESERIALIZED);
        objectInputStream.defaultReadObject();
    }
}
