package ca.openosp.openo.caisi_integrator.dao;

import java.io.ObjectInputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import org.apache.openjpa.util.ObjectId;
import org.apache.openjpa.enhance.FieldConsumer;
import org.apache.openjpa.util.InternalException;
import org.apache.openjpa.enhance.FieldSupplier;
import org.apache.openjpa.enhance.RedefinitionHelper;
import org.apache.openjpa.enhance.PersistenceCapable;
import org.apache.openjpa.enhance.PCRegistry;
import org.apache.commons.lang3.StringUtils;
import org.apache.openjpa.enhance.StateManager;
import org.apache.openjpa.persistence.jdbc.Index;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;

/**
 * JPA entity representing a cached mapping between facility-specific measurement identifiers and standardized
 * healthcare measurement codes within the CAISI (Client Access to Integrated Services and Information) Integrator system.
 *
 * <p>This entity facilitates interoperability between different healthcare facilities by maintaining a persistent
 * mapping of laboratory measurement identifiers. Each mapping associates a facility's internal measurement identifier
 * with standard LOINC (Logical Observation Identifiers Names and Codes) codes, enabling consistent interpretation
 * of laboratory results across different EMR systems and healthcare facilities.</p>
 *
 * <p>The class is enhanced by Apache OpenJPA for JPA persistence, implementing the {@link PersistenceCapable} interface
 * to enable transparent persistence and state management. All persistence-related methods (prefixed with "pc") are
 * generated by OpenJPA bytecode enhancement and should not be called directly by application code.</p>
 *
 * <p><strong>Healthcare Context:</strong> Laboratory measurements are fundamental to patient care, and different
 * facilities often use different coding systems and identifiers. This mapping table enables the CAISI Integrator
 * to translate between facility-specific codes and standardized LOINC codes, ensuring that laboratory results
 * can be correctly interpreted regardless of their source facility.</p>
 *
 * <p><strong>Key Features:</strong></p>
 * <ul>
 *   <li>Composite primary key based on facility ID and CAISI item ID</li>
 *   <li>Support for LOINC codes (standard healthcare measurement codes)</li>
 *   <li>Facility-specific identification codes</li>
 *   <li>Human-readable measurement names</li>
 *   <li>Laboratory type categorization</li>
 *   <li>OpenJPA bytecode enhancement for transparent persistence</li>
 * </ul>
 *
 * @see FacilityIdIntegerCompositePk
 * @see AbstractModel
 * @see PersistenceCapable
 * @since 2026-01-24
 */
@Entity
public class CachedMeasurementMap extends AbstractModel<FacilityIdIntegerCompositePk> implements Comparable<CachedMeasurementMap>, PersistenceCapable
{
    @EmbeddedId
    private FacilityIdIntegerCompositePk facilityMeasurementMapPk;
    @Column(length = 20)
    @Index
    private String loincCode;
    @Column(nullable = false, length = 20)
    @Index
    private String identCode;
    @Column(nullable = false, length = 255)
    private String name;
    @Column(nullable = false, length = 10)
    private String labType;
    private static int pcInheritedFieldCount;
    private static String[] pcFieldNames;
    private static Class[] pcFieldTypes;
    private static byte[] pcFieldFlags;
    private static Class pcPCSuperclass;
    protected transient StateManager pcStateManager;
    static /* synthetic */ Class class$Lca$openosp$openo$caisi_integrator$dao$FacilityIdIntegerCompositePk;
    static /* synthetic */ Class class$Ljava$lang$String;
    static /* synthetic */ Class class$Lca$openosp$openo$caisi_integrator$dao$CachedMeasurementMap;
    private transient Object pcDetachedState;
    private static final long serialVersionUID;
    
    /**
     * Default constructor that initializes a new CachedMeasurementMap instance with all fields set to null.
     *
     * <p>This constructor is required by JPA for entity instantiation and should be used when creating
     * new measurement mappings that will have their values set via setter methods.</p>
     */
    public CachedMeasurementMap() {
        this.loincCode = null;
        this.identCode = null;
        this.name = null;
        this.labType = null;
    }
    
    /**
     * Retrieves the composite primary key for this measurement mapping.
     *
     * <p>The composite key uniquely identifies this measurement mapping by combining the integrator facility ID
     * and the CAISI item ID. This key enables the system to distinguish between the same measurement type
     * across different healthcare facilities.</p>
     *
     * @return FacilityIdIntegerCompositePk the composite primary key containing facility and item identifiers,
     *         or null if not yet set
     */
    public FacilityIdIntegerCompositePk getFacilityIdIntegerCompositePk() {
        return pcGetfacilityMeasurementMapPk(this);
    }

    /**
     * Sets the composite primary key for this measurement mapping.
     *
     * <p>This method should be called when creating a new measurement mapping to establish its unique identity
     * within the system. The key must contain valid facility and item identifiers.</p>
     *
     * @param facilityMeasurementMapPk FacilityIdIntegerCompositePk the composite primary key to set,
     *                                  must not be null for persistent entities
     */
    public void setFacilityIdIntegerCompositePk(final FacilityIdIntegerCompositePk facilityMeasurementMapPk) {
        pcSetfacilityMeasurementMapPk(this, facilityMeasurementMapPk);
    }
    
    /**
     * Retrieves the LOINC (Logical Observation Identifiers Names and Codes) code for this measurement.
     *
     * <p>LOINC is a universal standard for identifying laboratory and clinical observations. This code enables
     * interoperability between different healthcare systems by providing a standardized identifier for the
     * measurement type regardless of the source facility.</p>
     *
     * @return String the LOINC code (maximum 20 characters), or null if not assigned
     */
    public String getLoincCode() {
        return pcGetloincCode(this);
    }

    /**
     * Sets the LOINC code for this measurement mapping.
     *
     * <p>The LOINC code should be a valid code from the LOINC coding system. The value will be automatically
     * trimmed of leading and trailing whitespace. If null is provided, an empty string will be stored.</p>
     *
     * @param loincCode String the LOINC code to assign (maximum 20 characters), will be trimmed
     */
    public void setLoincCode(final String loincCode) {
        pcSetloincCode(this, StringUtils.trimToEmpty(loincCode));
    }
    
    /**
     * Retrieves the facility-specific identification code for this measurement.
     *
     * <p>Each healthcare facility may use its own internal coding system for laboratory measurements.
     * This field stores the facility's local identifier, which can be mapped to the standardized LOINC code
     * to enable interoperability.</p>
     *
     * @return String the facility-specific identification code (maximum 20 characters), never null
     */
    public String getIdentCode() {
        return pcGetidentCode(this);
    }

    /**
     * Sets the facility-specific identification code for this measurement mapping.
     *
     * <p>This should be the code used by the source facility to identify this measurement type in their
     * local system. The value will be automatically trimmed of leading and trailing whitespace. If null
     * is provided, an empty string will be stored.</p>
     *
     * @param identCode String the facility-specific identification code (maximum 20 characters, required),
     *                   will be trimmed
     */
    public void setIdentCode(final String identCode) {
        pcSetidentCode(this, StringUtils.trimToEmpty(identCode));
    }
    
    /**
     * Retrieves the human-readable name for this measurement.
     *
     * <p>This name provides a descriptive label for the measurement that can be displayed to end users,
     * such as "Blood Glucose", "Hemoglobin A1c", or "Systolic Blood Pressure". It complements the
     * technical codes (LOINC and facility identifier) with a user-friendly description.</p>
     *
     * @return String the measurement name (maximum 255 characters), never null
     */
    public String getName() {
        return pcGetname(this);
    }

    /**
     * Sets the human-readable name for this measurement mapping.
     *
     * <p>The name should be clear and descriptive to help users understand what measurement this mapping
     * represents. The value will be automatically trimmed of leading and trailing whitespace. If null
     * is provided, an empty string will be stored.</p>
     *
     * @param name String the measurement name (maximum 255 characters, required), will be trimmed
     */
    public void setName(final String name) {
        pcSetname(this, StringUtils.trimToEmpty(name));
    }
    
    /**
     * Retrieves the laboratory type categorization for this measurement.
     *
     * <p>This field categorizes the measurement by laboratory department or type, such as "CHEM" (Chemistry),
     * "HEMA" (Hematology), "MICRO" (Microbiology), etc. This categorization helps organize and filter
     * measurements by their clinical specialty area.</p>
     *
     * @return String the laboratory type code (maximum 10 characters), never null
     */
    public String getLabType() {
        return pcGetlabType(this);
    }

    /**
     * Sets the laboratory type categorization for this measurement mapping.
     *
     * <p>The lab type should indicate the clinical specialty or department that typically performs this
     * measurement. The value will be automatically trimmed of leading and trailing whitespace. If null
     * is provided, an empty string will be stored.</p>
     *
     * @param labType String the laboratory type code (maximum 10 characters, required), will be trimmed
     */
    public void setLabType(final String labType) {
        pcSetlabType(this, StringUtils.trimToEmpty(labType));
    }
    
    /**
     * Compares this measurement mapping to another for ordering purposes.
     *
     * <p>The comparison is based on the CAISI item ID component of the composite primary key. This enables
     * measurement mappings to be sorted in a consistent order based on their item identifiers.</p>
     *
     * @param o CachedMeasurementMap the measurement mapping to compare against, must not be null
     * @return int a negative integer, zero, or a positive integer as this mapping's CAISI item ID
     *         is less than, equal to, or greater than the specified mapping's CAISI item ID
     */
    @Override
    public int compareTo(final CachedMeasurementMap o) {
        return pcGetfacilityMeasurementMapPk(this).getCaisiItemId() - pcGetfacilityMeasurementMapPk(o).getCaisiItemId();
    }
    
    /**
     * Retrieves the entity's primary key identifier.
     *
     * <p>This method overrides the abstract getId() method from AbstractModel to provide access to the
     * composite primary key. It returns the same value as getFacilityIdIntegerCompositePk().</p>
     *
     * @return FacilityIdIntegerCompositePk the composite primary key for this entity, or null if not set
     */
    @Override
    public FacilityIdIntegerCompositePk getId() {
        return pcGetfacilityMeasurementMapPk(this);
    }
    
    /**
     * Returns the OpenJPA bytecode enhancement contract version.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and is automatically generated
     * by OpenJPA bytecode enhancement. It should not be called directly by application code.</p>
     *
     * @return int the enhancement contract version (always 2 for this implementation)
     */
    public int pcGetEnhancementContractVersion() {
        return 2;
    }
    
    static {
        serialVersionUID = 2160040152489451055L;
        CachedMeasurementMap.pcFieldNames = new String[] { "facilityMeasurementMapPk", "identCode", "labType", "loincCode", "name" };
        CachedMeasurementMap.pcFieldTypes = new Class[] { (CachedMeasurementMap.class$Lca$openosp$openo$caisi_integrator$dao$FacilityIdIntegerCompositePk != null) ? CachedMeasurementMap.class$Lca$openosp$openo$caisi_integrator$dao$FacilityIdIntegerCompositePk : (CachedMeasurementMap.class$Lca$openosp$openo$caisi_integrator$dao$FacilityIdIntegerCompositePk = class$("ca.openosp.openo.caisi_integrator.dao.FacilityIdIntegerCompositePk")), (CachedMeasurementMap.class$Ljava$lang$String != null) ? CachedMeasurementMap.class$Ljava$lang$String : (CachedMeasurementMap.class$Ljava$lang$String = class$("java.lang.String")), (CachedMeasurementMap.class$Ljava$lang$String != null) ? CachedMeasurementMap.class$Ljava$lang$String : (CachedMeasurementMap.class$Ljava$lang$String = class$("java.lang.String")), (CachedMeasurementMap.class$Ljava$lang$String != null) ? CachedMeasurementMap.class$Ljava$lang$String : (CachedMeasurementMap.class$Ljava$lang$String = class$("java.lang.String")), (CachedMeasurementMap.class$Ljava$lang$String != null) ? CachedMeasurementMap.class$Ljava$lang$String : (CachedMeasurementMap.class$Ljava$lang$String = class$("java.lang.String")) };
        CachedMeasurementMap.pcFieldFlags = new byte[] { 26, 26, 26, 26, 26 };
        PCRegistry.register((CachedMeasurementMap.class$Lca$openosp$openo$caisi_integrator$dao$CachedMeasurementMap != null) ? CachedMeasurementMap.class$Lca$openosp$openo$caisi_integrator$dao$CachedMeasurementMap : (CachedMeasurementMap.class$Lca$openosp$openo$caisi_integrator$dao$CachedMeasurementMap = class$("ca.openosp.openo.caisi_integrator.dao.CachedMeasurementMap")), CachedMeasurementMap.pcFieldNames, CachedMeasurementMap.pcFieldTypes, CachedMeasurementMap.pcFieldFlags, CachedMeasurementMap.pcPCSuperclass, "CachedMeasurementMap", (PersistenceCapable)new CachedMeasurementMap());
    }
    
    static /* synthetic */ Class class$(final String className) {
        try {
            return Class.forName(className);
        }
        catch (final ClassNotFoundException ex) {
            throw new NoClassDefFoundError(ex.getMessage());
        }
    }
    
    protected void pcClearFields() {
        this.facilityMeasurementMapPk = null;
        this.identCode = null;
        this.labType = null;
        this.loincCode = null;
        this.name = null;
    }
    
    /**
     * Creates a new instance of this entity with a specific state manager and object ID.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and is used by the JPA provider
     * to create managed instances. It should not be called directly by application code.</p>
     *
     * @param pcStateManager StateManager the OpenJPA state manager to manage this instance
     * @param o Object the object ID containing key field values to copy
     * @param b boolean if true, all fields will be cleared before setting the state manager
     * @return PersistenceCapable a new managed instance with the specified state manager and key fields
     */
    public PersistenceCapable pcNewInstance(final StateManager pcStateManager, final Object o, final boolean b) {
        final CachedMeasurementMap cachedMeasurementMap = new CachedMeasurementMap();
        if (b) {
            cachedMeasurementMap.pcClearFields();
        }
        cachedMeasurementMap.pcStateManager = pcStateManager;
        cachedMeasurementMap.pcCopyKeyFieldsFromObjectId(o);
        return (PersistenceCapable)cachedMeasurementMap;
    }

    /**
     * Creates a new instance of this entity with a specific state manager.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and is used by the JPA provider
     * to create managed instances. It should not be called directly by application code.</p>
     *
     * @param pcStateManager StateManager the OpenJPA state manager to manage this instance
     * @param b boolean if true, all fields will be cleared before setting the state manager
     * @return PersistenceCapable a new managed instance with the specified state manager
     */
    public PersistenceCapable pcNewInstance(final StateManager pcStateManager, final boolean b) {
        final CachedMeasurementMap cachedMeasurementMap = new CachedMeasurementMap();
        if (b) {
            cachedMeasurementMap.pcClearFields();
        }
        cachedMeasurementMap.pcStateManager = pcStateManager;
        return (PersistenceCapable)cachedMeasurementMap;
    }
    
    protected static int pcGetManagedFieldCount() {
        return 5;
    }
    
    /**
     * Replaces a single field value from the state manager.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and is used by the JPA provider
     * to manage field state. It should not be called directly by application code.</p>
     *
     * @param n int the absolute field index to replace
     * @throws IllegalArgumentException if the field index is invalid
     */
    public void pcReplaceField(final int n) {
        final int n2 = n - CachedMeasurementMap.pcInheritedFieldCount;
        if (n2 < 0) {
            throw new IllegalArgumentException();
        }
        switch (n2) {
            case 0: {
                this.facilityMeasurementMapPk = (FacilityIdIntegerCompositePk)this.pcStateManager.replaceObjectField((PersistenceCapable)this, n);
                return;
            }
            case 1: {
                this.identCode = this.pcStateManager.replaceStringField((PersistenceCapable)this, n);
                return;
            }
            case 2: {
                this.labType = this.pcStateManager.replaceStringField((PersistenceCapable)this, n);
                return;
            }
            case 3: {
                this.loincCode = this.pcStateManager.replaceStringField((PersistenceCapable)this, n);
                return;
            }
            case 4: {
                this.name = this.pcStateManager.replaceStringField((PersistenceCapable)this, n);
                return;
            }
            default: {
                throw new IllegalArgumentException();
            }
        }
    }

    /**
     * Replaces multiple field values from the state manager.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and is used by the JPA provider
     * to manage field state. It should not be called directly by application code.</p>
     *
     * @param array int[] array of absolute field indices to replace
     */
    public void pcReplaceFields(final int[] array) {
        for (int i = 0; i < array.length; ++i) {
            this.pcReplaceField(array[i]);
        }
    }
    
    /**
     * Provides a single field value to the state manager.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and is used by the JPA provider
     * to retrieve field values for persistence operations. It should not be called directly by application code.</p>
     *
     * @param n int the absolute field index to provide
     * @throws IllegalArgumentException if the field index is invalid
     */
    public void pcProvideField(final int n) {
        final int n2 = n - CachedMeasurementMap.pcInheritedFieldCount;
        if (n2 < 0) {
            throw new IllegalArgumentException();
        }
        switch (n2) {
            case 0: {
                this.pcStateManager.providedObjectField((PersistenceCapable)this, n, (Object)this.facilityMeasurementMapPk);
                return;
            }
            case 1: {
                this.pcStateManager.providedStringField((PersistenceCapable)this, n, this.identCode);
                return;
            }
            case 2: {
                this.pcStateManager.providedStringField((PersistenceCapable)this, n, this.labType);
                return;
            }
            case 3: {
                this.pcStateManager.providedStringField((PersistenceCapable)this, n, this.loincCode);
                return;
            }
            case 4: {
                this.pcStateManager.providedStringField((PersistenceCapable)this, n, this.name);
                return;
            }
            default: {
                throw new IllegalArgumentException();
            }
        }
    }

    /**
     * Provides multiple field values to the state manager.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and is used by the JPA provider
     * to retrieve field values for persistence operations. It should not be called directly by application code.</p>
     *
     * @param array int[] array of absolute field indices to provide
     */
    public void pcProvideFields(final int[] array) {
        for (int i = 0; i < array.length; ++i) {
            this.pcProvideField(array[i]);
        }
    }
    
    protected void pcCopyField(final CachedMeasurementMap cachedMeasurementMap, final int n) {
        final int n2 = n - CachedMeasurementMap.pcInheritedFieldCount;
        if (n2 < 0) {
            throw new IllegalArgumentException();
        }
        switch (n2) {
            case 0: {
                this.facilityMeasurementMapPk = cachedMeasurementMap.facilityMeasurementMapPk;
                return;
            }
            case 1: {
                this.identCode = cachedMeasurementMap.identCode;
                return;
            }
            case 2: {
                this.labType = cachedMeasurementMap.labType;
                return;
            }
            case 3: {
                this.loincCode = cachedMeasurementMap.loincCode;
                return;
            }
            case 4: {
                this.name = cachedMeasurementMap.name;
                return;
            }
            default: {
                throw new IllegalArgumentException();
            }
        }
    }
    
    /**
     * Copies multiple field values from another instance with the same state manager.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and is used by the JPA provider
     * for state management operations. Both instances must be managed by the same state manager.</p>
     *
     * @param o Object the source CachedMeasurementMap instance to copy fields from
     * @param array int[] array of absolute field indices to copy
     * @throws IllegalArgumentException if the source has a different state manager
     * @throws IllegalStateException if this instance has no state manager
     */
    public void pcCopyFields(final Object o, final int[] array) {
        final CachedMeasurementMap cachedMeasurementMap = (CachedMeasurementMap)o;
        if (cachedMeasurementMap.pcStateManager != this.pcStateManager) {
            throw new IllegalArgumentException();
        }
        if (this.pcStateManager == null) {
            throw new IllegalStateException();
        }
        for (int i = 0; i < array.length; ++i) {
            this.pcCopyField(cachedMeasurementMap, array[i]);
        }
    }
    
    /**
     * Retrieves the generic context from the state manager.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface. The generic context provides
     * additional state information for the persistence provider.</p>
     *
     * @return Object the generic context, or null if there is no state manager
     */
    public Object pcGetGenericContext() {
        if (this.pcStateManager == null) {
            return null;
        }
        return this.pcStateManager.getGenericContext();
    }

    /**
     * Retrieves the object ID for this entity from the state manager.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and provides access to the
     * persistence provider's internal object identifier.</p>
     *
     * @return Object the object ID, or null if there is no state manager
     */
    public Object pcFetchObjectId() {
        if (this.pcStateManager == null) {
            return null;
        }
        return this.pcStateManager.fetchObjectId();
    }

    /**
     * Checks if this entity has been deleted from the persistence context.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and indicates whether
     * this entity is marked for deletion.</p>
     *
     * @return boolean true if the entity is deleted, false otherwise
     */
    public boolean pcIsDeleted() {
        return this.pcStateManager != null && this.pcStateManager.isDeleted();
    }

    /**
     * Checks if this entity has been modified since it was loaded or last persisted.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and is used by the JPA provider
     * to determine if the entity needs to be updated in the database.</p>
     *
     * @return boolean true if the entity has been modified, false otherwise
     */
    public boolean pcIsDirty() {
        if (this.pcStateManager == null) {
            return false;
        }
        final StateManager pcStateManager = this.pcStateManager;
        RedefinitionHelper.dirtyCheck(pcStateManager);
        return pcStateManager.isDirty();
    }

    /**
     * Checks if this entity is newly created and not yet persisted to the database.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and indicates whether
     * this entity has been created but not yet inserted into the database.</p>
     *
     * @return boolean true if the entity is new, false otherwise
     */
    public boolean pcIsNew() {
        return this.pcStateManager != null && this.pcStateManager.isNew();
    }

    /**
     * Checks if this entity is persistent (managed by the persistence context).
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and indicates whether
     * this entity is being managed by the JPA persistence provider.</p>
     *
     * @return boolean true if the entity is persistent, false otherwise
     */
    public boolean pcIsPersistent() {
        return this.pcStateManager != null && this.pcStateManager.isPersistent();
    }

    /**
     * Checks if this entity is enrolled in a transaction.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and indicates whether
     * this entity is participating in an active transaction.</p>
     *
     * @return boolean true if the entity is transactional, false otherwise
     */
    public boolean pcIsTransactional() {
        return this.pcStateManager != null && this.pcStateManager.isTransactional();
    }

    /**
     * Checks if this entity is currently being serialized.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and is used during
     * serialization to handle detached state properly.</p>
     *
     * @return boolean true if the entity is being serialized, false otherwise
     */
    public boolean pcSerializing() {
        return this.pcStateManager != null && this.pcStateManager.serializing();
    }
    
    /**
     * Marks a specific field as dirty (modified) in the state manager.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and notifies the JPA provider
     * that a field has been modified and should be persisted.</p>
     *
     * @param s String the name of the field that was modified
     */
    public void pcDirty(final String s) {
        if (this.pcStateManager == null) {
            return;
        }
        this.pcStateManager.dirty(s);
    }

    /**
     * Retrieves the OpenJPA state manager for this entity.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and provides access to the
     * state manager that tracks this entity's persistence state.</p>
     *
     * @return StateManager the state manager, or null if this instance is not managed
     */
    public StateManager pcGetStateManager() {
        return this.pcStateManager;
    }

    /**
     * Retrieves the version number for optimistic locking.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and provides access to the
     * version field used for optimistic locking and concurrency control.</p>
     *
     * @return Object the version object, or null if there is no state manager
     */
    public Object pcGetVersion() {
        if (this.pcStateManager == null) {
            return null;
        }
        return this.pcStateManager.getVersion();
    }

    /**
     * Replaces the current state manager with a new one.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and is used by the JPA provider
     * during state transitions. It should not be called directly by application code.</p>
     *
     * @param pcStateManager StateManager the new state manager to use
     * @throws SecurityException if the state manager replacement is not allowed
     */
    public void pcReplaceStateManager(final StateManager pcStateManager) throws SecurityException {
        if (this.pcStateManager != null) {
            this.pcStateManager = this.pcStateManager.replaceStateManager(pcStateManager);
            return;
        }
        this.pcStateManager = pcStateManager;
    }
    
    /**
     * Copies key fields to an object ID using a field supplier.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface. This implementation throws
     * InternalException because this entity uses an embedded ID class rather than individual key fields.</p>
     *
     * @param fieldSupplier FieldSupplier the field supplier to use for copying
     * @param o Object the target object ID
     * @throws InternalException always, as this operation is not supported for embedded ID classes
     */
    public void pcCopyKeyFieldsToObjectId(final FieldSupplier fieldSupplier, final Object o) {
        throw new InternalException();
    }

    /**
     * Copies key fields directly to an object ID.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface. This implementation throws
     * InternalException because this entity uses an embedded ID class rather than individual key fields.</p>
     *
     * @param o Object the target object ID
     * @throws InternalException always, as this operation is not supported for embedded ID classes
     */
    public void pcCopyKeyFieldsToObjectId(final Object o) {
        throw new InternalException();
    }

    /**
     * Copies key fields from an object ID using a field consumer.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and is used by the JPA provider
     * to populate the entity's key fields from an object ID.</p>
     *
     * @param fieldConsumer FieldConsumer the field consumer to store the key fields into
     * @param o Object the source object ID containing the key field values
     */
    public void pcCopyKeyFieldsFromObjectId(final FieldConsumer fieldConsumer, final Object o) {
        fieldConsumer.storeObjectField(0 + CachedMeasurementMap.pcInheritedFieldCount, ((ObjectId)o).getId());
    }

    /**
     * Copies key fields directly from an object ID to this entity.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and is used by the JPA provider
     * to set the composite primary key from an object ID.</p>
     *
     * @param o Object the source ObjectId containing the FacilityIdIntegerCompositePk
     */
    public void pcCopyKeyFieldsFromObjectId(final Object o) {
        this.facilityMeasurementMapPk = (FacilityIdIntegerCompositePk)((ObjectId)o).getId();
    }

    /**
     * Creates a new object ID instance from a string representation.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface. This implementation always throws
     * IllegalArgumentException because the ObjectId class does not support string-based construction for
     * embedded composite keys.</p>
     *
     * @param o Object the string representation of the object ID
     * @return Object never returns normally
     * @throws IllegalArgumentException always, as string-based construction is not supported
     */
    public Object pcNewObjectIdInstance(final Object o) {
        throw new IllegalArgumentException("The id type \"class org.apache.openjpa.util.ObjectId\" specified by persistent type \"class ca.openosp.openo.caisi_integrator.dao.CachedMeasurementMap\" does not have a public class org.apache.openjpa.util.ObjectId(String) or class org.apache.openjpa.util.ObjectId(Class, String) constructor.");
    }

    /**
     * Creates a new object ID instance for this entity's current key values.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and creates an ObjectId
     * containing this entity's composite primary key.</p>
     *
     * @return Object a new ObjectId wrapping this entity's FacilityIdIntegerCompositePk
     */
    public Object pcNewObjectIdInstance() {
        return new ObjectId((CachedMeasurementMap.class$Lca$openosp$openo$caisi_integrator$dao$CachedMeasurementMap != null) ? CachedMeasurementMap.class$Lca$openosp$openo$caisi_integrator$dao$CachedMeasurementMap : (CachedMeasurementMap.class$Lca$openosp$openo$caisi_integrator$dao$CachedMeasurementMap = class$("ca.openosp.openo.caisi_integrator.dao.CachedMeasurementMap")), (Object)this.facilityMeasurementMapPk);
    }
    
    private static final FacilityIdIntegerCompositePk pcGetfacilityMeasurementMapPk(final CachedMeasurementMap cachedMeasurementMap) {
        if (cachedMeasurementMap.pcStateManager == null) {
            return cachedMeasurementMap.facilityMeasurementMapPk;
        }
        cachedMeasurementMap.pcStateManager.accessingField(CachedMeasurementMap.pcInheritedFieldCount + 0);
        return cachedMeasurementMap.facilityMeasurementMapPk;
    }
    
    private static final void pcSetfacilityMeasurementMapPk(final CachedMeasurementMap cachedMeasurementMap, final FacilityIdIntegerCompositePk facilityMeasurementMapPk) {
        if (cachedMeasurementMap.pcStateManager == null) {
            cachedMeasurementMap.facilityMeasurementMapPk = facilityMeasurementMapPk;
            return;
        }
        cachedMeasurementMap.pcStateManager.settingObjectField((PersistenceCapable)cachedMeasurementMap, CachedMeasurementMap.pcInheritedFieldCount + 0, (Object)cachedMeasurementMap.facilityMeasurementMapPk, (Object)facilityMeasurementMapPk, 0);
    }
    
    private static final String pcGetidentCode(final CachedMeasurementMap cachedMeasurementMap) {
        if (cachedMeasurementMap.pcStateManager == null) {
            return cachedMeasurementMap.identCode;
        }
        cachedMeasurementMap.pcStateManager.accessingField(CachedMeasurementMap.pcInheritedFieldCount + 1);
        return cachedMeasurementMap.identCode;
    }
    
    private static final void pcSetidentCode(final CachedMeasurementMap cachedMeasurementMap, final String identCode) {
        if (cachedMeasurementMap.pcStateManager == null) {
            cachedMeasurementMap.identCode = identCode;
            return;
        }
        cachedMeasurementMap.pcStateManager.settingStringField((PersistenceCapable)cachedMeasurementMap, CachedMeasurementMap.pcInheritedFieldCount + 1, cachedMeasurementMap.identCode, identCode, 0);
    }
    
    private static final String pcGetlabType(final CachedMeasurementMap cachedMeasurementMap) {
        if (cachedMeasurementMap.pcStateManager == null) {
            return cachedMeasurementMap.labType;
        }
        cachedMeasurementMap.pcStateManager.accessingField(CachedMeasurementMap.pcInheritedFieldCount + 2);
        return cachedMeasurementMap.labType;
    }
    
    private static final void pcSetlabType(final CachedMeasurementMap cachedMeasurementMap, final String labType) {
        if (cachedMeasurementMap.pcStateManager == null) {
            cachedMeasurementMap.labType = labType;
            return;
        }
        cachedMeasurementMap.pcStateManager.settingStringField((PersistenceCapable)cachedMeasurementMap, CachedMeasurementMap.pcInheritedFieldCount + 2, cachedMeasurementMap.labType, labType, 0);
    }
    
    private static final String pcGetloincCode(final CachedMeasurementMap cachedMeasurementMap) {
        if (cachedMeasurementMap.pcStateManager == null) {
            return cachedMeasurementMap.loincCode;
        }
        cachedMeasurementMap.pcStateManager.accessingField(CachedMeasurementMap.pcInheritedFieldCount + 3);
        return cachedMeasurementMap.loincCode;
    }
    
    private static final void pcSetloincCode(final CachedMeasurementMap cachedMeasurementMap, final String loincCode) {
        if (cachedMeasurementMap.pcStateManager == null) {
            cachedMeasurementMap.loincCode = loincCode;
            return;
        }
        cachedMeasurementMap.pcStateManager.settingStringField((PersistenceCapable)cachedMeasurementMap, CachedMeasurementMap.pcInheritedFieldCount + 3, cachedMeasurementMap.loincCode, loincCode, 0);
    }
    
    private static final String pcGetname(final CachedMeasurementMap cachedMeasurementMap) {
        if (cachedMeasurementMap.pcStateManager == null) {
            return cachedMeasurementMap.name;
        }
        cachedMeasurementMap.pcStateManager.accessingField(CachedMeasurementMap.pcInheritedFieldCount + 4);
        return cachedMeasurementMap.name;
    }
    
    private static final void pcSetname(final CachedMeasurementMap cachedMeasurementMap, final String name) {
        if (cachedMeasurementMap.pcStateManager == null) {
            cachedMeasurementMap.name = name;
            return;
        }
        cachedMeasurementMap.pcStateManager.settingStringField((PersistenceCapable)cachedMeasurementMap, CachedMeasurementMap.pcInheritedFieldCount + 4, cachedMeasurementMap.name, name, 0);
    }
    
    /**
     * Checks if this entity is detached from the persistence context.
     *
     * <p>A detached entity was previously managed but is no longer associated with a persistence context.
     * Detached entities can be reattached (merged) back into a persistence context later.</p>
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and returns:</p>
     * <ul>
     *   <li>Boolean.TRUE if the entity is definitely detached</li>
     *   <li>Boolean.FALSE if the entity is definitely not detached</li>
     *   <li>null if the detached status cannot be determined definitively</li>
     * </ul>
     *
     * @return Boolean the detached status, or null if indeterminate
     */
    public Boolean pcIsDetached() {
        if (this.pcStateManager != null) {
            if (this.pcStateManager.isDetached()) {
                return Boolean.TRUE;
            }
            return Boolean.FALSE;
        }
        else {
            if (this.pcGetDetachedState() != null && this.pcGetDetachedState() != PersistenceCapable.DESERIALIZED) {
                return Boolean.TRUE;
            }
            if (!this.pcisDetachedStateDefinitive()) {
                return null;
            }
            if (this.pcGetDetachedState() == null) {
                return Boolean.FALSE;
            }
            return null;
        }
    }
    
    private boolean pcisDetachedStateDefinitive() {
        return false;
    }
    
    /**
     * Retrieves the detached state object for this entity.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and provides access to the
     * internal state used to track whether the entity is detached. The detached state is used during
     * merge operations to determine how to reattach the entity.</p>
     *
     * @return Object the detached state, or null if not detached
     */
    public Object pcGetDetachedState() {
        return this.pcDetachedState;
    }

    /**
     * Sets the detached state object for this entity.
     *
     * <p>This method is part of the OpenJPA PersistenceCapable interface and is used by the JPA provider
     * to mark the entity as detached and track its detached state. It should not be called directly by
     * application code.</p>
     *
     * @param pcDetachedState Object the detached state to set
     */
    public void pcSetDetachedState(final Object pcDetachedState) {
        this.pcDetachedState = pcDetachedState;
    }
    
    private void writeObject(final ObjectOutputStream objectOutputStream) throws IOException {
        final boolean pcSerializing = this.pcSerializing();
        objectOutputStream.defaultWriteObject();
        if (pcSerializing) {
            this.pcSetDetachedState(null);
        }
    }
    
    private void readObject(final ObjectInputStream objectInputStream) throws IOException, ClassNotFoundException {
        this.pcSetDetachedState(PersistenceCapable.DESERIALIZED);
        objectInputStream.defaultReadObject();
    }
}
