package ca.openosp.openo.caisi_integrator.dao;

import java.io.ObjectInputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import org.apache.openjpa.util.IntId;
import org.apache.openjpa.enhance.FieldConsumer;
import org.apache.openjpa.util.InternalException;
import org.apache.openjpa.enhance.FieldSupplier;
import org.apache.openjpa.enhance.RedefinitionHelper;
import org.apache.openjpa.enhance.PersistenceCapable;
import org.apache.openjpa.enhance.PCRegistry;
import org.apache.openjpa.enhance.StateManager;
import javax.persistence.TemporalType;
import javax.persistence.Temporal;
import java.util.Date;
import org.apache.openjpa.persistence.jdbc.Index;
import javax.persistence.Column;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.UniqueConstraint;
import javax.persistence.Table;
import javax.persistence.Entity;

/**
 * JPA entity representing a link between two demographic records across different healthcare facilities
 * in the CAISI integrator system.
 *
 * This class enables the OpenO EMR system to maintain patient demographic relationships across
 * multiple healthcare facilities and CAISI (Client Access to Integrated Services and Information)
 * installations. It tracks which demographic records in different facilities represent the same
 * patient, supporting cross-facility care coordination and data integration.
 *
 * The entity enforces a unique constraint ensuring that any pair of demographics from two facilities
 * can only be linked once, preventing duplicate or conflicting links. Each link includes audit
 * information tracking which provider created the link and when it was established.
 *
 * This class is enhanced by OpenJPA at runtime to support persistence capabilities, implementing
 * the PersistenceCapable interface with generated bytecode for state management, field access,
 * and object identity management.
 *
 * @see AbstractModel
 * @see PersistenceCapable
 * @since 2026-01-24
 */
@Entity
@Table(uniqueConstraints = { @UniqueConstraint(columnNames = { "integratorDemographicFacilityId1", "caisiDemographicId1", "integratorDemographicFacilityId2", "caisiDemographicId2" }) })
public class DemographicLink extends AbstractModel<Integer> implements PersistenceCapable
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    @Column(nullable = false)
    @Index
    private Integer integratorDemographicFacilityId1;
    @Column(nullable = false)
    @Index
    private Integer caisiDemographicId1;
    @Column(nullable = false)
    @Index
    private Integer integratorDemographicFacilityId2;
    @Column(nullable = false)
    @Index
    private Integer caisiDemographicId2;
    @Column(nullable = false)
    private Integer creatorIntegratorProviderFacilityId;
    @Column(nullable = false, length = 16)
    private String creatorCaisiProviderId;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(nullable = false)
    private Date createdDate;
    private static int pcInheritedFieldCount;
    private static String[] pcFieldNames;
    private static Class[] pcFieldTypes;
    private static byte[] pcFieldFlags;
    private static Class pcPCSuperclass;
    protected transient StateManager pcStateManager;
    static /* synthetic */ Class class$Ljava$lang$Integer;
    static /* synthetic */ Class class$Ljava$util$Date;
    static /* synthetic */ Class class$Ljava$lang$String;
    static /* synthetic */ Class class$Lca$openosp$openo$caisi_integrator$dao$DemographicLink;
    private transient Object pcDetachedState;
    private static final long serialVersionUID;

    /**
     * Default constructor that initializes a new demographic link with default values.
     *
     * All demographic and facility ID fields are initialized to null, and the created date
     * is set to the current timestamp. This constructor is used by JPA when instantiating
     * entities from database records and when creating new instances programmatically.
     */
    public DemographicLink() {
        this.id = null;
        this.integratorDemographicFacilityId1 = null;
        this.caisiDemographicId1 = null;
        this.integratorDemographicFacilityId2 = null;
        this.caisiDemographicId2 = null;
        this.creatorIntegratorProviderFacilityId = null;
        this.creatorCaisiProviderId = null;
        this.createdDate = new Date();
    }

    /**
     * Retrieves the integrator facility identifier for the first demographic in the link.
     *
     * This represents the healthcare facility where the first demographic record is managed
     * within the integrator system. The facility ID is required and cannot be null.
     *
     * @return Integer the integrator facility identifier for the first demographic
     */
    public Integer getIntegratorDemographicFacilityId1() {
        return pcGetintegratorDemographicFacilityId1(this);
    }

    /**
     * Sets the integrator facility identifier for the first demographic in the link.
     *
     * This value is required and cannot be null. It identifies the healthcare facility
     * managing the first demographic record in the integrator system.
     *
     * @param integratorDemographicFacilityId1 Integer the integrator facility identifier for the first demographic (required, cannot be null)
     */
    public void setIntegratorDemographicFacilityId1(final Integer integratorDemographicFacilityId1) {
        pcSetintegratorDemographicFacilityId1(this, integratorDemographicFacilityId1);
    }

    /**
     * Retrieves the CAISI demographic identifier for the first patient record in the link.
     *
     * This is the unique identifier of the first demographic record within the CAISI system
     * at the facility specified by integratorDemographicFacilityId1. This field is required
     * and cannot be null.
     *
     * @return Integer the CAISI demographic identifier for the first patient record
     */
    public Integer getCaisiDemographicId1() {
        return pcGetcaisiDemographicId1(this);
    }

    /**
     * Sets the CAISI demographic identifier for the first patient record in the link.
     *
     * This value is required and cannot be null. It identifies the first demographic record
     * within the CAISI system at the facility specified by integratorDemographicFacilityId1.
     *
     * @param caisiDemographicId1 Integer the CAISI demographic identifier for the first patient record (required, cannot be null)
     */
    public void setCaisiDemographicId1(final Integer caisiDemographicId1) {
        pcSetcaisiDemographicId1(this, caisiDemographicId1);
    }

    /**
     * Retrieves the integrator facility identifier for the second demographic in the link.
     *
     * This represents the healthcare facility where the second demographic record is managed
     * within the integrator system. The facility ID is required and cannot be null.
     *
     * @return Integer the integrator facility identifier for the second demographic
     */
    public Integer getIntegratorDemographicFacilityId2() {
        return pcGetintegratorDemographicFacilityId2(this);
    }

    /**
     * Sets the integrator facility identifier for the second demographic in the link.
     *
     * This value is required and cannot be null. It identifies the healthcare facility
     * managing the second demographic record in the integrator system.
     *
     * @param integratorDemographicFacilityId2 Integer the integrator facility identifier for the second demographic (required, cannot be null)
     */
    public void setIntegratorDemographicFacilityId2(final Integer integratorDemographicFacilityId2) {
        pcSetintegratorDemographicFacilityId2(this, integratorDemographicFacilityId2);
    }

    /**
     * Retrieves the CAISI demographic identifier for the second patient record in the link.
     *
     * This is the unique identifier of the second demographic record within the CAISI system
     * at the facility specified by integratorDemographicFacilityId2. This field is required
     * and cannot be null.
     *
     * @return Integer the CAISI demographic identifier for the second patient record
     */
    public Integer getCaisiDemographicId2() {
        return pcGetcaisiDemographicId2(this);
    }

    /**
     * Sets the CAISI demographic identifier for the second patient record in the link.
     *
     * This value is required and cannot be null. It identifies the second demographic record
     * within the CAISI system at the facility specified by integratorDemographicFacilityId2.
     *
     * @param caisiDemographicId2 Integer the CAISI demographic identifier for the second patient record (required, cannot be null)
     */
    public void setCaisiDemographicId2(final Integer caisiDemographicId2) {
        pcSetcaisiDemographicId2(this, caisiDemographicId2);
    }

    /**
     * Retrieves the integrator facility identifier for the healthcare provider who created this link.
     *
     * This represents the facility where the provider who established this demographic link
     * is registered within the integrator system. This field is required for audit purposes
     * and cannot be null.
     *
     * @return Integer the integrator facility identifier for the provider who created the link
     */
    public Integer getCreatorIntegratorProviderFacilityId() {
        return pcGetcreatorIntegratorProviderFacilityId(this);
    }

    /**
     * Sets the integrator facility identifier for the healthcare provider who created this link.
     *
     * This value is required for audit purposes and cannot be null. It identifies the facility
     * where the provider who established this demographic link is registered.
     *
     * @param creatorIntegratorProviderFacilityId Integer the integrator facility identifier for the provider who created the link (required, cannot be null)
     */
    public void setCreatorIntegratorProviderFacilityId(final Integer creatorIntegratorProviderFacilityId) {
        pcSetcreatorIntegratorProviderFacilityId(this, creatorIntegratorProviderFacilityId);
    }

    /**
     * Retrieves the CAISI provider identifier for the healthcare provider who created this link.
     *
     * This is the unique identifier of the provider within the CAISI system at their facility
     * who established this demographic link. This field is required for audit purposes and
     * cannot be null. Maximum length is 16 characters.
     *
     * @return String the CAISI provider identifier for the creator of this link
     */
    public String getCreatorCaisiProviderId() {
        return pcGetcreatorCaisiProviderId(this);
    }

    /**
     * Sets the CAISI provider identifier for the healthcare provider who created this link.
     *
     * This value is required for audit purposes and cannot be null. It identifies the provider
     * within the CAISI system at their facility who established this demographic link.
     * Maximum length is 16 characters.
     *
     * @param creatorCaisiProviderId String the CAISI provider identifier for the creator of this link (required, cannot be null, max 16 characters)
     */
    public void setCreatorCaisiProviderId(final String creatorCaisiProviderId) {
        pcSetcreatorCaisiProviderId(this, creatorCaisiProviderId);
    }

    /**
     * Retrieves the timestamp when this demographic link was created.
     *
     * This timestamp records when the link between the two demographic records was established.
     * It is required for audit purposes and cannot be null. The timestamp is stored with
     * both date and time components (TIMESTAMP type).
     *
     * @return Date the timestamp when this link was created
     */
    public Date getCreatedDate() {
        return pcGetcreatedDate(this);
    }

    /**
     * Generates a hash code for this demographic link based on its unique identifier.
     *
     * This implementation uses the ID field to compute the hash code, ensuring consistency
     * with the equals method. Two demographic links with the same ID will produce the same
     * hash code.
     *
     * @return int the hash code for this demographic link
     */
    @Override
    public int hashCode() {
        return pcGetid(this).hashCode();
    }

    /**
     * Determines whether this demographic link is equal to another object.
     *
     * Two demographic links are considered equal if they have the same ID. This method
     * only compares the ID field and assumes the provided object is a DemographicLink instance.
     *
     * Note: This implementation does not perform type checking or null checks, which may
     * result in ClassCastException or NullPointerException if the parameter is not a valid
     * DemographicLink instance.
     *
     * @param o Object the object to compare with this demographic link
     * @return boolean true if the objects have the same ID, false otherwise
     */
    @Override
    public boolean equals(final Object o) {
        return pcGetid(this).equals(((DemographicLink)o).getId());
    }

    /**
     * Retrieves the unique identifier for this demographic link.
     *
     * This is the primary key of the entity, auto-generated using an identity strategy.
     * Each demographic link has a unique ID that persists across the lifetime of the record.
     *
     * @return Integer the unique identifier for this demographic link
     */
    @Override
    public Integer getId() {
        return pcGetid(this);
    }

    /**
     * Returns the version of the OpenJPA enhancement contract implemented by this class.
     *
     * This method is part of the PersistenceCapable interface and is used by OpenJPA to
     * determine the version of bytecode enhancement applied to this entity. The value of 2
     * indicates the current enhancement contract version.
     *
     * @return int the enhancement contract version (2)
     */
    public int pcGetEnhancementContractVersion() {
        return 2;
    }
    
    static {
        serialVersionUID = 4681496997954442913L;
        DemographicLink.pcFieldNames = new String[] { "caisiDemographicId1", "caisiDemographicId2", "createdDate", "creatorCaisiProviderId", "creatorIntegratorProviderFacilityId", "id", "integratorDemographicFacilityId1", "integratorDemographicFacilityId2" };
        DemographicLink.pcFieldTypes = new Class[] { (DemographicLink.class$Ljava$lang$Integer != null) ? DemographicLink.class$Ljava$lang$Integer : (DemographicLink.class$Ljava$lang$Integer = class$("java.lang.Integer")), (DemographicLink.class$Ljava$lang$Integer != null) ? DemographicLink.class$Ljava$lang$Integer : (DemographicLink.class$Ljava$lang$Integer = class$("java.lang.Integer")), (DemographicLink.class$Ljava$util$Date != null) ? DemographicLink.class$Ljava$util$Date : (DemographicLink.class$Ljava$util$Date = class$("java.util.Date")), (DemographicLink.class$Ljava$lang$String != null) ? DemographicLink.class$Ljava$lang$String : (DemographicLink.class$Ljava$lang$String = class$("java.lang.String")), (DemographicLink.class$Ljava$lang$Integer != null) ? DemographicLink.class$Ljava$lang$Integer : (DemographicLink.class$Ljava$lang$Integer = class$("java.lang.Integer")), (DemographicLink.class$Ljava$lang$Integer != null) ? DemographicLink.class$Ljava$lang$Integer : (DemographicLink.class$Ljava$lang$Integer = class$("java.lang.Integer")), (DemographicLink.class$Ljava$lang$Integer != null) ? DemographicLink.class$Ljava$lang$Integer : (DemographicLink.class$Ljava$lang$Integer = class$("java.lang.Integer")), (DemographicLink.class$Ljava$lang$Integer != null) ? DemographicLink.class$Ljava$lang$Integer : (DemographicLink.class$Ljava$lang$Integer = class$("java.lang.Integer")) };
        DemographicLink.pcFieldFlags = new byte[] { 26, 26, 26, 26, 26, 26, 26, 26 };
        PCRegistry.register((DemographicLink.class$Lca$openosp$openo$caisi_integrator$dao$DemographicLink != null) ? DemographicLink.class$Lca$openosp$openo$caisi_integrator$dao$DemographicLink : (DemographicLink.class$Lca$openosp$openo$caisi_integrator$dao$DemographicLink = class$("ca.openosp.openo.caisi_integrator.dao.DemographicLink")), DemographicLink.pcFieldNames, DemographicLink.pcFieldTypes, DemographicLink.pcFieldFlags, DemographicLink.pcPCSuperclass, "DemographicLink", (PersistenceCapable)new DemographicLink());
    }
    
    static /* synthetic */ Class class$(final String className) {
        try {
            return Class.forName(className);
        }
        catch (final ClassNotFoundException ex) {
            throw new NoClassDefFoundError(ex.getMessage());
        }
    }
    
    protected void pcClearFields() {
        this.caisiDemographicId1 = null;
        this.caisiDemographicId2 = null;
        this.createdDate = null;
        this.creatorCaisiProviderId = null;
        this.creatorIntegratorProviderFacilityId = null;
        this.id = null;
        this.integratorDemographicFacilityId1 = null;
        this.integratorDemographicFacilityId2 = null;
    }

    /**
     * Creates a new instance of DemographicLink with the specified state manager and object ID.
     *
     * This method is part of the PersistenceCapable interface and is called by OpenJPA during
     * entity lifecycle operations. It creates a new instance, optionally clears its fields,
     * sets the state manager, and copies key fields from the provided object ID.
     *
     * @param pcStateManager StateManager the state manager to associate with the new instance
     * @param o Object the object ID to copy key fields from
     * @param b boolean if true, clears all persistent fields before setting the state manager
     * @return PersistenceCapable a new DemographicLink instance configured with the specified state
     */
    public PersistenceCapable pcNewInstance(final StateManager pcStateManager, final Object o, final boolean b) {
        final DemographicLink demographicLink = new DemographicLink();
        if (b) {
            demographicLink.pcClearFields();
        }
        demographicLink.pcStateManager = pcStateManager;
        demographicLink.pcCopyKeyFieldsFromObjectId(o);
        return (PersistenceCapable)demographicLink;
    }

    /**
     * Creates a new instance of DemographicLink with the specified state manager.
     *
     * This method is part of the PersistenceCapable interface and is called by OpenJPA during
     * entity lifecycle operations. It creates a new instance, optionally clears its fields,
     * and sets the state manager.
     *
     * @param pcStateManager StateManager the state manager to associate with the new instance
     * @param b boolean if true, clears all persistent fields before setting the state manager
     * @return PersistenceCapable a new DemographicLink instance configured with the specified state
     */
    public PersistenceCapable pcNewInstance(final StateManager pcStateManager, final boolean b) {
        final DemographicLink demographicLink = new DemographicLink();
        if (b) {
            demographicLink.pcClearFields();
        }
        demographicLink.pcStateManager = pcStateManager;
        return (PersistenceCapable)demographicLink;
    }

    /**
     * Returns the number of persistent fields managed by OpenJPA for this entity.
     *
     * This method is part of the OpenJPA enhancement infrastructure and returns the count
     * of all persistent fields in this class. The value of 8 represents the eight persistent
     * fields defined in DemographicLink.
     *
     * @return int the number of persistent fields managed by OpenJPA (8)
     */
    protected static int pcGetManagedFieldCount() {
        return 8;
    }

    /**
     * Replaces a single persistent field value from the state manager.
     *
     * This method is part of the PersistenceCapable interface and is called by OpenJPA
     * to restore field values during entity lifecycle operations (such as rollback or refresh).
     * The field is identified by its index, and the value is retrieved from the state manager.
     *
     * @param n int the index of the field to replace
     * @throws IllegalArgumentException if the field index is invalid
     */
    public void pcReplaceField(final int n) {
        final int n2 = n - DemographicLink.pcInheritedFieldCount;
        if (n2 < 0) {
            throw new IllegalArgumentException();
        }
        switch (n2) {
            case 0: {
                this.caisiDemographicId1 = (Integer)this.pcStateManager.replaceObjectField((PersistenceCapable)this, n);
                return;
            }
            case 1: {
                this.caisiDemographicId2 = (Integer)this.pcStateManager.replaceObjectField((PersistenceCapable)this, n);
                return;
            }
            case 2: {
                this.createdDate = (Date)this.pcStateManager.replaceObjectField((PersistenceCapable)this, n);
                return;
            }
            case 3: {
                this.creatorCaisiProviderId = this.pcStateManager.replaceStringField((PersistenceCapable)this, n);
                return;
            }
            case 4: {
                this.creatorIntegratorProviderFacilityId = (Integer)this.pcStateManager.replaceObjectField((PersistenceCapable)this, n);
                return;
            }
            case 5: {
                this.id = (Integer)this.pcStateManager.replaceObjectField((PersistenceCapable)this, n);
                return;
            }
            case 6: {
                this.integratorDemographicFacilityId1 = (Integer)this.pcStateManager.replaceObjectField((PersistenceCapable)this, n);
                return;
            }
            case 7: {
                this.integratorDemographicFacilityId2 = (Integer)this.pcStateManager.replaceObjectField((PersistenceCapable)this, n);
                return;
            }
            default: {
                throw new IllegalArgumentException();
            }
        }
    }

    /**
     * Replaces multiple persistent field values from the state manager.
     *
     * This method is part of the PersistenceCapable interface and is called by OpenJPA
     * to restore multiple field values during entity lifecycle operations. It delegates
     * to pcReplaceField for each field index in the array.
     *
     * @param array int[] array of field indices to replace
     */
    public void pcReplaceFields(final int[] array) {
        for (int i = 0; i < array.length; ++i) {
            this.pcReplaceField(array[i]);
        }
    }

    /**
     * Provides a single persistent field value to the state manager.
     *
     * This method is part of the PersistenceCapable interface and is called by OpenJPA
     * to retrieve field values during persistence operations (such as flush or detach).
     * The field is identified by its index, and the value is provided to the state manager.
     *
     * @param n int the index of the field to provide
     * @throws IllegalArgumentException if the field index is invalid
     */
    public void pcProvideField(final int n) {
        final int n2 = n - DemographicLink.pcInheritedFieldCount;
        if (n2 < 0) {
            throw new IllegalArgumentException();
        }
        switch (n2) {
            case 0: {
                this.pcStateManager.providedObjectField((PersistenceCapable)this, n, (Object)this.caisiDemographicId1);
                return;
            }
            case 1: {
                this.pcStateManager.providedObjectField((PersistenceCapable)this, n, (Object)this.caisiDemographicId2);
                return;
            }
            case 2: {
                this.pcStateManager.providedObjectField((PersistenceCapable)this, n, (Object)this.createdDate);
                return;
            }
            case 3: {
                this.pcStateManager.providedStringField((PersistenceCapable)this, n, this.creatorCaisiProviderId);
                return;
            }
            case 4: {
                this.pcStateManager.providedObjectField((PersistenceCapable)this, n, (Object)this.creatorIntegratorProviderFacilityId);
                return;
            }
            case 5: {
                this.pcStateManager.providedObjectField((PersistenceCapable)this, n, (Object)this.id);
                return;
            }
            case 6: {
                this.pcStateManager.providedObjectField((PersistenceCapable)this, n, (Object)this.integratorDemographicFacilityId1);
                return;
            }
            case 7: {
                this.pcStateManager.providedObjectField((PersistenceCapable)this, n, (Object)this.integratorDemographicFacilityId2);
                return;
            }
            default: {
                throw new IllegalArgumentException();
            }
        }
    }

    /**
     * Provides multiple persistent field values to the state manager.
     *
     * This method is part of the PersistenceCapable interface and is called by OpenJPA
     * to retrieve multiple field values during persistence operations. It delegates
     * to pcProvideField for each field index in the array.
     *
     * @param array int[] array of field indices to provide
     */
    public void pcProvideFields(final int[] array) {
        for (int i = 0; i < array.length; ++i) {
            this.pcProvideField(array[i]);
        }
    }
    
    protected void pcCopyField(final DemographicLink demographicLink, final int n) {
        final int n2 = n - DemographicLink.pcInheritedFieldCount;
        if (n2 < 0) {
            throw new IllegalArgumentException();
        }
        switch (n2) {
            case 0: {
                this.caisiDemographicId1 = demographicLink.caisiDemographicId1;
                return;
            }
            case 1: {
                this.caisiDemographicId2 = demographicLink.caisiDemographicId2;
                return;
            }
            case 2: {
                this.createdDate = demographicLink.createdDate;
                return;
            }
            case 3: {
                this.creatorCaisiProviderId = demographicLink.creatorCaisiProviderId;
                return;
            }
            case 4: {
                this.creatorIntegratorProviderFacilityId = demographicLink.creatorIntegratorProviderFacilityId;
                return;
            }
            case 5: {
                this.id = demographicLink.id;
                return;
            }
            case 6: {
                this.integratorDemographicFacilityId1 = demographicLink.integratorDemographicFacilityId1;
                return;
            }
            case 7: {
                this.integratorDemographicFacilityId2 = demographicLink.integratorDemographicFacilityId2;
                return;
            }
            default: {
                throw new IllegalArgumentException();
            }
        }
    }

    /**
     * Copies multiple persistent field values from another DemographicLink instance.
     *
     * This method is part of the PersistenceCapable interface and is called by OpenJPA
     * during entity merge and refresh operations. It validates that both instances share
     * the same state manager and copies the specified fields from the source instance.
     *
     * @param o Object the source DemographicLink instance to copy fields from
     * @param array int[] array of field indices to copy
     * @throws IllegalArgumentException if the source instance has a different state manager
     * @throws IllegalStateException if the state manager is null
     */
    public void pcCopyFields(final Object o, final int[] array) {
        final DemographicLink demographicLink = (DemographicLink)o;
        if (demographicLink.pcStateManager != this.pcStateManager) {
            throw new IllegalArgumentException();
        }
        if (this.pcStateManager == null) {
            throw new IllegalStateException();
        }
        for (int i = 0; i < array.length; ++i) {
            this.pcCopyField(demographicLink, array[i]);
        }
    }

    /**
     * Retrieves the generic context associated with this entity's state manager.
     *
     * This method is part of the PersistenceCapable interface and returns the generic
     * context object from the state manager, which may contain additional state or
     * configuration information. Returns null if no state manager is set.
     *
     * @return Object the generic context from the state manager, or null if no state manager exists
     */
    public Object pcGetGenericContext() {
        if (this.pcStateManager == null) {
            return null;
        }
        return this.pcStateManager.getGenericContext();
    }

    /**
     * Retrieves the object ID for this entity from the state manager.
     *
     * This method is part of the PersistenceCapable interface and returns the unique
     * object identifier assigned to this instance by OpenJPA. Returns null if no
     * state manager is set.
     *
     * @return Object the object ID for this entity, or null if no state manager exists
     */
    public Object pcFetchObjectId() {
        if (this.pcStateManager == null) {
            return null;
        }
        return this.pcStateManager.fetchObjectId();
    }

    /**
     * Determines whether this entity has been marked for deletion.
     *
     * This method is part of the PersistenceCapable interface and checks if the entity
     * is in a deleted state within the current persistence context. Returns false if
     * no state manager is set.
     *
     * @return boolean true if the entity is marked for deletion, false otherwise
     */
    public boolean pcIsDeleted() {
        return this.pcStateManager != null && this.pcStateManager.isDeleted();
    }

    /**
     * Determines whether this entity has been modified since it was last synchronized with the database.
     *
     * This method is part of the PersistenceCapable interface and checks if any persistent
     * fields have been modified. It performs a dirty check through the RedefinitionHelper
     * before querying the state manager. Returns false if no state manager is set.
     *
     * @return boolean true if the entity has unsaved changes, false otherwise
     */
    public boolean pcIsDirty() {
        if (this.pcStateManager == null) {
            return false;
        }
        final StateManager pcStateManager = this.pcStateManager;
        RedefinitionHelper.dirtyCheck(pcStateManager);
        return pcStateManager.isDirty();
    }

    /**
     * Determines whether this entity represents a new record not yet persisted to the database.
     *
     * This method is part of the PersistenceCapable interface and checks if the entity
     * is in a new (transient) state within the persistence context. Returns false if
     * no state manager is set.
     *
     * @return boolean true if the entity is new and not yet persisted, false otherwise
     */
    public boolean pcIsNew() {
        return this.pcStateManager != null && this.pcStateManager.isNew();
    }

    /**
     * Determines whether this entity is managed by a persistence context.
     *
     * This method is part of the PersistenceCapable interface and checks if the entity
     * is in a persistent state (either already saved to the database or pending save).
     * Returns false if no state manager is set.
     *
     * @return boolean true if the entity is managed by a persistence context, false otherwise
     */
    public boolean pcIsPersistent() {
        return this.pcStateManager != null && this.pcStateManager.isPersistent();
    }

    /**
     * Determines whether this entity is participating in a transaction.
     *
     * This method is part of the PersistenceCapable interface and checks if the entity
     * is enrolled in the current transaction scope. Returns false if no state manager is set.
     *
     * @return boolean true if the entity is transactional, false otherwise
     */
    public boolean pcIsTransactional() {
        return this.pcStateManager != null && this.pcStateManager.isTransactional();
    }

    /**
     * Determines whether this entity is currently being serialized.
     *
     * This method is part of the PersistenceCapable interface and checks if the entity
     * is in the process of serialization. Returns false if no state manager is set.
     *
     * @return boolean true if the entity is being serialized, false otherwise
     */
    public boolean pcSerializing() {
        return this.pcStateManager != null && this.pcStateManager.serializing();
    }

    /**
     * Marks a specific field as dirty to trigger change tracking.
     *
     * This method is part of the PersistenceCapable interface and notifies the state
     * manager that the specified field has been modified. This is used by OpenJPA to
     * track changes for optimistic locking and flush operations. Does nothing if no
     * state manager is set.
     *
     * @param s String the name of the field that was modified
     */
    public void pcDirty(final String s) {
        if (this.pcStateManager == null) {
            return;
        }
        this.pcStateManager.dirty(s);
    }

    /**
     * Retrieves the state manager associated with this entity.
     *
     * This method is part of the PersistenceCapable interface and returns the OpenJPA
     * state manager responsible for tracking the lifecycle and state of this entity.
     * Returns null if the entity is not currently managed.
     *
     * @return StateManager the state manager for this entity, or null if not managed
     */
    public StateManager pcGetStateManager() {
        return this.pcStateManager;
    }

    /**
     * Retrieves the version information for this entity used for optimistic locking.
     *
     * This method is part of the PersistenceCapable interface and returns the version
     * object from the state manager, which is used to detect concurrent modifications.
     * Returns null if no state manager is set.
     *
     * @return Object the version information for optimistic locking, or null if no state manager exists
     */
    public Object pcGetVersion() {
        if (this.pcStateManager == null) {
            return null;
        }
        return this.pcStateManager.getVersion();
    }

    /**
     * Replaces the current state manager with a new one.
     *
     * This method is part of the PersistenceCapable interface and is used by OpenJPA
     * to change the state manager associated with this entity. If a state manager already
     * exists, it delegates to the current state manager to perform the replacement,
     * allowing for state manager chaining.
     *
     * @param pcStateManager StateManager the new state manager to associate with this entity
     * @throws SecurityException if the state manager replacement is not permitted
     */
    public void pcReplaceStateManager(final StateManager pcStateManager) throws SecurityException {
        if (this.pcStateManager != null) {
            this.pcStateManager = this.pcStateManager.replaceStateManager(pcStateManager);
            return;
        }
        this.pcStateManager = pcStateManager;
    }

    /**
     * Copies key field values to an object ID using a field supplier.
     *
     * This method is part of the PersistenceCapable interface but is not implemented
     * for this entity type. Attempting to call this method will result in an InternalException.
     *
     * @param fieldSupplier FieldSupplier the field supplier to read key field values from
     * @param o Object the object ID to copy key fields to
     * @throws InternalException always thrown as this operation is not supported
     */
    public void pcCopyKeyFieldsToObjectId(final FieldSupplier fieldSupplier, final Object o) {
        throw new InternalException();
    }

    /**
     * Copies key field values to an object ID.
     *
     * This method is part of the PersistenceCapable interface but is not implemented
     * for this entity type. Attempting to call this method will result in an InternalException.
     *
     * @param o Object the object ID to copy key fields to
     * @throws InternalException always thrown as this operation is not supported
     */
    public void pcCopyKeyFieldsToObjectId(final Object o) {
        throw new InternalException();
    }

    /**
     * Copies key field values from an object ID using a field consumer.
     *
     * This method is part of the PersistenceCapable interface and is called by OpenJPA
     * to populate the ID field from an IntId object. The field consumer is used to set
     * the id field value at the appropriate field index.
     *
     * @param fieldConsumer FieldConsumer the field consumer to write key field values to
     * @param o Object the IntId object to copy the key field from
     */
    public void pcCopyKeyFieldsFromObjectId(final FieldConsumer fieldConsumer, final Object o) {
        fieldConsumer.storeObjectField(5 + DemographicLink.pcInheritedFieldCount, (Object)Integer.valueOf(((IntId)o).getId()));
    }

    /**
     * Copies key field values from an object ID directly to this entity.
     *
     * This method is part of the PersistenceCapable interface and is called by OpenJPA
     * to populate the ID field from an IntId object. The integer ID value is extracted
     * from the IntId and assigned to the id field.
     *
     * @param o Object the IntId object to copy the key field from
     */
    public void pcCopyKeyFieldsFromObjectId(final Object o) {
        this.id = Integer.valueOf(((IntId)o).getId());
    }

    /**
     * Creates a new object ID instance from a string representation.
     *
     * This method is part of the PersistenceCapable interface and is called by OpenJPA
     * to create an IntId object from a string representation of the ID. The IntId is
     * constructed with the DemographicLink class type and the provided string value.
     *
     * @param o Object the string representation of the ID
     * @return Object a new IntId instance for this entity type
     */
    public Object pcNewObjectIdInstance(final Object o) {
        return new IntId((DemographicLink.class$Lca$openosp$openo$caisi_integrator$dao$DemographicLink != null) ? DemographicLink.class$Lca$openosp$openo$caisi_integrator$dao$DemographicLink : (DemographicLink.class$Lca$openosp$openo$caisi_integrator$dao$DemographicLink = class$("ca.openosp.openo.caisi_integrator.dao.DemographicLink")), (String)o);
    }

    /**
     * Creates a new object ID instance from this entity's current ID value.
     *
     * This method is part of the PersistenceCapable interface and is called by OpenJPA
     * to create an IntId object representing this entity's identity. The IntId is
     * constructed with the DemographicLink class type and this entity's id field value.
     *
     * @return Object a new IntId instance containing this entity's ID
     */
    public Object pcNewObjectIdInstance() {
        return new IntId((DemographicLink.class$Lca$openosp$openo$caisi_integrator$dao$DemographicLink != null) ? DemographicLink.class$Lca$openosp$openo$caisi_integrator$dao$DemographicLink : (DemographicLink.class$Lca$openosp$openo$caisi_integrator$dao$DemographicLink = class$("ca.openosp.openo.caisi_integrator.dao.DemographicLink")), this.id);
    }
    
    private static final Integer pcGetcaisiDemographicId1(final DemographicLink demographicLink) {
        if (demographicLink.pcStateManager == null) {
            return demographicLink.caisiDemographicId1;
        }
        demographicLink.pcStateManager.accessingField(DemographicLink.pcInheritedFieldCount + 0);
        return demographicLink.caisiDemographicId1;
    }
    
    private static final void pcSetcaisiDemographicId1(final DemographicLink demographicLink, final Integer caisiDemographicId1) {
        if (demographicLink.pcStateManager == null) {
            demographicLink.caisiDemographicId1 = caisiDemographicId1;
            return;
        }
        demographicLink.pcStateManager.settingObjectField((PersistenceCapable)demographicLink, DemographicLink.pcInheritedFieldCount + 0, (Object)demographicLink.caisiDemographicId1, (Object)caisiDemographicId1, 0);
    }
    
    private static final Integer pcGetcaisiDemographicId2(final DemographicLink demographicLink) {
        if (demographicLink.pcStateManager == null) {
            return demographicLink.caisiDemographicId2;
        }
        demographicLink.pcStateManager.accessingField(DemographicLink.pcInheritedFieldCount + 1);
        return demographicLink.caisiDemographicId2;
    }
    
    private static final void pcSetcaisiDemographicId2(final DemographicLink demographicLink, final Integer caisiDemographicId2) {
        if (demographicLink.pcStateManager == null) {
            demographicLink.caisiDemographicId2 = caisiDemographicId2;
            return;
        }
        demographicLink.pcStateManager.settingObjectField((PersistenceCapable)demographicLink, DemographicLink.pcInheritedFieldCount + 1, (Object)demographicLink.caisiDemographicId2, (Object)caisiDemographicId2, 0);
    }
    
    private static final Date pcGetcreatedDate(final DemographicLink demographicLink) {
        if (demographicLink.pcStateManager == null) {
            return demographicLink.createdDate;
        }
        demographicLink.pcStateManager.accessingField(DemographicLink.pcInheritedFieldCount + 2);
        return demographicLink.createdDate;
    }
    
    private static final void pcSetcreatedDate(final DemographicLink demographicLink, final Date createdDate) {
        if (demographicLink.pcStateManager == null) {
            demographicLink.createdDate = createdDate;
            return;
        }
        demographicLink.pcStateManager.settingObjectField((PersistenceCapable)demographicLink, DemographicLink.pcInheritedFieldCount + 2, (Object)demographicLink.createdDate, (Object)createdDate, 0);
    }
    
    private static final String pcGetcreatorCaisiProviderId(final DemographicLink demographicLink) {
        if (demographicLink.pcStateManager == null) {
            return demographicLink.creatorCaisiProviderId;
        }
        demographicLink.pcStateManager.accessingField(DemographicLink.pcInheritedFieldCount + 3);
        return demographicLink.creatorCaisiProviderId;
    }
    
    private static final void pcSetcreatorCaisiProviderId(final DemographicLink demographicLink, final String creatorCaisiProviderId) {
        if (demographicLink.pcStateManager == null) {
            demographicLink.creatorCaisiProviderId = creatorCaisiProviderId;
            return;
        }
        demographicLink.pcStateManager.settingStringField((PersistenceCapable)demographicLink, DemographicLink.pcInheritedFieldCount + 3, demographicLink.creatorCaisiProviderId, creatorCaisiProviderId, 0);
    }
    
    private static final Integer pcGetcreatorIntegratorProviderFacilityId(final DemographicLink demographicLink) {
        if (demographicLink.pcStateManager == null) {
            return demographicLink.creatorIntegratorProviderFacilityId;
        }
        demographicLink.pcStateManager.accessingField(DemographicLink.pcInheritedFieldCount + 4);
        return demographicLink.creatorIntegratorProviderFacilityId;
    }
    
    private static final void pcSetcreatorIntegratorProviderFacilityId(final DemographicLink demographicLink, final Integer creatorIntegratorProviderFacilityId) {
        if (demographicLink.pcStateManager == null) {
            demographicLink.creatorIntegratorProviderFacilityId = creatorIntegratorProviderFacilityId;
            return;
        }
        demographicLink.pcStateManager.settingObjectField((PersistenceCapable)demographicLink, DemographicLink.pcInheritedFieldCount + 4, (Object)demographicLink.creatorIntegratorProviderFacilityId, (Object)creatorIntegratorProviderFacilityId, 0);
    }
    
    private static final Integer pcGetid(final DemographicLink demographicLink) {
        if (demographicLink.pcStateManager == null) {
            return demographicLink.id;
        }
        demographicLink.pcStateManager.accessingField(DemographicLink.pcInheritedFieldCount + 5);
        return demographicLink.id;
    }
    
    private static final void pcSetid(final DemographicLink demographicLink, final Integer id) {
        if (demographicLink.pcStateManager == null) {
            demographicLink.id = id;
            return;
        }
        demographicLink.pcStateManager.settingObjectField((PersistenceCapable)demographicLink, DemographicLink.pcInheritedFieldCount + 5, (Object)demographicLink.id, (Object)id, 0);
    }
    
    private static final Integer pcGetintegratorDemographicFacilityId1(final DemographicLink demographicLink) {
        if (demographicLink.pcStateManager == null) {
            return demographicLink.integratorDemographicFacilityId1;
        }
        demographicLink.pcStateManager.accessingField(DemographicLink.pcInheritedFieldCount + 6);
        return demographicLink.integratorDemographicFacilityId1;
    }
    
    private static final void pcSetintegratorDemographicFacilityId1(final DemographicLink demographicLink, final Integer integratorDemographicFacilityId1) {
        if (demographicLink.pcStateManager == null) {
            demographicLink.integratorDemographicFacilityId1 = integratorDemographicFacilityId1;
            return;
        }
        demographicLink.pcStateManager.settingObjectField((PersistenceCapable)demographicLink, DemographicLink.pcInheritedFieldCount + 6, (Object)demographicLink.integratorDemographicFacilityId1, (Object)integratorDemographicFacilityId1, 0);
    }
    
    private static final Integer pcGetintegratorDemographicFacilityId2(final DemographicLink demographicLink) {
        if (demographicLink.pcStateManager == null) {
            return demographicLink.integratorDemographicFacilityId2;
        }
        demographicLink.pcStateManager.accessingField(DemographicLink.pcInheritedFieldCount + 7);
        return demographicLink.integratorDemographicFacilityId2;
    }
    
    private static final void pcSetintegratorDemographicFacilityId2(final DemographicLink demographicLink, final Integer integratorDemographicFacilityId2) {
        if (demographicLink.pcStateManager == null) {
            demographicLink.integratorDemographicFacilityId2 = integratorDemographicFacilityId2;
            return;
        }
        demographicLink.pcStateManager.settingObjectField((PersistenceCapable)demographicLink, DemographicLink.pcInheritedFieldCount + 7, (Object)demographicLink.integratorDemographicFacilityId2, (Object)integratorDemographicFacilityId2, 0);
    }

    /**
     * Determines whether this entity is in a detached state.
     *
     * This method is part of the PersistenceCapable interface and checks if the entity
     * has been detached from its persistence context. The determination is based on:
     * - If a state manager exists, it delegates to the state manager's isDetached() method
     * - If no state manager exists, it checks the detached state field and ID field
     * - Returns null if the detached state is ambiguous
     *
     * @return Boolean true if detached, false if attached, or null if the state cannot be determined
     */
    public Boolean pcIsDetached() {
        if (this.pcStateManager != null) {
            if (this.pcStateManager.isDetached()) {
                return Boolean.TRUE;
            }
            return Boolean.FALSE;
        }
        else {
            if (this.pcGetDetachedState() != null && this.pcGetDetachedState() != PersistenceCapable.DESERIALIZED) {
                return Boolean.TRUE;
            }
            if (this.id != null) {
                return Boolean.TRUE;
            }
            if (!this.pcisDetachedStateDefinitive()) {
                return null;
            }
            if (this.pcGetDetachedState() == null) {
                return Boolean.FALSE;
            }
            return null;
        }
    }

    private boolean pcisDetachedStateDefinitive() {
        return false;
    }

    /**
     * Retrieves the detached state object for this entity.
     *
     * This method is part of the PersistenceCapable interface and returns the detached
     * state information maintained by OpenJPA for detached entity management. The state
     * may be null, DESERIALIZED, or contain version information for optimistic locking.
     *
     * @return Object the detached state information, or null if not set
     */
    public Object pcGetDetachedState() {
        return this.pcDetachedState;
    }

    /**
     * Sets the detached state object for this entity.
     *
     * This method is part of the PersistenceCapable interface and is called by OpenJPA
     * to establish or update the detached state information for this entity. This state
     * is used to track entity versions and manage reattachment to persistence contexts.
     *
     * @param pcDetachedState Object the detached state information to set
     */
    public void pcSetDetachedState(final Object pcDetachedState) {
        this.pcDetachedState = pcDetachedState;
    }
    
    private void writeObject(final ObjectOutputStream objectOutputStream) throws IOException {
        final boolean pcSerializing = this.pcSerializing();
        objectOutputStream.defaultWriteObject();
        if (pcSerializing) {
            this.pcSetDetachedState(null);
        }
    }
    
    private void readObject(final ObjectInputStream objectInputStream) throws IOException, ClassNotFoundException {
        this.pcSetDetachedState(PersistenceCapable.DESERIALIZED);
        objectInputStream.defaultReadObject();
    }
}
