package ca.openosp.openo.caisi_integrator.dao;

import java.io.ObjectInputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import org.apache.openjpa.util.IntId;
import org.apache.openjpa.enhance.FieldConsumer;
import org.apache.openjpa.util.InternalException;
import org.apache.openjpa.enhance.FieldSupplier;
import org.apache.openjpa.enhance.RedefinitionHelper;
import org.apache.openjpa.enhance.PersistenceCapable;
import org.apache.openjpa.enhance.PCRegistry;
import java.util.Arrays;
import ca.openosp.openo.caisi_integrator.util.EncryptionUtils;
import ca.openosp.openo.caisi_integrator.util.MiscUtils;
import org.apache.openjpa.enhance.StateManager;
import javax.persistence.TemporalType;
import javax.persistence.Temporal;
import java.util.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.persistence.Column;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Entity;
import ca.openosp.openo.caisi_integrator.util.Named;

/**
 * Represents a user account for accessing the CAISI Integrator system across multiple OpenO EMR sites.
 *
 * <p>This entity manages user authentication and access control for the CAISI (Client Access to Integrated Services and Information)
 * Integrator, which enables data sharing and integration between multiple OpenO EMR installations. Each SiteUser can access
 * patient records and clinical data across federated healthcare sites within the integrator network.</p>
 *
 * <p>The class is enhanced by Apache OpenJPA for persistence capabilities and uses legacy SHA-1
 * password hashing. User accounts can be disabled to prevent access without deletion, and track
 * last login timestamps for auditing purposes.</p>
 *
 * <p><strong>Security Considerations:</strong></p>
 * <ul>
 *   <li>Passwords are automatically hashed using SHA-1 via {@link EncryptionUtils}</li>
 *   <li>Usernames are validated and normalized through {@link MiscUtils#validateAndNormaliseUserName(String)}</li>
 *   <li>Accounts can be disabled without data loss through the disabled flag</li>
 *   <li>Last login tracking supports audit requirements for healthcare data access</li>
 * </ul>
 *
 * @see AbstractModel
 * @see Named
 * @see ca.openosp.openo.caisi_integrator.util.EncryptionUtils
 * @see ca.openosp.openo.caisi_integrator.util.MiscUtils
 * @since 2026-01-24
 */
@Entity
public class SiteUser extends AbstractModel<Integer> implements Named, PersistenceCapable
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    @Column(nullable = false, length = 32, unique = true)
    private String name;
    @Column(nullable = false, columnDefinition = "tinyblob")
    private byte[] password;
    @Temporal(TemporalType.TIMESTAMP)
    private Calendar lastLogin;
    @Column(nullable = false, columnDefinition = "tinyint(1)")
    private boolean disabled;
    private static int pcInheritedFieldCount;
    private static String[] pcFieldNames;
    private static Class[] pcFieldTypes;
    private static byte[] pcFieldFlags;
    private static Class pcPCSuperclass;
    protected transient StateManager pcStateManager;
    static /* synthetic */ Class class$Ljava$lang$Integer;
    static /* synthetic */ Class class$Ljava$util$Calendar;
    static /* synthetic */ Class class$Ljava$lang$String;
    static /* synthetic */ Class class$L$B;
    static /* synthetic */ Class class$Lca$openosp$openo$caisi_integrator$dao$SiteUser;
    private transient Object pcDetachedState;
    private static final long serialVersionUID;

    /**
     * Constructs a new SiteUser instance with default values.
     *
     * <p>Initializes a new user account with:</p>
     * <ul>
     *   <li>No ID (null) - will be auto-generated upon persistence</li>
     *   <li>No username (null) - must be set via {@link #setName(String)}</li>
     *   <li>No password (null) - must be set via {@link #setPassword(String)}</li>
     *   <li>No last login timestamp (null)</li>
     *   <li>Enabled status (disabled = false)</li>
     * </ul>
     *
     * <p>This constructor is primarily used by JPA/OpenJPA for entity instantiation.
     * After construction, the username and password should be set before persisting the entity.</p>
     */
    public SiteUser() {
        this.id = null;
        this.name = null;
        this.password = null;
        this.lastLogin = null;
        this.disabled = false;
    }

    /**
     * Retrieves the unique identifier for this site user.
     *
     * <p>The ID is auto-generated by the database upon first persistence and serves as the primary key
     * for this entity. The value is null for transient (unsaved) instances and assigned automatically
     * when the entity is persisted to the database.</p>
     *
     * <p>This method is OpenJPA-enhanced and routes through the persistence state manager for proper
     * field access tracking and dirty checking.</p>
     *
     * @return Integer the unique database identifier, or null if not yet persisted
     */
    @Override
    public Integer getId() {
        return pcGetid(this);
    }

    /**
     * Retrieves the username for this site user account.
     *
     * <p>The username is a unique identifier (maximum 32 characters) used for authentication across
     * the CAISI Integrator network. Usernames are validated and normalized when set to ensure consistency
     * in the system.</p>
     *
     * <p>This method is OpenJPA-enhanced and routes through the persistence state manager for proper
     * field access tracking.</p>
     *
     * @return String the username, or null if not set
     */
    public String getName() {
        return pcGetname(this);
    }

    /**
     * Sets the username for this site user account with validation and normalization.
     *
     * <p>The provided username is automatically validated and normalized through
     * {@link MiscUtils#validateAndNormaliseUserName(String)} before being stored. This ensures
     * consistent username format across the CAISI Integrator system.</p>
     *
     * <p>Username requirements:</p>
     * <ul>
     *   <li>Maximum length: 32 characters (enforced by database constraint)</li>
     *   <li>Must be unique across all site users (enforced by database constraint)</li>
     *   <li>Automatically normalized to consistent format</li>
     * </ul>
     *
     * <p>This method is OpenJPA-enhanced and routes through the persistence state manager for proper
     * field modification tracking and change detection.</p>
     *
     * @param name String the username to set (will be validated and normalized)
     * @throws IllegalArgumentException if the username fails validation in MiscUtils
     */
    public void setName(final String name) {
        pcSetname(this, MiscUtils.validateAndNormaliseUserName(name));
    }

    /**
     * Sets the password for this site user account with automatic SHA-1 hashing.
     *
     * <p>The provided password is automatically hashed using SHA-1 via {@link EncryptionUtils#getSha1(String)}
     * before being stored in the database. The plaintext password is never stored, only the hash value.</p>
     *
     * <p><strong>Security Notes:</strong></p>
     * <ul>
     *   <li>Password is hashed using SHA-1 before storage</li>
     *   <li>The hashed value is stored as a byte array (tinyblob in database)</li>
     *   <li>Plaintext password is never persisted</li>
     *   <li>Use {@link #checkPassword(String)} to verify passwords during authentication</li>
     * </ul>
     *
     * <p>This method is OpenJPA-enhanced and routes through the persistence state manager for proper
     * field modification tracking.</p>
     *
     * @param password String the plaintext password to hash and store
     * @throws IllegalArgumentException if password is null
     * @see #checkPassword(String)
     * @see EncryptionUtils#getSha1(String)
     */
    public void setPassword(final String password) {
        if (password == null) {
            throw new IllegalArgumentException("password can't be null");
        }
        pcSetpassword(this, EncryptionUtils.getSha1(password));
    }

    /**
     * Verifies if the provided password matches the stored password hash.
     *
     * <p>This method performs password authentication by comparing the provided plaintext password
     * against the stored hash. It supports two comparison modes for backward compatibility:</p>
     * <ol>
     *   <li>Direct byte comparison (for legacy plaintext passwords)</li>
     *   <li>SHA-1 hash comparison (for properly hashed passwords)</li>
     * </ol>
     *
     * <p><strong>Authentication Logic:</strong></p>
     * <ul>
     *   <li>Returns false immediately if provided password is null</li>
     *   <li>Checks if stored password matches plaintext bytes (legacy support)</li>
     *   <li>If not, hashes provided password and compares with stored hash</li>
     *   <li>Returns true if either comparison succeeds</li>
     * </ul>
     *
     * <p>This method is OpenJPA-enhanced and routes through the persistence state manager for proper
     * field access tracking.</p>
     *
     * @param password String the plaintext password to verify
     * @return boolean true if the password matches the stored hash, false otherwise
     * @see #setPassword(String)
     * @see EncryptionUtils#getSha1(String)
     */
    public boolean checkPassword(final String password) {
        return password != null && (Arrays.equals(pcGetpassword(this), password.getBytes()) || Arrays.equals(pcGetpassword(this), EncryptionUtils.getSha1(password)));
    }

    /**
     * Retrieves the timestamp of the user's last successful login.
     *
     * <p>This field tracks the most recent authentication timestamp for audit and security purposes.
     * It is stored as a TIMESTAMP in the database and can be used to:</p>
     * <ul>
     *   <li>Display last login information to users</li>
     *   <li>Identify inactive accounts for security reviews</li>
     *   <li>Support audit trails for healthcare data access compliance</li>
     *   <li>Detect unusual access patterns</li>
     * </ul>
     *
     * <p>This method is OpenJPA-enhanced and routes through the persistence state manager for proper
     * field access tracking.</p>
     *
     * @return Calendar the last login timestamp, or null if the user has never logged in
     */
    public Calendar getLastLogin() {
        return pcGetlastLogin(this);
    }

    /**
     * Sets the timestamp of the user's last successful login.
     *
     * <p>This method should be called during the authentication process to record when the user
     * successfully logged into the CAISI Integrator system. The timestamp is used for security
     * auditing and compliance with healthcare data access regulations.</p>
     *
     * <p>Typical usage is to set this value to the current time upon successful authentication:</p>
     * <pre>
     * user.setLastLogin(Calendar.getInstance());
     * </pre>
     *
     * <p>This method is OpenJPA-enhanced and routes through the persistence state manager for proper
     * field modification tracking and change detection.</p>
     *
     * @param lastLogin Calendar the login timestamp to record, or null to clear
     */
    public void setLastLogin(final Calendar lastLogin) {
        pcSetlastLogin(this, lastLogin);
    }

    /**
     * Checks whether this user account is disabled.
     *
     * <p>Disabled accounts cannot authenticate or access the CAISI Integrator system. This provides
     * a way to revoke access without deleting the user record, preserving audit history and
     * relationships in the database.</p>
     *
     * <p>Common reasons for disabling accounts:</p>
     * <ul>
     *   <li>Employee termination or role change</li>
     *   <li>Temporary suspension pending investigation</li>
     *   <li>Account security concerns</li>
     *   <li>Inactive accounts being archived</li>
     * </ul>
     *
     * <p>This method is OpenJPA-enhanced and routes through the persistence state manager for proper
     * field access tracking.</p>
     *
     * @return boolean true if the account is disabled and cannot authenticate, false if active
     */
    public boolean isDisabled() {
        return pcGetdisabled(this);
    }

    /**
     * Sets whether this user account is disabled.
     *
     * <p>Setting this value to true prevents the user from authenticating or accessing the CAISI
     * Integrator system while preserving their account data and audit history. Setting it to false
     * re-enables a previously disabled account.</p>
     *
     * <p>This is the preferred method for revoking access compared to deleting the user record,
     * as it maintains referential integrity and audit trails required for healthcare compliance.</p>
     *
     * <p>This method is OpenJPA-enhanced and routes through the persistence state manager for proper
     * field modification tracking and change detection.</p>
     *
     * @param disabled boolean true to disable the account, false to enable it
     */
    public void setDisabled(final boolean disabled) {
        pcSetdisabled(this, disabled);
    }

    /**
     * Returns the OpenJPA enhancement contract version for this persistence-capable class.
     *
     * <p>This method is part of the OpenJPA {@link PersistenceCapable} interface and indicates
     * which version of the bytecode enhancement contract this class implements. The value 2
     * represents the current enhancement contract version used by OpenJPA.</p>
     *
     * <p>This method is automatically invoked by the OpenJPA runtime and should not be called
     * directly by application code.</p>
     *
     * @return int the enhancement contract version (always 2 for this implementation)
     */
    public int pcGetEnhancementContractVersion() {
        return 2;
    }
    
    static {
        serialVersionUID = 8746124247439157163L;
        SiteUser.pcFieldNames = new String[] { "disabled", "id", "lastLogin", "name", "password" };
        SiteUser.pcFieldTypes = new Class[] { Boolean.TYPE, (SiteUser.class$Ljava$lang$Integer != null) ? SiteUser.class$Ljava$lang$Integer : (SiteUser.class$Ljava$lang$Integer = class$("java.lang.Integer")), (SiteUser.class$Ljava$util$Calendar != null) ? SiteUser.class$Ljava$util$Calendar : (SiteUser.class$Ljava$util$Calendar = class$("java.util.Calendar")), (SiteUser.class$Ljava$lang$String != null) ? SiteUser.class$Ljava$lang$String : (SiteUser.class$Ljava$lang$String = class$("java.lang.String")), (SiteUser.class$L$B != null) ? SiteUser.class$L$B : (SiteUser.class$L$B = class$("[B")) };
        SiteUser.pcFieldFlags = new byte[] { 26, 26, 26, 26, 26 };
        PCRegistry.register((SiteUser.class$Lca$openosp$openo$caisi_integrator$dao$SiteUser != null) ? SiteUser.class$Lca$openosp$openo$caisi_integrator$dao$SiteUser : (SiteUser.class$Lca$openosp$openo$caisi_integrator$dao$SiteUser = class$("ca.openosp.openo.caisi_integrator.dao.SiteUser")), SiteUser.pcFieldNames, SiteUser.pcFieldTypes, SiteUser.pcFieldFlags, SiteUser.pcPCSuperclass, "SiteUser", (PersistenceCapable)new SiteUser());
    }
    
    static /* synthetic */ Class class$(final String className) {
        try {
            return Class.forName(className);
        }
        catch (final ClassNotFoundException ex) {
            throw new NoClassDefFoundError(ex.getMessage());
        }
    }
    
    protected void pcClearFields() {
        this.disabled = false;
        this.id = null;
        this.lastLogin = null;
        this.name = null;
        this.password = null;
    }

    /**
     * Creates a new instance of SiteUser with the specified state manager and object ID.
     *
     * <p>This method is part of the OpenJPA {@link PersistenceCapable} interface and is used by
     * the OpenJPA runtime to instantiate entity objects during query execution and object retrieval.
     * It creates a new instance, optionally clears its fields, assigns the state manager, and
     * copies the primary key from the provided object ID.</p>
     *
     * <p>This method is automatically invoked by the OpenJPA runtime and should not be called
     * directly by application code.</p>
     *
     * @param pcStateManager StateManager the OpenJPA state manager to manage this instance
     * @param o Object the object ID containing the primary key value
     * @param b boolean true to clear all fields to default values, false to leave as-is
     * @return PersistenceCapable a new SiteUser instance with the specified configuration
     */
    public PersistenceCapable pcNewInstance(final StateManager pcStateManager, final Object o, final boolean b) {
        final SiteUser siteUser = new SiteUser();
        if (b) {
            siteUser.pcClearFields();
        }
        siteUser.pcStateManager = pcStateManager;
        siteUser.pcCopyKeyFieldsFromObjectId(o);
        return (PersistenceCapable)siteUser;
    }

    /**
     * Creates a new instance of SiteUser with the specified state manager.
     *
     * <p>This method is part of the OpenJPA {@link PersistenceCapable} interface and is used by
     * the OpenJPA runtime to instantiate entity objects. It creates a new instance, optionally
     * clears its fields, and assigns the state manager. This variant does not initialize the
     * primary key from an object ID.</p>
     *
     * <p>This method is automatically invoked by the OpenJPA runtime and should not be called
     * directly by application code.</p>
     *
     * @param pcStateManager StateManager the OpenJPA state manager to manage this instance
     * @param b boolean true to clear all fields to default values, false to leave as-is
     * @return PersistenceCapable a new SiteUser instance with the specified configuration
     */
    public PersistenceCapable pcNewInstance(final StateManager pcStateManager, final boolean b) {
        final SiteUser siteUser = new SiteUser();
        if (b) {
            siteUser.pcClearFields();
        }
        siteUser.pcStateManager = pcStateManager;
        return (PersistenceCapable)siteUser;
    }
    
    protected static int pcGetManagedFieldCount() {
        return 5;
    }
    
    public void pcReplaceField(final int n) {
        final int n2 = n - SiteUser.pcInheritedFieldCount;
        if (n2 < 0) {
            throw new IllegalArgumentException();
        }
        switch (n2) {
            case 0: {
                this.disabled = this.pcStateManager.replaceBooleanField((PersistenceCapable)this, n);
                return;
            }
            case 1: {
                this.id = (Integer)this.pcStateManager.replaceObjectField((PersistenceCapable)this, n);
                return;
            }
            case 2: {
                this.lastLogin = (Calendar)this.pcStateManager.replaceObjectField((PersistenceCapable)this, n);
                return;
            }
            case 3: {
                this.name = this.pcStateManager.replaceStringField((PersistenceCapable)this, n);
                return;
            }
            case 4: {
                this.password = (byte[])this.pcStateManager.replaceObjectField((PersistenceCapable)this, n);
                return;
            }
            default: {
                throw new IllegalArgumentException();
            }
        }
    }
    
    public void pcReplaceFields(final int[] array) {
        for (int i = 0; i < array.length; ++i) {
            this.pcReplaceField(array[i]);
        }
    }
    
    public void pcProvideField(final int n) {
        final int n2 = n - SiteUser.pcInheritedFieldCount;
        if (n2 < 0) {
            throw new IllegalArgumentException();
        }
        switch (n2) {
            case 0: {
                this.pcStateManager.providedBooleanField((PersistenceCapable)this, n, this.disabled);
                return;
            }
            case 1: {
                this.pcStateManager.providedObjectField((PersistenceCapable)this, n, (Object)this.id);
                return;
            }
            case 2: {
                this.pcStateManager.providedObjectField((PersistenceCapable)this, n, (Object)this.lastLogin);
                return;
            }
            case 3: {
                this.pcStateManager.providedStringField((PersistenceCapable)this, n, this.name);
                return;
            }
            case 4: {
                this.pcStateManager.providedObjectField((PersistenceCapable)this, n, (Object)this.password);
                return;
            }
            default: {
                throw new IllegalArgumentException();
            }
        }
    }
    
    public void pcProvideFields(final int[] array) {
        for (int i = 0; i < array.length; ++i) {
            this.pcProvideField(array[i]);
        }
    }
    
    protected void pcCopyField(final SiteUser siteUser, final int n) {
        final int n2 = n - SiteUser.pcInheritedFieldCount;
        if (n2 < 0) {
            throw new IllegalArgumentException();
        }
        switch (n2) {
            case 0: {
                this.disabled = siteUser.disabled;
                return;
            }
            case 1: {
                this.id = siteUser.id;
                return;
            }
            case 2: {
                this.lastLogin = siteUser.lastLogin;
                return;
            }
            case 3: {
                this.name = siteUser.name;
                return;
            }
            case 4: {
                this.password = siteUser.password;
                return;
            }
            default: {
                throw new IllegalArgumentException();
            }
        }
    }
    
    public void pcCopyFields(final Object o, final int[] array) {
        final SiteUser siteUser = (SiteUser)o;
        if (siteUser.pcStateManager != this.pcStateManager) {
            throw new IllegalArgumentException();
        }
        if (this.pcStateManager == null) {
            throw new IllegalStateException();
        }
        for (int i = 0; i < array.length; ++i) {
            this.pcCopyField(siteUser, array[i]);
        }
    }
    
    public Object pcGetGenericContext() {
        if (this.pcStateManager == null) {
            return null;
        }
        return this.pcStateManager.getGenericContext();
    }
    
    public Object pcFetchObjectId() {
        if (this.pcStateManager == null) {
            return null;
        }
        return this.pcStateManager.fetchObjectId();
    }

    /**
     * Checks whether this entity instance has been marked for deletion.
     *
     * <p>This method is part of the OpenJPA {@link PersistenceCapable} interface and indicates
     * whether this instance has been deleted in the current transaction context. Returns true
     * if the entity has been marked for deletion but the transaction has not yet been committed.</p>
     *
     * @return boolean true if this entity is deleted, false otherwise
     */
    public boolean pcIsDeleted() {
        return this.pcStateManager != null && this.pcStateManager.isDeleted();
    }

    /**
     * Checks whether this entity instance has uncommitted changes.
     *
     * <p>This method is part of the OpenJPA {@link PersistenceCapable} interface and indicates
     * whether this instance has been modified since it was loaded or last committed. Returns true
     * if any fields have been changed but not yet persisted to the database.</p>
     *
     * <p>The method performs a dirty check via {@link RedefinitionHelper} before returning the
     * state to ensure accuracy.</p>
     *
     * @return boolean true if this entity has uncommitted changes, false otherwise
     */
    public boolean pcIsDirty() {
        if (this.pcStateManager == null) {
            return false;
        }
        final StateManager pcStateManager = this.pcStateManager;
        RedefinitionHelper.dirtyCheck(pcStateManager);
        return pcStateManager.isDirty();
    }

    /**
     * Checks whether this entity instance is newly created and not yet persisted.
     *
     * <p>This method is part of the OpenJPA {@link PersistenceCapable} interface and indicates
     * whether this instance was created in the current transaction but has not yet been committed
     * to the database. Returns true for new entities that will be inserted on transaction commit.</p>
     *
     * @return boolean true if this is a new, unpersisted entity, false otherwise
     */
    public boolean pcIsNew() {
        return this.pcStateManager != null && this.pcStateManager.isNew();
    }

    /**
     * Checks whether this entity instance is managed by a persistence context.
     *
     * <p>This method is part of the OpenJPA {@link PersistenceCapable} interface and indicates
     * whether this instance is in a persistent state (either newly created within a transaction,
     * loaded from the database, or previously persisted). Transient instances that have never
     * been associated with a persistence context will return false.</p>
     *
     * @return boolean true if this entity is persistent, false if transient
     */
    public boolean pcIsPersistent() {
        return this.pcStateManager != null && this.pcStateManager.isPersistent();
    }

    /**
     * Checks whether this entity instance is associated with an active transaction.
     *
     * <p>This method is part of the OpenJPA {@link PersistenceCapable} interface and indicates
     * whether this instance is currently participating in a transaction context. Returns true
     * for instances that are within a transaction boundary.</p>
     *
     * @return boolean true if this entity is transactional, false otherwise
     */
    public boolean pcIsTransactional() {
        return this.pcStateManager != null && this.pcStateManager.isTransactional();
    }
    
    public boolean pcSerializing() {
        return this.pcStateManager != null && this.pcStateManager.serializing();
    }
    
    public void pcDirty(final String s) {
        if (this.pcStateManager == null) {
            return;
        }
        this.pcStateManager.dirty(s);
    }
    
    public StateManager pcGetStateManager() {
        return this.pcStateManager;
    }
    
    public Object pcGetVersion() {
        if (this.pcStateManager == null) {
            return null;
        }
        return this.pcStateManager.getVersion();
    }
    
    public void pcReplaceStateManager(final StateManager pcStateManager) throws SecurityException {
        if (this.pcStateManager != null) {
            this.pcStateManager = this.pcStateManager.replaceStateManager(pcStateManager);
            return;
        }
        this.pcStateManager = pcStateManager;
    }
    
    public void pcCopyKeyFieldsToObjectId(final FieldSupplier fieldSupplier, final Object o) {
        throw new InternalException();
    }
    
    public void pcCopyKeyFieldsToObjectId(final Object o) {
        throw new InternalException();
    }
    
    public void pcCopyKeyFieldsFromObjectId(final FieldConsumer fieldConsumer, final Object o) {
        fieldConsumer.storeObjectField(1 + SiteUser.pcInheritedFieldCount, (Object)Integer.valueOf(((IntId)o).getId()));
    }
    
    public void pcCopyKeyFieldsFromObjectId(final Object o) {
        this.id = Integer.valueOf(((IntId)o).getId());
    }
    
    public Object pcNewObjectIdInstance(final Object o) {
        return new IntId((SiteUser.class$Lca$openosp$openo$caisi_integrator$dao$SiteUser != null) ? SiteUser.class$Lca$openosp$openo$caisi_integrator$dao$SiteUser : (SiteUser.class$Lca$openosp$openo$caisi_integrator$dao$SiteUser = class$("ca.openosp.openo.caisi_integrator.dao.SiteUser")), (String)o);
    }
    
    public Object pcNewObjectIdInstance() {
        return new IntId((SiteUser.class$Lca$openosp$openo$caisi_integrator$dao$SiteUser != null) ? SiteUser.class$Lca$openosp$openo$caisi_integrator$dao$SiteUser : (SiteUser.class$Lca$openosp$openo$caisi_integrator$dao$SiteUser = class$("ca.openosp.openo.caisi_integrator.dao.SiteUser")), this.id);
    }
    
    private static final boolean pcGetdisabled(final SiteUser siteUser) {
        if (siteUser.pcStateManager == null) {
            return siteUser.disabled;
        }
        siteUser.pcStateManager.accessingField(SiteUser.pcInheritedFieldCount + 0);
        return siteUser.disabled;
    }
    
    private static final void pcSetdisabled(final SiteUser siteUser, final boolean disabled) {
        if (siteUser.pcStateManager == null) {
            siteUser.disabled = disabled;
            return;
        }
        siteUser.pcStateManager.settingBooleanField((PersistenceCapable)siteUser, SiteUser.pcInheritedFieldCount + 0, siteUser.disabled, disabled, 0);
    }
    
    private static final Integer pcGetid(final SiteUser siteUser) {
        if (siteUser.pcStateManager == null) {
            return siteUser.id;
        }
        siteUser.pcStateManager.accessingField(SiteUser.pcInheritedFieldCount + 1);
        return siteUser.id;
    }
    
    private static final void pcSetid(final SiteUser siteUser, final Integer id) {
        if (siteUser.pcStateManager == null) {
            siteUser.id = id;
            return;
        }
        siteUser.pcStateManager.settingObjectField((PersistenceCapable)siteUser, SiteUser.pcInheritedFieldCount + 1, (Object)siteUser.id, (Object)id, 0);
    }
    
    private static final Calendar pcGetlastLogin(final SiteUser siteUser) {
        if (siteUser.pcStateManager == null) {
            return siteUser.lastLogin;
        }
        siteUser.pcStateManager.accessingField(SiteUser.pcInheritedFieldCount + 2);
        return siteUser.lastLogin;
    }
    
    private static final void pcSetlastLogin(final SiteUser siteUser, final Calendar lastLogin) {
        if (siteUser.pcStateManager == null) {
            siteUser.lastLogin = lastLogin;
            return;
        }
        siteUser.pcStateManager.settingObjectField((PersistenceCapable)siteUser, SiteUser.pcInheritedFieldCount + 2, (Object)siteUser.lastLogin, (Object)lastLogin, 0);
    }
    
    private static final String pcGetname(final SiteUser siteUser) {
        if (siteUser.pcStateManager == null) {
            return siteUser.name;
        }
        siteUser.pcStateManager.accessingField(SiteUser.pcInheritedFieldCount + 3);
        return siteUser.name;
    }
    
    private static final void pcSetname(final SiteUser siteUser, final String name) {
        if (siteUser.pcStateManager == null) {
            siteUser.name = name;
            return;
        }
        siteUser.pcStateManager.settingStringField((PersistenceCapable)siteUser, SiteUser.pcInheritedFieldCount + 3, siteUser.name, name, 0);
    }
    
    private static final byte[] pcGetpassword(final SiteUser siteUser) {
        if (siteUser.pcStateManager == null) {
            return siteUser.password;
        }
        siteUser.pcStateManager.accessingField(SiteUser.pcInheritedFieldCount + 4);
        return siteUser.password;
    }
    
    private static final void pcSetpassword(final SiteUser siteUser, final byte[] password) {
        if (siteUser.pcStateManager == null) {
            siteUser.password = password;
            return;
        }
        siteUser.pcStateManager.settingObjectField((PersistenceCapable)siteUser, SiteUser.pcInheritedFieldCount + 4, (Object)siteUser.password, (Object)password, 0);
    }

    /**
     * Checks whether this entity instance is in a detached state.
     *
     * <p>This method is part of the OpenJPA {@link PersistenceCapable} interface and determines
     * whether this instance is detached from its persistence context. A detached entity was
     * previously managed but is no longer associated with an active persistence context.</p>
     *
     * <p>The detection logic follows these rules:</p>
     * <ul>
     *   <li>If a state manager is present, delegate to its detachment status</li>
     *   <li>If detached state is set (and not DESERIALIZED), return true</li>
     *   <li>If an ID is present without a state manager, assume detached</li>
     *   <li>Returns null if the detachment state cannot be definitively determined</li>
     * </ul>
     *
     * @return Boolean true if detached, false if attached, null if indeterminate
     */
    public Boolean pcIsDetached() {
        if (this.pcStateManager != null) {
            if (this.pcStateManager.isDetached()) {
                return Boolean.TRUE;
            }
            return Boolean.FALSE;
        }
        else {
            if (this.pcGetDetachedState() != null && this.pcGetDetachedState() != PersistenceCapable.DESERIALIZED) {
                return Boolean.TRUE;
            }
            if (this.id != null) {
                return Boolean.TRUE;
            }
            if (!this.pcisDetachedStateDefinitive()) {
                return null;
            }
            if (this.pcGetDetachedState() == null) {
                return Boolean.FALSE;
            }
            return null;
        }
    }
    
    private boolean pcisDetachedStateDefinitive() {
        return false;
    }
    
    public Object pcGetDetachedState() {
        return this.pcDetachedState;
    }
    
    public void pcSetDetachedState(final Object pcDetachedState) {
        this.pcDetachedState = pcDetachedState;
    }
    
    private void writeObject(final ObjectOutputStream objectOutputStream) throws IOException {
        final boolean pcSerializing = this.pcSerializing();
        objectOutputStream.defaultWriteObject();
        if (pcSerializing) {
            this.pcSetDetachedState(null);
        }
    }
    
    private void readObject(final ObjectInputStream objectInputStream) throws IOException, ClassNotFoundException {
        this.pcSetDetachedState(PersistenceCapable.DESERIALIZED);
        objectInputStream.defaultReadObject();
    }
}
