package ca.openosp.openo.email.core;

import ca.openosp.openo.commn.model.EmailLog;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Pins down the split between what a patient receives and what lands in their chart.
 *
 * <p>The footer is boilerplate generated by the email compose eForm: a clinic signature,
 * an unsubscribe line, a legal disclaimer. It belongs at the bottom of the email the patient
 * receives, and nowhere near the clinical note. Before the footer had a field of its own the
 * eForm concatenated it into the body, so the one body string was both transmitted and charted,
 * and the boilerplate ended up in the chart.</p>
 *
 * <p>Two invariants keep that from happening again:</p>
 * <ul>
 *   <li>{@link EmailData#getBodyWithFooter()} is what {@link EmailSender} transmits, and it ends
 *       with the footer</li>
 *   <li>{@link EmailData#getBody()} is what is written to {@link EmailLog}, and the chart note is
 *       built from that, so it must stay free of the footer</li>
 * </ul>
 */
@DisplayName("Email footer stays out of the chart note")
@Tag("unit")
@Tag("fast")
@Tag("email")
class EmailFooterUnitTest {

    private static final String BODY = "Your lab results are attached.";
    private static final String FOOTER = "Riverdale Family Health\nReply STOP to unsubscribe.";

    @Nested
    @DisplayName("EmailData.getBodyWithFooter")
    class BodyWithFooter {

        @Test
        @DisplayName("should return body only when footer was never set")
        void shouldReturnBodyOnly_whenFooterNotSet() {
            EmailData emailData = new EmailData();
            emailData.setBody(BODY);

            assertThat(emailData.getBodyWithFooter()).isEqualTo(BODY);
        }

        @Test
        @DisplayName("should return body only when footer is empty")
        void shouldReturnBodyOnly_whenFooterIsEmpty() {
            EmailData emailData = new EmailData();
            emailData.setBody(BODY);
            emailData.setFooter("");

            assertThat(emailData.getBodyWithFooter()).isEqualTo(BODY);
        }

        @Test
        @DisplayName("should return body only when footer is set to null")
        void shouldReturnBodyOnly_whenFooterIsNull() {
            EmailData emailData = new EmailData();
            emailData.setBody(BODY);
            emailData.setFooter(null);

            assertThat(emailData.getFooter()).isEmpty();
            assertThat(emailData.getBodyWithFooter()).isEqualTo(BODY);
        }

        @Test
        @DisplayName("should append footer below body separated by a blank line")
        void shouldAppendFooterBelowBody_whenFooterSet() {
            EmailData emailData = new EmailData();
            emailData.setBody(BODY);
            emailData.setFooter(FOOTER);

            assertThat(emailData.getBodyWithFooter()).isEqualTo(BODY + "\n\n" + FOOTER);
        }

        @Test
        @DisplayName("should trim footer whitespace so the email does not end in blank lines")
        void shouldTrimFooter_whenFooterHasSurroundingWhitespace() {
            EmailData emailData = new EmailData();
            emailData.setBody(BODY);
            emailData.setFooter("\n\n  " + FOOTER + "  \n\n");

            assertThat(emailData.getBodyWithFooter()).isEqualTo(BODY + "\n\n" + FOOTER);
        }

        @Test
        @DisplayName("should leave the charted body untouched when a footer is appended")
        void shouldLeaveBodyUnchanged_whenFooterAppended() {
            EmailData emailData = new EmailData();
            emailData.setBody(BODY);
            emailData.setFooter(FOOTER);

            emailData.getBodyWithFooter();

            assertThat(emailData.getBody()).isEqualTo(BODY).doesNotContain(FOOTER);
        }
    }

    @Nested
    @DisplayName("EmailLog.getFooter")
    class LogFooter {

        @Test
        @DisplayName("should return empty string for rows written before the footer column existed")
        void shouldReturnEmptyString_whenFooterNeverSet() {
            assertThat(new EmailLog().getFooter()).isEmpty();
        }

        @Test
        @DisplayName("should return empty string when footer is set to null")
        void shouldReturnEmptyString_whenFooterIsNull() {
            EmailLog emailLog = new EmailLog();
            emailLog.setFooter(null);

            assertThat(emailLog.getFooter()).isEmpty();
        }

        @Test
        @DisplayName("should round trip the footer through Base64 storage")
        void shouldRoundTripFooter_whenFooterSet() {
            EmailLog emailLog = new EmailLog();
            emailLog.setFooter(FOOTER);

            assertThat(emailLog.getFooter()).isEqualTo(FOOTER);
        }

        @Test
        @DisplayName("should round trip accented characters through Base64 storage")
        void shouldRoundTripFooter_whenFooterHasNonAsciiCharacters() {
            String accentedFooter = "Clinique de santé familiale — répondre ARRÊT";
            EmailLog emailLog = new EmailLog();
            emailLog.setFooter(accentedFooter);

            assertThat(emailLog.getFooter()).isEqualTo(accentedFooter);
        }
    }
}
