services:
  open-o:
    container_name: openo-tomcat-dev
    build:
      context: ./development
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "18000:8000"
    volumes:
      - m2-volume:/root/.m2
      - ..:/workspace:cached 
      - ../.devcontainer/db/db_data/:/db-data/
    env_file:
      - ./development/config/shared/local.env
    environment:
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      TZ: America/Toronto
    networks:
      - open-o-network
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: openo-mariadb-dev
    build:
      context: ../
      dockerfile: .devcontainer/db/Dockerfile
    env_file:
      - ./development/config/shared/local.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb-files:/var/lib/mysql
    environment:
      TZ: America/Toronto
      container: docker
    networks:
      - open-o-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 60s

volumes:
  mariadb-files:
    driver: local

  m2-volume:
    driver: local

networks:
  open-o-network:
    driver: bridge
    name: open-o-network
