package ca.openosp.openo.ar2005;

import org.apache.xmlbeans.xml.stream.XMLStreamException;
import org.apache.xmlbeans.xml.stream.XMLInputStream;
import org.w3c.dom.Node;
import javax.xml.stream.XMLStreamReader;
import java.io.Reader;
import java.io.InputStream;
import java.net.URL;
import java.io.IOException;
import java.io.File;
import org.apache.xmlbeans.XmlException;
import org.apache.xmlbeans.XmlOptions;
import org.apache.xmlbeans.XmlBeans;
import org.apache.xmlbeans.XmlString;
import org.apache.xmlbeans.XmlDate;
import java.util.Calendar;
import org.apache.xmlbeans.SchemaType;
import org.apache.xmlbeans.XmlObject;

/**
 * Represents ultrasound examination data for the Antenatal Record 2005 (AR2005) system.
 *
 * This interface provides methods to manage ultrasound examination information including
 * the examination date, gestational age (GA), and results. It is part of the British Columbia
 * Antenatal Record (BCAR) forms used for pregnancy care tracking in the OpenO EMR system.
 *
 * The interface is generated by Apache XMLBeans and provides both high-level property
 * accessors (getters/setters) and low-level XML type accessors (xget/xset) for fine-grained
 * control over the underlying XML representation.
 *
 * @see XmlObject
 * @see ca.openosp.openo.ar2005
 * @since 2026-01-23
 */
public interface UltrasoundType extends XmlObject
{
    public static final SchemaType type = (SchemaType)XmlBeans.typeSystemForClassLoader(UltrasoundType.class.getClassLoader(), "schemaorg_apache_xmlbeans.system.s9C023B7D67311A3187802DA7FD51EA38").resolveHandle("ultrasoundtype4a74type");

    /**
     * Gets the date of the ultrasound examination.
     *
     * @return Calendar the ultrasound examination date
     */
    Calendar getDate();

    /**
     * Gets the date of the ultrasound examination as an XML date type.
     *
     * This method provides low-level access to the underlying XML representation
     * of the date field for fine-grained control over XML processing.
     *
     * @return XmlDate the ultrasound examination date as XML type
     */
    XmlDate xgetDate();

    /**
     * Sets the date of the ultrasound examination.
     *
     * @param p0 Calendar the ultrasound examination date to set
     */
    void setDate(final Calendar p0);

    /**
     * Sets the date of the ultrasound examination using an XML date type.
     *
     * This method provides low-level access to set the underlying XML representation
     * of the date field for fine-grained control over XML processing.
     *
     * @param p0 XmlDate the ultrasound examination date to set as XML type
     */
    void xsetDate(final XmlDate p0);

    /**
     * Gets the gestational age (GA) at the time of the ultrasound examination.
     *
     * @return String the gestational age value
     */
    String getGa();

    /**
     * Gets the gestational age (GA) as an XML string type.
     *
     * This method provides low-level access to the underlying XML representation
     * of the gestational age field.
     *
     * @return Ga the gestational age as a constrained XML string type
     */
    Ga xgetGa();

    /**
     * Sets the gestational age (GA) at the time of the ultrasound examination.
     *
     * @param p0 String the gestational age value to set
     */
    void setGa(final String p0);

    /**
     * Sets the gestational age (GA) using an XML string type.
     *
     * This method provides low-level access to set the underlying XML representation
     * of the gestational age field.
     *
     * @param p0 Ga the gestational age to set as a constrained XML string type
     */
    void xsetGa(final Ga p0);

    /**
     * Gets the results of the ultrasound examination.
     *
     * @return String the ultrasound examination results
     */
    String getResults();

    /**
     * Gets the results of the ultrasound examination as an XML string type.
     *
     * This method provides low-level access to the underlying XML representation
     * of the results field.
     *
     * @return XmlString the ultrasound examination results as XML type
     */
    XmlString xgetResults();

    /**
     * Sets the results of the ultrasound examination.
     *
     * @param p0 String the ultrasound examination results to set
     */
    void setResults(final String p0);

    /**
     * Sets the results of the ultrasound examination using an XML string type.
     *
     * This method provides low-level access to set the underlying XML representation
     * of the results field.
     *
     * @param p0 XmlString the ultrasound examination results to set as XML type
     */
    void xsetResults(final XmlString p0);

    /**
     * Represents a constrained XML string type for gestational age (GA) values.
     *
     * This interface provides a type-safe representation of gestational age within
     * the ultrasound data structure, ensuring values conform to the expected schema
     * constraints defined in the AR2005 XML schema.
     *
     * @see XmlString
     * @since 2026-01-23
     */
    public interface Ga extends XmlString
    {
        public static final SchemaType type = (SchemaType)XmlBeans.typeSystemForClassLoader(Ga.class.getClassLoader(), "schemaorg_apache_xmlbeans.system.s9C023B7D67311A3187802DA7FD51EA38").resolveHandle("gab8beelemtype");

        /**
         * Factory class for creating Ga instances.
         *
         * Provides static methods to create new Ga objects with or without
         * XML processing options for schema validation and other XMLBeans features.
         *
         * @since 2026-01-23
         */
        public static final class Factory
        {
            /**
             * Creates a new Ga instance from an object value.
             *
             * @param obj Object the value to convert to a Ga instance
             * @return Ga a new Ga instance initialized with the given value
             */
            public static Ga newValue(final Object obj) {
                return (Ga)Ga.type.newValue(obj);
            }

            /**
             * Creates a new Ga instance with default XML processing options.
             *
             * @return Ga a new empty Ga instance
             */
            public static Ga newInstance() {
                return (Ga)XmlBeans.getContextTypeLoader().newInstance(Ga.type, (XmlOptions)null);
            }

            /**
             * Creates a new Ga instance with specified XML processing options.
             *
             * @param options XmlOptions the XML processing options for schema validation and other features
             * @return Ga a new empty Ga instance configured with the given options
             */
            public static Ga newInstance(final XmlOptions options) {
                return (Ga)XmlBeans.getContextTypeLoader().newInstance(Ga.type, options);
            }

            private Factory() {
            }
        }
    }

    /**
     * Factory class for creating and parsing UltrasoundType instances.
     *
     * Provides comprehensive static methods to create new UltrasoundType objects
     * and parse XML content from various sources including strings, files, URLs,
     * streams, readers, and DOM nodes. All parsing methods support optional
     * XML processing options for schema validation and other XMLBeans features.
     *
     * @since 2026-01-23
     */
    public static final class Factory
    {
        /**
         * Creates a new UltrasoundType instance with default XML processing options.
         *
         * @return UltrasoundType a new empty UltrasoundType instance
         */
        public static UltrasoundType newInstance() {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().newInstance(UltrasoundType.type, (XmlOptions)null);
        }

        /**
         * Creates a new UltrasoundType instance with specified XML processing options.
         *
         * @param options XmlOptions the XML processing options for schema validation and other features
         * @return UltrasoundType a new empty UltrasoundType instance configured with the given options
         */
        public static UltrasoundType newInstance(final XmlOptions options) {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().newInstance(UltrasoundType.type, options);
        }

        /**
         * Parses an XML string into an UltrasoundType instance with default options.
         *
         * @param xmlAsString String the XML content to parse
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         */
        public static UltrasoundType parse(final String xmlAsString) throws XmlException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(xmlAsString, UltrasoundType.type, (XmlOptions)null);
        }

        /**
         * Parses an XML string into an UltrasoundType instance with specified options.
         *
         * @param xmlAsString String the XML content to parse
         * @param options XmlOptions the XML processing options for schema validation and other features
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         */
        public static UltrasoundType parse(final String xmlAsString, final XmlOptions options) throws XmlException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(xmlAsString, UltrasoundType.type, options);
        }

        /**
         * Parses an XML file into an UltrasoundType instance with default options.
         *
         * @param file File the file containing XML content to parse
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         * @throws IOException if there is an error reading the file
         */
        public static UltrasoundType parse(final File file) throws XmlException, IOException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(file, UltrasoundType.type, (XmlOptions)null);
        }

        /**
         * Parses an XML file into an UltrasoundType instance with specified options.
         *
         * @param file File the file containing XML content to parse
         * @param options XmlOptions the XML processing options for schema validation and other features
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         * @throws IOException if there is an error reading the file
         */
        public static UltrasoundType parse(final File file, final XmlOptions options) throws XmlException, IOException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(file, UltrasoundType.type, options);
        }

        /**
         * Parses XML content from a URL into an UltrasoundType instance with default options.
         *
         * @param u URL the URL to fetch XML content from
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         * @throws IOException if there is an error fetching content from the URL
         */
        public static UltrasoundType parse(final URL u) throws XmlException, IOException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(u, UltrasoundType.type, (XmlOptions)null);
        }

        /**
         * Parses XML content from a URL into an UltrasoundType instance with specified options.
         *
         * @param u URL the URL to fetch XML content from
         * @param options XmlOptions the XML processing options for schema validation and other features
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         * @throws IOException if there is an error fetching content from the URL
         */
        public static UltrasoundType parse(final URL u, final XmlOptions options) throws XmlException, IOException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(u, UltrasoundType.type, options);
        }

        /**
         * Parses XML content from an input stream into an UltrasoundType instance with default options.
         *
         * @param is InputStream the input stream containing XML content to parse
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         * @throws IOException if there is an error reading from the input stream
         */
        public static UltrasoundType parse(final InputStream is) throws XmlException, IOException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(is, UltrasoundType.type, (XmlOptions)null);
        }

        /**
         * Parses XML content from an input stream into an UltrasoundType instance with specified options.
         *
         * @param is InputStream the input stream containing XML content to parse
         * @param options XmlOptions the XML processing options for schema validation and other features
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         * @throws IOException if there is an error reading from the input stream
         */
        public static UltrasoundType parse(final InputStream is, final XmlOptions options) throws XmlException, IOException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(is, UltrasoundType.type, options);
        }

        /**
         * Parses XML content from a reader into an UltrasoundType instance with default options.
         *
         * @param r Reader the reader containing XML content to parse
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         * @throws IOException if there is an error reading from the reader
         */
        public static UltrasoundType parse(final Reader r) throws XmlException, IOException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(r, UltrasoundType.type, (XmlOptions)null);
        }

        /**
         * Parses XML content from a reader into an UltrasoundType instance with specified options.
         *
         * @param r Reader the reader containing XML content to parse
         * @param options XmlOptions the XML processing options for schema validation and other features
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         * @throws IOException if there is an error reading from the reader
         */
        public static UltrasoundType parse(final Reader r, final XmlOptions options) throws XmlException, IOException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(r, UltrasoundType.type, options);
        }

        /**
         * Parses XML content from an XMLStreamReader into an UltrasoundType instance with default options.
         *
         * @param sr XMLStreamReader the stream reader positioned at the XML content to parse
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         */
        public static UltrasoundType parse(final XMLStreamReader sr) throws XmlException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(sr, UltrasoundType.type, (XmlOptions)null);
        }

        /**
         * Parses XML content from an XMLStreamReader into an UltrasoundType instance with specified options.
         *
         * @param sr XMLStreamReader the stream reader positioned at the XML content to parse
         * @param options XmlOptions the XML processing options for schema validation and other features
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         */
        public static UltrasoundType parse(final XMLStreamReader sr, final XmlOptions options) throws XmlException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(sr, UltrasoundType.type, options);
        }

        /**
         * Parses XML content from a DOM node into an UltrasoundType instance with default options.
         *
         * @param node Node the DOM node containing XML content to parse
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         */
        public static UltrasoundType parse(final Node node) throws XmlException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(node, UltrasoundType.type, (XmlOptions)null);
        }

        /**
         * Parses XML content from a DOM node into an UltrasoundType instance with specified options.
         *
         * @param node Node the DOM node containing XML content to parse
         * @param options XmlOptions the XML processing options for schema validation and other features
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         */
        public static UltrasoundType parse(final Node node, final XmlOptions options) throws XmlException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(node, UltrasoundType.type, options);
        }

        /**
         * Parses XML content from an XMLInputStream into an UltrasoundType instance with default options.
         *
         * @param xis XMLInputStream the XML input stream to parse
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         * @throws XMLStreamException if there is an error reading from the XML stream
         * @deprecated XMLInputStream is deprecated in favor of XMLStreamReader
         */
        @Deprecated
        public static UltrasoundType parse(final XMLInputStream xis) throws XmlException, XMLStreamException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(xis, UltrasoundType.type, (XmlOptions)null);
        }

        /**
         * Parses XML content from an XMLInputStream into an UltrasoundType instance with specified options.
         *
         * @param xis XMLInputStream the XML input stream to parse
         * @param options XmlOptions the XML processing options for schema validation and other features
         * @return UltrasoundType the parsed UltrasoundType instance
         * @throws XmlException if the XML is invalid or does not conform to the schema
         * @throws XMLStreamException if there is an error reading from the XML stream
         * @deprecated XMLInputStream is deprecated in favor of XMLStreamReader
         */
        @Deprecated
        public static UltrasoundType parse(final XMLInputStream xis, final XmlOptions options) throws XmlException, XMLStreamException {
            return (UltrasoundType)XmlBeans.getContextTypeLoader().parse(xis, UltrasoundType.type, options);
        }

        /**
         * Creates a validating XMLInputStream from an existing XMLInputStream with default options.
         *
         * @param xis XMLInputStream the XML input stream to wrap with validation
         * @return XMLInputStream a validating XML input stream
         * @throws XmlException if the XML is invalid or does not conform to the schema
         * @throws XMLStreamException if there is an error reading from the XML stream
         * @deprecated XMLInputStream is deprecated in favor of XMLStreamReader
         */
        @Deprecated
        public static XMLInputStream newValidatingXMLInputStream(final XMLInputStream xis) throws XmlException, XMLStreamException {
            return XmlBeans.getContextTypeLoader().newValidatingXMLInputStream(xis, UltrasoundType.type, (XmlOptions)null);
        }

        /**
         * Creates a validating XMLInputStream from an existing XMLInputStream with specified options.
         *
         * @param xis XMLInputStream the XML input stream to wrap with validation
         * @param options XmlOptions the XML processing options for schema validation and other features
         * @return XMLInputStream a validating XML input stream
         * @throws XmlException if the XML is invalid or does not conform to the schema
         * @throws XMLStreamException if there is an error reading from the XML stream
         * @deprecated XMLInputStream is deprecated in favor of XMLStreamReader
         */
        @Deprecated
        public static XMLInputStream newValidatingXMLInputStream(final XMLInputStream xis, final XmlOptions options) throws XmlException, XMLStreamException {
            return XmlBeans.getContextTypeLoader().newValidatingXMLInputStream(xis, UltrasoundType.type, options);
        }

        private Factory() {
        }
    }
}
