package ca.openosp.openo.ar2005.impl;

import java.util.List;
import java.util.ArrayList;

import org.apache.xmlbeans.impl.values.JavaIntHolderEx;
import org.apache.xmlbeans.impl.values.JavaStringHolderEx;
import org.apache.xmlbeans.impl.values.JavaStringEnumerationHolderEx;
import org.apache.xmlbeans.XmlDate;
import java.util.Calendar;
import org.apache.xmlbeans.StringEnumAbstractBase;
import org.apache.xmlbeans.XmlObject;
import org.apache.xmlbeans.XmlString;
import org.apache.xmlbeans.SimpleValue;
import org.apache.xmlbeans.SchemaType;
import javax.xml.namespace.QName;
import ca.openosp.openo.ar2005.PatientInformation;
import org.apache.xmlbeans.impl.values.XmlComplexContentImpl;

/**
 * Implementation of PatientInformation interface for AR2005 (Antenatal Record 2005) form schema.
 *
 * <p>This class is automatically generated by Apache XMLBeans from the AR2005 XML Schema Definition (XSD).
 * It provides XML binding functionality for patient demographic and medical information used in antenatal
 * care records within the OpenO EMR system.</p>
 *
 * <p>The implementation manages comprehensive patient data including:</p>
 * <ul>
 *   <li>Demographics: name, address, contact information</li>
 *   <li>Personal details: date of birth, age, language, occupation, education level</li>
 *   <li>Healthcare identifiers: Health Insurance Number (HIN), file number</li>
 *   <li>Social determinants: marital status, ethnic background</li>
 *   <li>Clinical information: allergies, medications</li>
 * </ul>
 *
 * <p>This class uses XMLBeans' internal store mechanism for thread-safe XML element access and manipulation.
 * All getter and setter methods are synchronized using the monitor pattern to ensure thread safety when
 * accessing or modifying patient information.</p>
 *
 * <p><strong>Healthcare Context:</strong> The AR2005 form is part of the British Columbia Antenatal Record
 * (BCAR) system used for tracking prenatal care across multiple jurisdictions in Canada. Patient information
 * captured through this implementation must comply with PIPEDA/HIPAA privacy regulations.</p>
 *
 * @see ca.openosp.openo.ar2005.PatientInformation
 * @since 2026-01-24
 */
public class PatientInformationImpl extends XmlComplexContentImpl implements PatientInformation
{
    private static final long serialVersionUID = 1L;
    private static final QName LASTNAME$0;
    private static final QName FIRSTNAME$2;
    private static final QName ADDRESS$4;
    private static final QName APT$6;
    private static final QName CITY$8;
    private static final QName PROVINCE$10;
    private static final QName POSTALCODE$12;
    private static final QName HOMEPHONE$14;
    private static final QName WORKPHONE$16;
    private static final QName LANGUAGE$18;
    private static final QName DOB$20;
    private static final QName AGE$22;
    private static final QName OCCUPATION$24;
    private static final QName LEVELOFEDUCATION$26;
    private static final QName HIN$28;
    private static final QName FILENO$30;
    private static final QName ETHNICBACKGROUND$32;
    private static final QName MARITALSTATUS$34;
    private static final QName ALLERGIES$36;
    private static final QName MEDICATIONS$38;

    /**
     * Constructs a new PatientInformationImpl instance with the specified schema type.
     *
     * <p>This constructor is called by the XMLBeans framework during XML deserialization
     * or when creating new instances programmatically. It initializes the internal XML
     * store with the AR2005 patient information schema structure.</p>
     *
     * @param sType SchemaType the schema type definition for PatientInformation
     */
    public PatientInformationImpl(final SchemaType sType) {
        super(sType);
    }

    /**
     * Gets the patient's last name (surname/family name).
     *
     * <p>This method retrieves the lastName element from the XML store in a thread-safe manner.
     * The last name is a critical identifier for patient records and is used throughout the
     * EMR system for patient identification and record linking.</p>
     *
     * @return String the patient's last name, or null if not set
     */
    public String getLastName() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.LASTNAME$0, 0);
            if (target == null) {
                return null;
            }
            return target.getStringValue();
        }
    }

    /**
     * Gets the patient's last name as an XmlString object.
     *
     * <p>This method provides access to the raw XMLBeans XmlString representation, which includes
     * both the string value and XML schema type information. Useful for advanced XML manipulation
     * or when preserving XML-specific attributes.</p>
     *
     * @return XmlString the patient's last name as an XmlString, or null if not set
     */
    public XmlString xgetLastName() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlString target = null;
            target = (XmlString)this.get_store().find_element_user(PatientInformationImpl.LASTNAME$0, 0);
            return target;
        }
    }

    /**
     * Sets the patient's last name (surname/family name).
     *
     * <p>Updates the lastName element in the XML store. If the element doesn't exist,
     * it will be created. This operation is thread-safe and automatically handles
     * XML serialization.</p>
     *
     * <p><strong>Healthcare Note:</strong> Last name changes should be handled carefully
     * and may require audit logging in production systems for patient identification continuity.</p>
     *
     * @param lastName String the patient's last name to set
     */
    public void setLastName(final String lastName) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.LASTNAME$0, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.LASTNAME$0);
            }
            target.setStringValue(lastName);
        }
    }

    /**
     * Sets the patient's last name using an XmlString object.
     *
     * <p>This method accepts an XmlString parameter, allowing setting of both the value
     * and any associated XML schema attributes or metadata. Used primarily when working
     * with XML documents directly or preserving XML-specific information.</p>
     *
     * @param lastName XmlString the patient's last name as an XmlString object
     */
    public void xsetLastName(final XmlString lastName) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlString target = null;
            target = (XmlString)this.get_store().find_element_user(PatientInformationImpl.LASTNAME$0, 0);
            if (target == null) {
                target = (XmlString)this.get_store().add_element_user(PatientInformationImpl.LASTNAME$0);
            }
            target.set((XmlObject)lastName);
        }
    }

    /**
     * Gets the patient's first name (given name).
     *
     * <p>Retrieves the firstName element from the XML store. The first name is used
     * in conjunction with the last name for patient identification throughout the EMR system.</p>
     *
     * @return String the patient's first name, or null if not set
     */
    public String getFirstName() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.FIRSTNAME$2, 0);
            if (target == null) {
                return null;
            }
            return target.getStringValue();
        }
    }

    /**
     * Gets the patient's first name as an XmlString object.
     *
     * @return XmlString the patient's first name as an XmlString, or null if not set
     */
    public XmlString xgetFirstName() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlString target = null;
            target = (XmlString)this.get_store().find_element_user(PatientInformationImpl.FIRSTNAME$2, 0);
            return target;
        }
    }

    /**
     * Sets the patient's first name (given name).
     *
     * @param firstName String the patient's first name to set
     */
    public void setFirstName(final String firstName) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.FIRSTNAME$2, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.FIRSTNAME$2);
            }
            target.setStringValue(firstName);
        }
    }

    /**
     * Sets the patient's first name using an XmlString object.
     *
     * @param firstName XmlString the patient's first name as an XmlString object
     */
    public void xsetFirstName(final XmlString firstName) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlString target = null;
            target = (XmlString)this.get_store().find_element_user(PatientInformationImpl.FIRSTNAME$2, 0);
            if (target == null) {
                target = (XmlString)this.get_store().add_element_user(PatientInformationImpl.FIRSTNAME$2);
            }
            target.set((XmlObject)firstName);
        }
    }

    /**
     * Gets the patient's street address.
     *
     * @return String the street address, or null if not set
     */
    public String getAddress() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.ADDRESS$4, 0);
            if (target == null) {
                return null;
            }
            return target.getStringValue();
        }
    }

    /**
     * Gets the patient's street address as an XmlString object.
     *
     * @return XmlString the street address as an XmlString, or null if not set
     */
    public XmlString xgetAddress() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlString target = null;
            target = (XmlString)this.get_store().find_element_user(PatientInformationImpl.ADDRESS$4, 0);
            return target;
        }
    }

    /**
     * Sets the patient's street address.
     *
     * @param address String the street address to set
     */
    public void setAddress(final String address) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.ADDRESS$4, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.ADDRESS$4);
            }
            target.setStringValue(address);
        }
    }

    /**
     * Sets the patient's street address using an XmlString object.
     *
     * @param address XmlString the street address as an XmlString object
     */
    public void xsetAddress(final XmlString address) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlString target = null;
            target = (XmlString)this.get_store().find_element_user(PatientInformationImpl.ADDRESS$4, 0);
            if (target == null) {
                target = (XmlString)this.get_store().add_element_user(PatientInformationImpl.ADDRESS$4);
            }
            target.set((XmlObject)address);
        }
    }

    /**
     * Gets the patient's apartment/unit number.
     *
     * @return String the apartment/unit number, or null if not set
     */
    public String getApt() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.APT$6, 0);
            if (target == null) {
                return null;
            }
            return target.getStringValue();
        }
    }

    /**
     * Gets the patient's apartment/unit number as an XmlString object.
     *
     * @return XmlString the apartment/unit number as an XmlString, or null if not set
     */
    public XmlString xgetApt() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlString target = null;
            target = (XmlString)this.get_store().find_element_user(PatientInformationImpl.APT$6, 0);
            return target;
        }
    }

    /**
     * Sets the patient's apartment/unit number.
     *
     * @param apt String the apartment/unit number to set
     */
    public void setApt(final String apt) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.APT$6, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.APT$6);
            }
            target.setStringValue(apt);
        }
    }

    /**
     * Sets the patient's apartment/unit number using an XmlString object.
     *
     * @param apt XmlString the apartment/unit number as an XmlString object
     */
    public void xsetApt(final XmlString apt) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlString target = null;
            target = (XmlString)this.get_store().find_element_user(PatientInformationImpl.APT$6, 0);
            if (target == null) {
                target = (XmlString)this.get_store().add_element_user(PatientInformationImpl.APT$6);
            }
            target.set((XmlObject)apt);
        }
    }

    /**
     * Gets the patient's city of residence.
     *
     * @return String the city name, or null if not set
     */
    public String getCity() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.CITY$8, 0);
            if (target == null) {
                return null;
            }
            return target.getStringValue();
        }
    }

    /**
     * Gets the patient's city as an XmlString object.
     *
     * @return XmlString the city name as an XmlString, or null if not set
     */
    public XmlString xgetCity() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlString target = null;
            target = (XmlString)this.get_store().find_element_user(PatientInformationImpl.CITY$8, 0);
            return target;
        }
    }

    /**
     * Sets the patient's city of residence.
     *
     * @param city String the city name to set
     */
    public void setCity(final String city) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.CITY$8, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.CITY$8);
            }
            target.setStringValue(city);
        }
    }

    /**
     * Sets the patient's city using an XmlString object.
     *
     * @param city XmlString the city name as an XmlString object
     */
    public void xsetCity(final XmlString city) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlString target = null;
            target = (XmlString)this.get_store().find_element_user(PatientInformationImpl.CITY$8, 0);
            if (target == null) {
                target = (XmlString)this.get_store().add_element_user(PatientInformationImpl.CITY$8);
            }
            target.set((XmlObject)city);
        }
    }

    /**
     * Gets the patient's province/territory of residence.
     *
     * <p>Province information is critical for healthcare billing and jurisdictional regulations
     * in Canadian healthcare systems (e.g., BC, ON, AB).</p>
     *
     * @return Province.Enum the province enumeration value, or null if not set
     */
    public Province.Enum getProvince() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.PROVINCE$10, 0);
            if (target == null) {
                return null;
            }
            return (Province.Enum)target.getEnumValue();
        }
    }

    /**
     * Gets the patient's province as a Province XML type.
     *
     * @return Province the province as an XML type object, or null if not set
     */
    public Province xgetProvince() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            Province target = null;
            target = (Province)this.get_store().find_element_user(PatientInformationImpl.PROVINCE$10, 0);
            return target;
        }
    }

    /**
     * Sets the patient's province/territory of residence.
     *
     * @param province Province.Enum the province enumeration value to set
     */
    public void setProvince(final Province.Enum province) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.PROVINCE$10, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.PROVINCE$10);
            }
            target.setEnumValue((StringEnumAbstractBase)province);
        }
    }

    /**
     * Sets the patient's province using a Province XML type.
     *
     * @param province Province the province as an XML type object
     */
    public void xsetProvince(final Province province) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            Province target = null;
            target = (Province)this.get_store().find_element_user(PatientInformationImpl.PROVINCE$10, 0);
            if (target == null) {
                target = (Province)this.get_store().add_element_user(PatientInformationImpl.PROVINCE$10);
            }
            target.set((XmlObject)province);
        }
    }

    /**
     * Gets the patient's postal code (Canadian format).
     *
     * @return String the postal code, or null if not set
     */
    public String getPostalCode() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.POSTALCODE$12, 0);
            if (target == null) {
                return null;
            }
            return target.getStringValue();
        }
    }

    /**
     * Gets the patient's postal code as a PostalCode XML type.
     *
     * @return PostalCode the postal code as an XML type, or null if not set
     */
    public PostalCode xgetPostalCode() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            PostalCode target = null;
            target = (PostalCode)this.get_store().find_element_user(PatientInformationImpl.POSTALCODE$12, 0);
            return target;
        }
    }

    /**
     * Sets the patient's postal code.
     *
     * @param postalCode String the postal code to set
     */
    public void setPostalCode(final String postalCode) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.POSTALCODE$12, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.POSTALCODE$12);
            }
            target.setStringValue(postalCode);
        }
    }

    /**
     * Sets the patient's postal code using a PostalCode XML type.
     *
     * @param postalCode PostalCode the postal code as an XML type object
     */
    public void xsetPostalCode(final PostalCode postalCode) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            PostalCode target = null;
            target = (PostalCode)this.get_store().find_element_user(PatientInformationImpl.POSTALCODE$12, 0);
            if (target == null) {
                target = (PostalCode)this.get_store().add_element_user(PatientInformationImpl.POSTALCODE$12);
            }
            target.set((XmlObject)postalCode);
        }
    }

    /**
     * Gets the patient's home phone number.
     *
     * @return String the home phone number, or null if not set
     */
    public String getHomePhone() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.HOMEPHONE$14, 0);
            if (target == null) {
                return null;
            }
            return target.getStringValue();
        }
    }

    /**
     * Gets the patient's home phone number as a HomePhone XML type.
     *
     * @return HomePhone the home phone as an XML type, or null if not set
     */
    public HomePhone xgetHomePhone() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            HomePhone target = null;
            target = (HomePhone)this.get_store().find_element_user(PatientInformationImpl.HOMEPHONE$14, 0);
            return target;
        }
    }

    /**
     * Sets the patient's home phone number.
     *
     * @param homePhone String the home phone number to set
     */
    public void setHomePhone(final String homePhone) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.HOMEPHONE$14, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.HOMEPHONE$14);
            }
            target.setStringValue(homePhone);
        }
    }

    /**
     * Sets the patient's home phone using a HomePhone XML type.
     *
     * @param homePhone HomePhone the home phone as an XML type object
     */
    public void xsetHomePhone(final HomePhone homePhone) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            HomePhone target = null;
            target = (HomePhone)this.get_store().find_element_user(PatientInformationImpl.HOMEPHONE$14, 0);
            if (target == null) {
                target = (HomePhone)this.get_store().add_element_user(PatientInformationImpl.HOMEPHONE$14);
            }
            target.set((XmlObject)homePhone);
        }
    }

    /**
     * Gets the patient's work phone number.
     *
     * @return String the work phone number, or null if not set
     */
    public String getWorkPhone() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.WORKPHONE$16, 0);
            if (target == null) {
                return null;
            }
            return target.getStringValue();
        }
    }

    /**
     * Gets the patient's work phone number as a WorkPhone XML type.
     *
     * @return WorkPhone the work phone as an XML type, or null if not set
     */
    public WorkPhone xgetWorkPhone() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            WorkPhone target = null;
            target = (WorkPhone)this.get_store().find_element_user(PatientInformationImpl.WORKPHONE$16, 0);
            return target;
        }
    }

    /**
     * Sets the patient's work phone number.
     *
     * @param workPhone String the work phone number to set
     */
    public void setWorkPhone(final String workPhone) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.WORKPHONE$16, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.WORKPHONE$16);
            }
            target.setStringValue(workPhone);
        }
    }

    /**
     * Sets the patient's work phone using a WorkPhone XML type.
     *
     * @param workPhone WorkPhone the work phone as an XML type object
     */
    public void xsetWorkPhone(final WorkPhone workPhone) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            WorkPhone target = null;
            target = (WorkPhone)this.get_store().find_element_user(PatientInformationImpl.WORKPHONE$16, 0);
            if (target == null) {
                target = (WorkPhone)this.get_store().add_element_user(PatientInformationImpl.WORKPHONE$16);
            }
            target.set((XmlObject)workPhone);
        }
    }

    /**
     * Gets the patient's preferred language for communication.
     *
     * <p>Language preference is important for patient communication and informed consent
     * in healthcare settings.</p>
     *
     * @return Language.Enum the language enumeration value, or null if not set
     */
    public Language.Enum getLanguage() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.LANGUAGE$18, 0);
            if (target == null) {
                return null;
            }
            return (Language.Enum)target.getEnumValue();
        }
    }

    /**
     * Gets the patient's language as a Language XML type.
     *
     * @return Language the language as an XML type, or null if not set
     */
    public Language xgetLanguage() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            Language target = null;
            target = (Language)this.get_store().find_element_user(PatientInformationImpl.LANGUAGE$18, 0);
            return target;
        }
    }

    /**
     * Sets the patient's preferred language.
     *
     * @param language Language.Enum the language enumeration value to set
     */
    public void setLanguage(final Language.Enum language) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.LANGUAGE$18, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.LANGUAGE$18);
            }
            target.setEnumValue((StringEnumAbstractBase)language);
        }
    }

    /**
     * Sets the patient's language using a Language XML type.
     *
     * @param language Language the language as an XML type object
     */
    public void xsetLanguage(final Language language) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            Language target = null;
            target = (Language)this.get_store().find_element_user(PatientInformationImpl.LANGUAGE$18, 0);
            if (target == null) {
                target = (Language)this.get_store().add_element_user(PatientInformationImpl.LANGUAGE$18);
            }
            target.set((XmlObject)language);
        }
    }

    /**
     * Gets the patient's date of birth.
     *
     * <p>Date of birth is a critical healthcare identifier used for age calculation,
     * pediatric care protocols, and patient matching across systems.</p>
     *
     * @return Calendar the date of birth, or null if not set
     */
    public Calendar getDob() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.DOB$20, 0);
            if (target == null) {
                return null;
            }
            return target.getCalendarValue();
        }
    }

    /**
     * Gets the patient's date of birth as an XmlDate.
     *
     * @return XmlDate the date of birth as an XML date type, or null if not set
     */
    public XmlDate xgetDob() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlDate target = null;
            target = (XmlDate)this.get_store().find_element_user(PatientInformationImpl.DOB$20, 0);
            return target;
        }
    }

    /**
     * Sets the patient's date of birth.
     *
     * @param dob Calendar the date of birth to set
     */
    public void setDob(final Calendar dob) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.DOB$20, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.DOB$20);
            }
            target.setCalendarValue(dob);
        }
    }

    /**
     * Sets the patient's date of birth using an XmlDate.
     *
     * @param dob XmlDate the date of birth as an XML date type
     */
    public void xsetDob(final XmlDate dob) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlDate target = null;
            target = (XmlDate)this.get_store().find_element_user(PatientInformationImpl.DOB$20, 0);
            if (target == null) {
                target = (XmlDate)this.get_store().add_element_user(PatientInformationImpl.DOB$20);
            }
            target.set((XmlObject)dob);
        }
    }

    /**
     * Gets the patient's age in years.
     *
     * <p>Age may be calculated from date of birth or entered directly. Used for
     * age-appropriate care protocols and preventive care scheduling.</p>
     *
     * @return int the patient's age in years, or 0 if not set
     */
    public int getAge() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.AGE$22, 0);
            if (target == null) {
                return 0;
            }
            return target.getIntValue();
        }
    }

    /**
     * Gets the patient's age as an Age XML type.
     *
     * @return Age the age as an XML type, or null if not set
     */
    public Age xgetAge() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            Age target = null;
            target = (Age)this.get_store().find_element_user(PatientInformationImpl.AGE$22, 0);
            return target;
        }
    }

    /**
     * Sets the patient's age in years.
     *
     * @param age int the patient's age to set
     */
    public void setAge(final int age) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.AGE$22, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.AGE$22);
            }
            target.setIntValue(age);
        }
    }

    /**
     * Sets the patient's age using an Age XML type.
     *
     * @param age Age the age as an XML type object
     */
    public void xsetAge(final Age age) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            Age target = null;
            target = (Age)this.get_store().find_element_user(PatientInformationImpl.AGE$22, 0);
            if (target == null) {
                target = (Age)this.get_store().add_element_user(PatientInformationImpl.AGE$22);
            }
            target.set((XmlObject)age);
        }
    }

    /**
     * Gets the patient's occupation information.
     *
     * <p>Occupation data is a social determinant of health used in antenatal care
     * for assessing workplace risks and health hazards.</p>
     *
     * @return Occupation the occupation object, or null if not set
     */
    public Occupation getOccupation() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            Occupation target = null;
            target = (Occupation)this.get_store().find_element_user(PatientInformationImpl.OCCUPATION$24, 0);
            if (target == null) {
                return null;
            }
            return target;
        }
    }

    /**
     * Sets the patient's occupation information.
     *
     * @param occupation Occupation the occupation object to set
     */
    public void setOccupation(final Occupation occupation) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            Occupation target = null;
            target = (Occupation)this.get_store().find_element_user(PatientInformationImpl.OCCUPATION$24, 0);
            if (target == null) {
                target = (Occupation)this.get_store().add_element_user(PatientInformationImpl.OCCUPATION$24);
            }
            target.set((XmlObject)occupation);
        }
    }

    /**
     * Adds a new occupation element and returns it for further configuration.
     *
     * @return Occupation the newly created occupation object
     */
    public Occupation addNewOccupation() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            Occupation target = null;
            target = (Occupation)this.get_store().add_element_user(PatientInformationImpl.OCCUPATION$24);
            return target;
        }
    }

    /**
     * Gets the patient's level of education.
     *
     * <p>Education level is a social determinant of health that can influence
     * health literacy and patient education approaches.</p>
     *
     * @return LevelOfEducation.Enum the education level enumeration, or null if not set
     */
    public LevelOfEducation.Enum getLevelOfEducation() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.LEVELOFEDUCATION$26, 0);
            if (target == null) {
                return null;
            }
            return (LevelOfEducation.Enum)target.getEnumValue();
        }
    }

    /**
     * Gets the patient's level of education as a LevelOfEducation XML type.
     *
     * @return LevelOfEducation the education level as an XML type, or null if not set
     */
    public LevelOfEducation xgetLevelOfEducation() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            LevelOfEducation target = null;
            target = (LevelOfEducation)this.get_store().find_element_user(PatientInformationImpl.LEVELOFEDUCATION$26, 0);
            return target;
        }
    }

    /**
     * Sets the patient's level of education.
     *
     * @param levelOfEducation LevelOfEducation.Enum the education level to set
     */
    public void setLevelOfEducation(final LevelOfEducation.Enum levelOfEducation) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.LEVELOFEDUCATION$26, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.LEVELOFEDUCATION$26);
            }
            target.setEnumValue((StringEnumAbstractBase)levelOfEducation);
        }
    }

    /**
     * Sets the patient's level of education using a LevelOfEducation XML type.
     *
     * @param levelOfEducation LevelOfEducation the education level as an XML type
     */
    public void xsetLevelOfEducation(final LevelOfEducation levelOfEducation) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            LevelOfEducation target = null;
            target = (LevelOfEducation)this.get_store().find_element_user(PatientInformationImpl.LEVELOFEDUCATION$26, 0);
            if (target == null) {
                target = (LevelOfEducation)this.get_store().add_element_user(PatientInformationImpl.LEVELOFEDUCATION$26);
            }
            target.set((XmlObject)levelOfEducation);
        }
    }

    /**
     * Gets the patient's Health Insurance Number (HIN).
     *
     * <p>The HIN is a critical healthcare identifier in Canadian provinces used for
     * billing, patient identification, and eligibility verification. This is Protected
     * Health Information (PHI) and must be handled according to PIPEDA/HIPAA regulations.</p>
     *
     * @return Hin the health insurance number object, or null if not set
     */
    public Hin getHin() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            Hin target = null;
            target = (Hin)this.get_store().find_element_user(PatientInformationImpl.HIN$28, 0);
            if (target == null) {
                return null;
            }
            return target;
        }
    }

    /**
     * Sets the patient's Health Insurance Number (HIN).
     *
     * <p><strong>Security Note:</strong> HIN is sensitive PHI and should be protected
     * with appropriate access controls and audit logging.</p>
     *
     * @param hin Hin the health insurance number object to set
     */
    public void setHin(final Hin hin) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            Hin target = null;
            target = (Hin)this.get_store().find_element_user(PatientInformationImpl.HIN$28, 0);
            if (target == null) {
                target = (Hin)this.get_store().add_element_user(PatientInformationImpl.HIN$28);
            }
            target.set((XmlObject)hin);
        }
    }

    /**
     * Adds a new HIN element and returns it for further configuration.
     *
     * @return Hin the newly created HIN object
     */
    public Hin addNewHin() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            Hin target = null;
            target = (Hin)this.get_store().add_element_user(PatientInformationImpl.HIN$28);
            return target;
        }
    }

    /**
     * Gets the patient's file number (chart number).
     *
     * <p>The file number is an internal identifier used by the medical practice
     * for paper chart organization and record keeping.</p>
     *
     * @return String the file number, or null if not set
     */
    public String getFileNo() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.FILENO$30, 0);
            if (target == null) {
                return null;
            }
            return target.getStringValue();
        }
    }

    /**
     * Gets the patient's file number as an XmlString.
     *
     * @return XmlString the file number as an XML string, or null if not set
     */
    public XmlString xgetFileNo() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlString target = null;
            target = (XmlString)this.get_store().find_element_user(PatientInformationImpl.FILENO$30, 0);
            return target;
        }
    }

    /**
     * Sets the patient's file number.
     *
     * @param fileNo String the file number to set
     */
    public void setFileNo(final String fileNo) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.FILENO$30, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.FILENO$30);
            }
            target.setStringValue(fileNo);
        }
    }

    /**
     * Sets the patient's file number using an XmlString.
     *
     * @param fileNo XmlString the file number as an XML string
     */
    public void xsetFileNo(final XmlString fileNo) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlString target = null;
            target = (XmlString)this.get_store().find_element_user(PatientInformationImpl.FILENO$30, 0);
            if (target == null) {
                target = (XmlString)this.get_store().add_element_user(PatientInformationImpl.FILENO$30);
            }
            target.set((XmlObject)fileNo);
        }
    }

    /**
     * Gets the patient's ethnic background information.
     *
     * <p>Ethnic background is a social determinant of health that can influence
     * genetic risk factors, cultural health practices, and healthcare delivery approaches.</p>
     *
     * @return EthnicBackground the ethnic background object, or null if not set
     */
    public EthnicBackground getEthnicBackground() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            EthnicBackground target = null;
            target = (EthnicBackground)this.get_store().find_element_user(PatientInformationImpl.ETHNICBACKGROUND$32, 0);
            if (target == null) {
                return null;
            }
            return target;
        }
    }

    /**
     * Sets the patient's ethnic background information.
     *
     * @param ethnicBackground EthnicBackground the ethnic background object to set
     */
    public void setEthnicBackground(final EthnicBackground ethnicBackground) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            EthnicBackground target = null;
            target = (EthnicBackground)this.get_store().find_element_user(PatientInformationImpl.ETHNICBACKGROUND$32, 0);
            if (target == null) {
                target = (EthnicBackground)this.get_store().add_element_user(PatientInformationImpl.ETHNICBACKGROUND$32);
            }
            target.set((XmlObject)ethnicBackground);
        }
    }

    /**
     * Adds a new ethnic background element and returns it for configuration.
     *
     * @return EthnicBackground the newly created ethnic background object
     */
    public EthnicBackground addNewEthnicBackground() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            EthnicBackground target = null;
            target = (EthnicBackground)this.get_store().add_element_user(PatientInformationImpl.ETHNICBACKGROUND$32);
            return target;
        }
    }

    /**
     * Gets the patient's marital status.
     *
     * <p>Marital status is relevant for support system assessment and next-of-kin
     * determination in healthcare settings.</p>
     *
     * @return MaritalStatus.Enum the marital status enumeration, or null if not set
     */
    public MaritalStatus.Enum getMaritalStatus() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.MARITALSTATUS$34, 0);
            if (target == null) {
                return null;
            }
            return (MaritalStatus.Enum)target.getEnumValue();
        }
    }

    /**
     * Gets the patient's marital status as a MaritalStatus XML type.
     *
     * @return MaritalStatus the marital status as an XML type, or null if not set
     */
    public MaritalStatus xgetMaritalStatus() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            MaritalStatus target = null;
            target = (MaritalStatus)this.get_store().find_element_user(PatientInformationImpl.MARITALSTATUS$34, 0);
            return target;
        }
    }

    /**
     * Sets the patient's marital status.
     *
     * @param maritalStatus MaritalStatus.Enum the marital status to set
     */
    public void setMaritalStatus(final MaritalStatus.Enum maritalStatus) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.MARITALSTATUS$34, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.MARITALSTATUS$34);
            }
            target.setEnumValue((StringEnumAbstractBase)maritalStatus);
        }
    }

    /**
     * Sets the patient's marital status using a MaritalStatus XML type.
     *
     * @param maritalStatus MaritalStatus the marital status as an XML type
     */
    public void xsetMaritalStatus(final MaritalStatus maritalStatus) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            MaritalStatus target = null;
            target = (MaritalStatus)this.get_store().find_element_user(PatientInformationImpl.MARITALSTATUS$34, 0);
            if (target == null) {
                target = (MaritalStatus)this.get_store().add_element_user(PatientInformationImpl.MARITALSTATUS$34);
            }
            target.set((XmlObject)maritalStatus);
        }
    }

    /**
     * Gets the patient's allergy information as a text string.
     *
     * <p><strong>Critical Clinical Information:</strong> Allergies are essential patient
     * safety data that must be checked before prescribing medications or administering treatments.
     * This field contains free-text allergy descriptions from the AR2005 form.</p>
     *
     * @return String the allergies text, or null if not set
     */
    public String getAllergies() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.ALLERGIES$36, 0);
            if (target == null) {
                return null;
            }
            return target.getStringValue();
        }
    }

    /**
     * Gets the patient's allergies as an XmlString.
     *
     * @return XmlString the allergies as an XML string, or null if not set
     */
    public XmlString xgetAllergies() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlString target = null;
            target = (XmlString)this.get_store().find_element_user(PatientInformationImpl.ALLERGIES$36, 0);
            return target;
        }
    }

    /**
     * Sets the patient's allergy information.
     *
     * <p><strong>Clinical Safety Note:</strong> Changes to allergy information should
     * trigger alerts and be prominently displayed in the patient's medical record.</p>
     *
     * @param allergies String the allergies text to set
     */
    public void setAllergies(final String allergies) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            SimpleValue target = null;
            target = (SimpleValue)this.get_store().find_element_user(PatientInformationImpl.ALLERGIES$36, 0);
            if (target == null) {
                target = (SimpleValue)this.get_store().add_element_user(PatientInformationImpl.ALLERGIES$36);
            }
            target.setStringValue(allergies);
        }
    }

    /**
     * Sets the patient's allergies using an XmlString.
     *
     * @param allergies XmlString the allergies as an XML string
     */
    public void xsetAllergies(final XmlString allergies) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            XmlString target = null;
            target = (XmlString)this.get_store().find_element_user(PatientInformationImpl.ALLERGIES$36, 0);
            if (target == null) {
                target = (XmlString)this.get_store().add_element_user(PatientInformationImpl.ALLERGIES$36);
            }
            target.set((XmlObject)allergies);
        }
    }

    /**
     * Gets the patient's current medications information.
     *
     * <p><strong>Clinical Information:</strong> Current medications are critical for
     * assessing drug interactions, contraindications, and medication reconciliation during
     * antenatal care.</p>
     *
     * @return Medications the medications object, or null if not set
     */
    public Medications getMedications() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            Medications target = null;
            target = (Medications)this.get_store().find_element_user(PatientInformationImpl.MEDICATIONS$38, 0);
            if (target == null) {
                return null;
            }
            return target;
        }
    }

    /**
     * Sets the patient's medications information.
     *
     * @param medications Medications the medications object to set
     */
    public void setMedications(final Medications medications) {
        synchronized (this.monitor()) {
            this.check_orphaned();
            Medications target = null;
            target = (Medications)this.get_store().find_element_user(PatientInformationImpl.MEDICATIONS$38, 0);
            if (target == null) {
                target = (Medications)this.get_store().add_element_user(PatientInformationImpl.MEDICATIONS$38);
            }
            target.set((XmlObject)medications);
        }
    }

    /**
     * Adds a new medications element and returns it for configuration.
     *
     * @return Medications the newly created medications object
     */
    public Medications addNewMedications() {
        synchronized (this.monitor()) {
            this.check_orphaned();
            Medications target = null;
            target = (Medications)this.get_store().add_element_user(PatientInformationImpl.MEDICATIONS$38);
            return target;
        }
    }
    
    static {
        LASTNAME$0 = new QName("http://www.oscarmcmaster.org/AR2005", "lastName");
        FIRSTNAME$2 = new QName("http://www.oscarmcmaster.org/AR2005", "firstName");
        ADDRESS$4 = new QName("http://www.oscarmcmaster.org/AR2005", "address");
        APT$6 = new QName("http://www.oscarmcmaster.org/AR2005", "apt");
        CITY$8 = new QName("http://www.oscarmcmaster.org/AR2005", "city");
        PROVINCE$10 = new QName("http://www.oscarmcmaster.org/AR2005", "province");
        POSTALCODE$12 = new QName("http://www.oscarmcmaster.org/AR2005", "postalCode");
        HOMEPHONE$14 = new QName("http://www.oscarmcmaster.org/AR2005", "homePhone");
        WORKPHONE$16 = new QName("http://www.oscarmcmaster.org/AR2005", "workPhone");
        LANGUAGE$18 = new QName("http://www.oscarmcmaster.org/AR2005", "language");
        DOB$20 = new QName("http://www.oscarmcmaster.org/AR2005", "dob");
        AGE$22 = new QName("http://www.oscarmcmaster.org/AR2005", "age");
        OCCUPATION$24 = new QName("http://www.oscarmcmaster.org/AR2005", "occupation");
        LEVELOFEDUCATION$26 = new QName("http://www.oscarmcmaster.org/AR2005", "levelOfEducation");
        HIN$28 = new QName("http://www.oscarmcmaster.org/AR2005", "hin");
        FILENO$30 = new QName("http://www.oscarmcmaster.org/AR2005", "fileNo");
        ETHNICBACKGROUND$32 = new QName("http://www.oscarmcmaster.org/AR2005", "ethnicBackground");
        MARITALSTATUS$34 = new QName("http://www.oscarmcmaster.org/AR2005", "maritalStatus");
        ALLERGIES$36 = new QName("http://www.oscarmcmaster.org/AR2005", "allergies");
        MEDICATIONS$38 = new QName("http://www.oscarmcmaster.org/AR2005", "medications");
    }

    /**
     * XMLBeans implementation for Province enumeration type.
     *
     * <p>Handles Canadian province/territory codes (e.g., BC, ON, AB) used for
     * jurisdictional healthcare billing and regulations.</p>
     */
    public static class ProvinceImpl extends JavaStringEnumerationHolderEx implements Province
    {
        private static final long serialVersionUID = 1L;

        /**
         * Constructs a new ProvinceImpl with the specified schema type.
         *
         * @param sType SchemaType the schema type definition
         */
        public ProvinceImpl(final SchemaType sType) {
            super(sType, false);
        }

        /**
         * Protected constructor for schema type with validation control.
         *
         * @param sType SchemaType the schema type definition
         * @param b boolean validation flag
         */
        protected ProvinceImpl(final SchemaType sType, final boolean b) {
            super(sType, b);
        }
    }

    /**
     * XMLBeans implementation for PostalCode type.
     *
     * <p>Validates and stores Canadian postal codes in the format A1A 1A1.</p>
     */
    public static class PostalCodeImpl extends JavaStringHolderEx implements PostalCode
    {
        private static final long serialVersionUID = 1L;

        /**
         * Constructs a new PostalCodeImpl with the specified schema type.
         *
         * @param sType SchemaType the schema type definition
         */
        public PostalCodeImpl(final SchemaType sType) {
            super(sType, false);
        }

        /**
         * Protected constructor for schema type with validation control.
         *
         * @param sType SchemaType the schema type definition
         * @param b boolean validation flag
         */
        protected PostalCodeImpl(final SchemaType sType, final boolean b) {
            super(sType, b);
        }
    }

    /**
     * XMLBeans implementation for HomePhone type.
     *
     * <p>Stores and validates home phone numbers.</p>
     */
    public static class HomePhoneImpl extends JavaStringHolderEx implements HomePhone
    {
        private static final long serialVersionUID = 1L;

        /**
         * Constructs a new HomePhoneImpl with the specified schema type.
         *
         * @param sType SchemaType the schema type definition
         */
        public HomePhoneImpl(final SchemaType sType) {
            super(sType, false);
        }

        /**
         * Protected constructor for schema type with validation control.
         *
         * @param sType SchemaType the schema type definition
         * @param b boolean validation flag
         */
        protected HomePhoneImpl(final SchemaType sType, final boolean b) {
            super(sType, b);
        }
    }

    /**
     * XMLBeans implementation for WorkPhone type.
     *
     * <p>Stores and validates work phone numbers.</p>
     */
    public static class WorkPhoneImpl extends JavaStringHolderEx implements WorkPhone
    {
        private static final long serialVersionUID = 1L;

        /**
         * Constructs a new WorkPhoneImpl with the specified schema type.
         *
         * @param sType SchemaType the schema type definition
         */
        public WorkPhoneImpl(final SchemaType sType) {
            super(sType, false);
        }

        /**
         * Protected constructor for schema type with validation control.
         *
         * @param sType SchemaType the schema type definition
         * @param b boolean validation flag
         */
        protected WorkPhoneImpl(final SchemaType sType, final boolean b) {
            super(sType, b);
        }
    }

    /**
     * XMLBeans implementation for Language enumeration type.
     *
     * <p>Handles language preference codes for patient communication.</p>
     */
    public static class LanguageImpl extends JavaStringEnumerationHolderEx implements Language
    {
        private static final long serialVersionUID = 1L;

        /**
         * Constructs a new LanguageImpl with the specified schema type.
         *
         * @param sType SchemaType the schema type definition
         */
        public LanguageImpl(final SchemaType sType) {
            super(sType, false);
        }

        /**
         * Protected constructor for schema type with validation control.
         *
         * @param sType SchemaType the schema type definition
         * @param b boolean validation flag
         */
        protected LanguageImpl(final SchemaType sType, final boolean b) {
            super(sType, b);
        }
    }

    /**
     * XMLBeans implementation for Age type.
     *
     * <p>Stores patient age as an integer value with schema validation.</p>
     */
    public static class AgeImpl extends JavaIntHolderEx implements Age
    {
        private static final long serialVersionUID = 1L;

        /**
         * Constructs a new AgeImpl with the specified schema type.
         *
         * @param sType SchemaType the schema type definition
         */
        public AgeImpl(final SchemaType sType) {
            super(sType, false);
        }

        /**
         * Protected constructor for schema type with validation control.
         *
         * @param sType SchemaType the schema type definition
         * @param b boolean validation flag
         */
        protected AgeImpl(final SchemaType sType, final boolean b) {
            super(sType, b);
        }
    }

    /**
     * XMLBeans implementation for Occupation complex type.
     *
     * <p>Stores occupation information with both enumerated values and free-text
     * "other" option for occupations not in the predefined list.</p>
     */
    public static class OccupationImpl extends XmlComplexContentImpl implements Occupation
    {
        private static final long serialVersionUID = 1L;
        private static final QName VALUE$0;
        private static final QName OTHER$2;

        /**
         * Constructs a new OccupationImpl with the specified schema type.
         *
         * @param sType SchemaType the schema type definition
         */
        public OccupationImpl(final SchemaType sType) {
            super(sType);
        }

        /**
         * Gets the occupation value from the enumerated list.
         *
         * @return Value.Enum the occupation enumeration value, or null if not set
         */
        public Value.Enum getValue() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                SimpleValue target = null;
                target = (SimpleValue)this.get_store().find_element_user(OccupationImpl.VALUE$0, 0);
                if (target == null) {
                    return null;
                }
                return (Value.Enum)target.getEnumValue();
            }
        }

        /**
         * Gets the occupation value as a Value XML type.
         *
         * @return Value the occupation value as an XML type, or null if not set
         */
        public Value xgetValue() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                Value target = null;
                target = (Value)this.get_store().find_element_user(OccupationImpl.VALUE$0, 0);
                return target;
            }
        }

        /**
         * Sets the occupation value from the enumerated list.
         *
         * @param value Value.Enum the occupation enumeration value to set
         */
        public void setValue(final Value.Enum value) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                SimpleValue target = null;
                target = (SimpleValue)this.get_store().find_element_user(OccupationImpl.VALUE$0, 0);
                if (target == null) {
                    target = (SimpleValue)this.get_store().add_element_user(OccupationImpl.VALUE$0);
                }
                target.setEnumValue((StringEnumAbstractBase)value);
            }
        }

        /**
         * Sets the occupation value using a Value XML type.
         *
         * @param value Value the occupation value as an XML type
         */
        public void xsetValue(final Value value) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                Value target = null;
                target = (Value)this.get_store().find_element_user(OccupationImpl.VALUE$0, 0);
                if (target == null) {
                    target = (Value)this.get_store().add_element_user(OccupationImpl.VALUE$0);
                }
                target.set((XmlObject)value);
            }
        }

        /**
         * Gets the free-text occupation description for "other" occupations.
         *
         * <p>Used when the occupation is not in the predefined enumeration list.</p>
         *
         * @return String the other occupation text, or null if not set
         */
        public String getOther() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                SimpleValue target = null;
                target = (SimpleValue)this.get_store().find_element_user(OccupationImpl.OTHER$2, 0);
                if (target == null) {
                    return null;
                }
                return target.getStringValue();
            }
        }

        /**
         * Gets the other occupation text as an XmlString.
         *
         * @return XmlString the other occupation as an XML string, or null if not set
         */
        public XmlString xgetOther() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                XmlString target = null;
                target = (XmlString)this.get_store().find_element_user(OccupationImpl.OTHER$2, 0);
                return target;
            }
        }

        /**
         * Sets the free-text occupation description.
         *
         * @param other String the other occupation text to set
         */
        public void setOther(final String other) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                SimpleValue target = null;
                target = (SimpleValue)this.get_store().find_element_user(OccupationImpl.OTHER$2, 0);
                if (target == null) {
                    target = (SimpleValue)this.get_store().add_element_user(OccupationImpl.OTHER$2);
                }
                target.setStringValue(other);
            }
        }

        /**
         * Sets the other occupation using an XmlString.
         *
         * @param other XmlString the other occupation as an XML string
         */
        public void xsetOther(final XmlString other) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                XmlString target = null;
                target = (XmlString)this.get_store().find_element_user(OccupationImpl.OTHER$2, 0);
                if (target == null) {
                    target = (XmlString)this.get_store().add_element_user(OccupationImpl.OTHER$2);
                }
                target.set((XmlObject)other);
            }
        }
        
        static {
            VALUE$0 = new QName("http://www.oscarmcmaster.org/AR2005", "value");
            OTHER$2 = new QName("http://www.oscarmcmaster.org/AR2005", "other");
        }

        /**
         * XMLBeans implementation for occupation Value enumeration.
         */
        public static class ValueImpl extends JavaStringEnumerationHolderEx implements Value
        {
            private static final long serialVersionUID = 1L;

            /**
             * Constructs a new ValueImpl with the specified schema type.
             *
             * @param sType SchemaType the schema type definition
             */
            public ValueImpl(final SchemaType sType) {
                super(sType, false);
            }

            /**
             * Protected constructor for schema type with validation control.
             *
             * @param sType SchemaType the schema type definition
             * @param b boolean validation flag
             */
            protected ValueImpl(final SchemaType sType, final boolean b) {
                super(sType, b);
            }
        }
    }

    /**
     * XMLBeans implementation for LevelOfEducation enumeration type.
     *
     * <p>Represents educational attainment levels (e.g., high school, college, university).</p>
     */
    public static class LevelOfEducationImpl extends JavaStringEnumerationHolderEx implements LevelOfEducation
    {
        private static final long serialVersionUID = 1L;

        /**
         * Constructs a new LevelOfEducationImpl with the specified schema type.
         *
         * @param sType SchemaType the schema type definition
         */
        public LevelOfEducationImpl(final SchemaType sType) {
            super(sType, false);
        }

        /**
         * Protected constructor for schema type with validation control.
         *
         * @param sType SchemaType the schema type definition
         * @param b boolean validation flag
         */
        protected LevelOfEducationImpl(final SchemaType sType, final boolean b) {
            super(sType, b);
        }
    }

    /**
     * XMLBeans implementation for Health Insurance Number (HIN) type.
     *
     * <p>Stores the provincial health insurance number with an optional type attribute
     * indicating the province/jurisdiction. This is Protected Health Information (PHI).</p>
     */
    public static class HinImpl extends JavaStringHolderEx implements Hin
    {
        private static final long serialVersionUID = 1L;
        private static final QName TYPE$0;

        /**
         * Constructs a new HinImpl with the specified schema type.
         *
         * @param sType SchemaType the schema type definition
         */
        public HinImpl(final SchemaType sType) {
            super(sType, true);
        }

        /**
         * Protected constructor for schema type with validation control.
         *
         * @param sType SchemaType the schema type definition
         * @param b boolean validation flag
         */
        protected HinImpl(final SchemaType sType, final boolean b) {
            super(sType, b);
        }

        /**
         * Gets the HIN type attribute (province/jurisdiction identifier).
         *
         * @return Type.Enum the HIN type enumeration, or null if not set
         */
        public Type.Enum getType() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                SimpleValue target = null;
                target = (SimpleValue)this.get_store().find_attribute_user(HinImpl.TYPE$0);
                if (target == null) {
                    return null;
                }
                return (Type.Enum)target.getEnumValue();
            }
        }

        /**
         * Gets the HIN type as a Type XML type.
         *
         * @return Type the HIN type as an XML type, or null if not set
         */
        public Type xgetType() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                Type target = null;
                target = (Type)this.get_store().find_attribute_user(HinImpl.TYPE$0);
                return target;
            }
        }

        /**
         * Checks if the HIN type attribute is set.
         *
         * @return boolean true if the type is set, false otherwise
         */
        public boolean isSetType() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                return this.get_store().find_attribute_user(HinImpl.TYPE$0) != null;
            }
        }

        /**
         * Sets the HIN type attribute.
         *
         * @param type Type.Enum the HIN type to set
         */
        public void setType(final Type.Enum type) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                SimpleValue target = null;
                target = (SimpleValue)this.get_store().find_attribute_user(HinImpl.TYPE$0);
                if (target == null) {
                    target = (SimpleValue)this.get_store().add_attribute_user(HinImpl.TYPE$0);
                }
                target.setEnumValue((StringEnumAbstractBase)type);
            }
        }

        /**
         * Sets the HIN type using a Type XML type.
         *
         * @param type Type the HIN type as an XML type
         */
        public void xsetType(final Type type) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                Type target = null;
                target = (Type)this.get_store().find_attribute_user(HinImpl.TYPE$0);
                if (target == null) {
                    target = (Type)this.get_store().add_attribute_user(HinImpl.TYPE$0);
                }
                target.set((XmlObject)type);
            }
        }

        /**
         * Removes the HIN type attribute.
         */
        public void unsetType() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                this.get_store().remove_attribute(HinImpl.TYPE$0);
            }
        }
        
        static {
            TYPE$0 = new QName("", "type");
        }

        /**
         * XMLBeans implementation for HIN Type enumeration.
         */
        public static class TypeImpl extends JavaStringEnumerationHolderEx implements Type
        {
            private static final long serialVersionUID = 1L;

            /**
             * Constructs a new TypeImpl with the specified schema type.
             *
             * @param sType SchemaType the schema type definition
             */
            public TypeImpl(final SchemaType sType) {
                super(sType, false);
            }

            /**
             * Protected constructor for schema type with validation control.
             *
             * @param sType SchemaType the schema type definition
             * @param b boolean validation flag
             */
            protected TypeImpl(final SchemaType sType, final boolean b) {
                super(sType, b);
            }
        }
    }

    /**
     * XMLBeans implementation for EthnicBackground complex type.
     *
     * <p>Manages ethnic background values with support for multi-select options
     * and parent/child ethnic group relationships.</p>
     */
    public static class EthnicBackgroundImpl extends XmlComplexContentImpl implements EthnicBackground
    {
        private static final long serialVersionUID = 1L;
        private static final QName VALUE$0;

        /**
         * Constructs a new EthnicBackgroundImpl with the specified schema type.
         *
         * @param sType SchemaType the schema type definition
         */
        public EthnicBackgroundImpl(final SchemaType sType) {
            super(sType);
        }

        /**
         * Gets all ethnic background values as an array.
         *
         * <p>Supports multiple ethnic background selections.</p>
         *
         * @return Value[] array of ethnic background values
         */
        public Value[] getValueArray() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                final List targetList = new ArrayList();
                this.get_store().find_all_element_users(EthnicBackgroundImpl.VALUE$0, targetList);
                final Value[] result = new Value[targetList.size()];
                targetList.toArray(result);
                return result;
            }
        }
        
        public Value getValueArray(final int i) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                Value target = null;
                target = (Value)this.get_store().find_element_user(EthnicBackgroundImpl.VALUE$0, i);
                if (target == null) {
                    throw new IndexOutOfBoundsException();
                }
                return target;
            }
        }
        
        public int sizeOfValueArray() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                return this.get_store().count_elements(EthnicBackgroundImpl.VALUE$0);
            }
        }
        
        public void setValueArray(final Value[] valueArray) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                this.arraySetterHelper((XmlObject[])valueArray, EthnicBackgroundImpl.VALUE$0);
            }
        }
        
        public void setValueArray(final int i, final Value value) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                Value target = null;
                target = (Value)this.get_store().find_element_user(EthnicBackgroundImpl.VALUE$0, i);
                if (target == null) {
                    throw new IndexOutOfBoundsException();
                }
                target.set((XmlObject)value);
            }
        }
        
        public Value insertNewValue(final int i) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                Value target = null;
                target = (Value)this.get_store().insert_element_user(EthnicBackgroundImpl.VALUE$0, i);
                return target;
            }
        }
        
        public Value addNewValue() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                Value target = null;
                target = (Value)this.get_store().add_element_user(EthnicBackgroundImpl.VALUE$0);
                return target;
            }
        }
        
        public void removeValue(final int i) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                this.get_store().remove_element(EthnicBackgroundImpl.VALUE$0, i);
            }
        }
        
        static {
            VALUE$0 = new QName("http://www.oscarmcmaster.org/AR2005", "value");
        }

        /**
         * XMLBeans implementation for ethnic background Value with parent attribute support.
         */
        public static class ValueImpl extends JavaStringEnumerationHolderEx implements Value
        {
            private static final long serialVersionUID = 1L;
            private static final QName PARENT$0;
            
            public ValueImpl(final SchemaType sType) {
                super(sType, true);
            }
            
            protected ValueImpl(final SchemaType sType, final boolean b) {
                super(sType, b);
            }
            
            public Parent.Enum getParent() {
                synchronized (this.monitor()) {
                    this.check_orphaned();
                    SimpleValue target = null;
                    target = (SimpleValue)this.get_store().find_attribute_user(ValueImpl.PARENT$0);
                    if (target == null) {
                        return null;
                    }
                    return (Parent.Enum)target.getEnumValue();
                }
            }
            
            public Parent xgetParent() {
                synchronized (this.monitor()) {
                    this.check_orphaned();
                    Parent target = null;
                    target = (Parent)this.get_store().find_attribute_user(ValueImpl.PARENT$0);
                    return target;
                }
            }
            
            public boolean isSetParent() {
                synchronized (this.monitor()) {
                    this.check_orphaned();
                    return this.get_store().find_attribute_user(ValueImpl.PARENT$0) != null;
                }
            }
            
            public void setParent(final Parent.Enum parent) {
                synchronized (this.monitor()) {
                    this.check_orphaned();
                    SimpleValue target = null;
                    target = (SimpleValue)this.get_store().find_attribute_user(ValueImpl.PARENT$0);
                    if (target == null) {
                        target = (SimpleValue)this.get_store().add_attribute_user(ValueImpl.PARENT$0);
                    }
                    target.setEnumValue((StringEnumAbstractBase)parent);
                }
            }
            
            public void xsetParent(final Parent parent) {
                synchronized (this.monitor()) {
                    this.check_orphaned();
                    Parent target = null;
                    target = (Parent)this.get_store().find_attribute_user(ValueImpl.PARENT$0);
                    if (target == null) {
                        target = (Parent)this.get_store().add_attribute_user(ValueImpl.PARENT$0);
                    }
                    target.set((XmlObject)parent);
                }
            }
            
            public void unsetParent() {
                synchronized (this.monitor()) {
                    this.check_orphaned();
                    this.get_store().remove_attribute(ValueImpl.PARENT$0);
                }
            }
            
            static {
                PARENT$0 = new QName("", "parent");
            }

            /**
             * XMLBeans implementation for ethnic background Parent enumeration.
             */
            public static class ParentImpl extends JavaStringEnumerationHolderEx implements Parent
            {
                private static final long serialVersionUID = 1L;

                /**
                 * Constructs a new ParentImpl with the specified schema type.
                 *
                 * @param sType SchemaType the schema type definition
                 */
                public ParentImpl(final SchemaType sType) {
                    super(sType, false);
                }

                /**
                 * Protected constructor for schema type with validation control.
                 *
                 * @param sType SchemaType the schema type definition
                 * @param b boolean validation flag
                 */
                protected ParentImpl(final SchemaType sType, final boolean b) {
                    super(sType, b);
                }
            }
        }
    }

    /**
     * XMLBeans implementation for MaritalStatus enumeration type.
     *
     * <p>Represents marital status values (e.g., single, married, divorced, widowed).</p>
     */
    public static class MaritalStatusImpl extends JavaStringEnumerationHolderEx implements MaritalStatus
    {
        private static final long serialVersionUID = 1L;

        /**
         * Constructs a new MaritalStatusImpl with the specified schema type.
         *
         * @param sType SchemaType the schema type definition
         */
        public MaritalStatusImpl(final SchemaType sType) {
            super(sType, false);
        }

        /**
         * Protected constructor for schema type with validation control.
         *
         * @param sType SchemaType the schema type definition
         * @param b boolean validation flag
         */
        protected MaritalStatusImpl(final SchemaType sType, final boolean b) {
            super(sType, b);
        }
    }

    /**
     * XMLBeans implementation for Medications complex type.
     *
     * <p>Manages current medications with support for multiple entries including
     * both enumerated medication values and free-text "other" medications.</p>
     */
    public static class MedicationsImpl extends XmlComplexContentImpl implements Medications
    {
        private static final long serialVersionUID = 1L;
        private static final QName VALUE$0;
        private static final QName OTHER$2;
        
        public MedicationsImpl(final SchemaType sType) {
            super(sType);
        }
        
        public Value.Enum[] getValueArray() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                final List targetList = new ArrayList();
                this.get_store().find_all_element_users(MedicationsImpl.VALUE$0, targetList);
                final Value.Enum[] result = new Value.Enum[targetList.size()];
                for (int i = 0, len = targetList.size(); i < len; ++i) {
                    result[i] = (Value.Enum)((SimpleValue)targetList.get(i)).getEnumValue();
                }
                return result;
            }
        }
        
        public Value.Enum getValueArray(final int i) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                SimpleValue target = null;
                target = (SimpleValue)this.get_store().find_element_user(MedicationsImpl.VALUE$0, i);
                if (target == null) {
                    throw new IndexOutOfBoundsException();
                }
                return (Value.Enum)target.getEnumValue();
            }
        }
        
        public Value[] xgetValueArray() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                final List targetList = new ArrayList();
                this.get_store().find_all_element_users(MedicationsImpl.VALUE$0, targetList);
                final Value[] result = new Value[targetList.size()];
                targetList.toArray(result);
                return result;
            }
        }
        
        public Value xgetValueArray(final int i) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                Value target = null;
                target = (Value)this.get_store().find_element_user(MedicationsImpl.VALUE$0, i);
                if (target == null) {
                    throw new IndexOutOfBoundsException();
                }
                return target;
            }
        }
        
        public int sizeOfValueArray() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                return this.get_store().count_elements(MedicationsImpl.VALUE$0);
            }
        }
        
        public void setValueArray(final Value.Enum[] valueArray) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                this.arraySetterHelper((StringEnumAbstractBase[])valueArray, MedicationsImpl.VALUE$0);
            }
        }
        
        public void setValueArray(final int i, final Value.Enum value) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                SimpleValue target = null;
                target = (SimpleValue)this.get_store().find_element_user(MedicationsImpl.VALUE$0, i);
                if (target == null) {
                    throw new IndexOutOfBoundsException();
                }
                target.setEnumValue((StringEnumAbstractBase)value);
            }
        }
        
        public void xsetValueArray(final Value[] valueArray) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                this.arraySetterHelper((XmlObject[])valueArray, MedicationsImpl.VALUE$0);
            }
        }
        
        public void xsetValueArray(final int i, final Value value) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                Value target = null;
                target = (Value)this.get_store().find_element_user(MedicationsImpl.VALUE$0, i);
                if (target == null) {
                    throw new IndexOutOfBoundsException();
                }
                target.set((XmlObject)value);
            }
        }
        
        public void insertValue(final int i, final Value.Enum value) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                final SimpleValue target = (SimpleValue)this.get_store().insert_element_user(MedicationsImpl.VALUE$0, i);
                target.setEnumValue((StringEnumAbstractBase)value);
            }
        }
        
        public void addValue(final Value.Enum value) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                SimpleValue target = null;
                target = (SimpleValue)this.get_store().add_element_user(MedicationsImpl.VALUE$0);
                target.setEnumValue((StringEnumAbstractBase)value);
            }
        }
        
        public Value insertNewValue(final int i) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                Value target = null;
                target = (Value)this.get_store().insert_element_user(MedicationsImpl.VALUE$0, i);
                return target;
            }
        }
        
        public Value addNewValue() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                Value target = null;
                target = (Value)this.get_store().add_element_user(MedicationsImpl.VALUE$0);
                return target;
            }
        }
        
        public void removeValue(final int i) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                this.get_store().remove_element(MedicationsImpl.VALUE$0, i);
            }
        }
        
        public String[] getOtherArray() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                final List targetList = new ArrayList();
                this.get_store().find_all_element_users(MedicationsImpl.OTHER$2, targetList);
                final String[] result = new String[targetList.size()];
                for (int i = 0, len = targetList.size(); i < len; ++i) {
                    result[i] = ((SimpleValue)targetList.get(i)).getStringValue();
                }
                return result;
            }
        }
        
        public String getOtherArray(final int i) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                SimpleValue target = null;
                target = (SimpleValue)this.get_store().find_element_user(MedicationsImpl.OTHER$2, i);
                if (target == null) {
                    throw new IndexOutOfBoundsException();
                }
                return target.getStringValue();
            }
        }
        
        public XmlString[] xgetOtherArray() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                final List targetList = new ArrayList();
                this.get_store().find_all_element_users(MedicationsImpl.OTHER$2, targetList);
                final XmlString[] result = new XmlString[targetList.size()];
                targetList.toArray(result);
                return result;
            }
        }
        
        public XmlString xgetOtherArray(final int i) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                XmlString target = null;
                target = (XmlString)this.get_store().find_element_user(MedicationsImpl.OTHER$2, i);
                if (target == null) {
                    throw new IndexOutOfBoundsException();
                }
                return target;
            }
        }
        
        public int sizeOfOtherArray() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                return this.get_store().count_elements(MedicationsImpl.OTHER$2);
            }
        }
        
        public void setOtherArray(final String[] otherArray) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                this.arraySetterHelper(otherArray, MedicationsImpl.OTHER$2);
            }
        }
        
        public void setOtherArray(final int i, final String other) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                SimpleValue target = null;
                target = (SimpleValue)this.get_store().find_element_user(MedicationsImpl.OTHER$2, i);
                if (target == null) {
                    throw new IndexOutOfBoundsException();
                }
                target.setStringValue(other);
            }
        }
        
        public void xsetOtherArray(final XmlString[] otherArray) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                this.arraySetterHelper((XmlObject[])otherArray, MedicationsImpl.OTHER$2);
            }
        }
        
        public void xsetOtherArray(final int i, final XmlString other) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                XmlString target = null;
                target = (XmlString)this.get_store().find_element_user(MedicationsImpl.OTHER$2, i);
                if (target == null) {
                    throw new IndexOutOfBoundsException();
                }
                target.set((XmlObject)other);
            }
        }
        
        public void insertOther(final int i, final String other) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                final SimpleValue target = (SimpleValue)this.get_store().insert_element_user(MedicationsImpl.OTHER$2, i);
                target.setStringValue(other);
            }
        }
        
        public void addOther(final String other) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                SimpleValue target = null;
                target = (SimpleValue)this.get_store().add_element_user(MedicationsImpl.OTHER$2);
                target.setStringValue(other);
            }
        }
        
        public XmlString insertNewOther(final int i) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                XmlString target = null;
                target = (XmlString)this.get_store().insert_element_user(MedicationsImpl.OTHER$2, i);
                return target;
            }
        }
        
        public XmlString addNewOther() {
            synchronized (this.monitor()) {
                this.check_orphaned();
                XmlString target = null;
                target = (XmlString)this.get_store().add_element_user(MedicationsImpl.OTHER$2);
                return target;
            }
        }
        
        public void removeOther(final int i) {
            synchronized (this.monitor()) {
                this.check_orphaned();
                this.get_store().remove_element(MedicationsImpl.OTHER$2, i);
            }
        }
        
        static {
            VALUE$0 = new QName("http://www.oscarmcmaster.org/AR2005", "value");
            OTHER$2 = new QName("http://www.oscarmcmaster.org/AR2005", "other");
        }

        /**
         * XMLBeans implementation for medication Value enumeration.
         */
        public static class ValueImpl extends JavaStringEnumerationHolderEx implements Value
        {
            private static final long serialVersionUID = 1L;

            /**
             * Constructs a new ValueImpl with the specified schema type.
             *
             * @param sType SchemaType the schema type definition
             */
            public ValueImpl(final SchemaType sType) {
                super(sType, false);
            }

            /**
             * Protected constructor for schema type with validation control.
             *
             * @param sType SchemaType the schema type definition
             * @param b boolean validation flag
             */
            protected ValueImpl(final SchemaType sType, final boolean b) {
                super(sType, b);
            }
        }
    }
}
